In [2]:
%run Oncokb.ipynb

%run "/home/ubuntu/jupyter_notebooks/Internal/Cancer_hotspot/CH_display_table.ipynb"
    
%run "/home/ubuntu/jupyter_notebooks/Internal/Clinvar/Clinvar_annotation.ipynb"

%run "/home/ubuntu/jupyter_notebooks/Internal/Intogen/intogen_display_table.ipynb"
    
%run "getGeneInfoFromGeneCardsAndNCBI.ipynb"
    
%run "CKB_Core_Gene_Information_Extraction.ipynb"
    
%run "NCBI_gene_id.ipynb"

%run "dbsnp.ipynb"

In [13]:
import pandas as pd
import os
from datetime import datetime
import io
import shutil
import requests
import re
import functools 
import urllib.request
import xmltodict
from xmltodict import parse
import time
import requests
import numpy as np
from IPython.display import HTML, display
from ipywidgets import widgets, interact, Button, Layout, VBox, Output, Label, HTML, HBox
    
#User Input file upload path
USER_INPUT_FOLDER_PATH='/home/ubuntu/jupyter_notebooks/Internal/input_files/'
#Temporary foler path 
TEMP_FOLDER_PATH = '/home/ubuntu/jupyter_notebooks/Internal/input_files/Annotations_temporary/'
#SIFT Indel installation path
SIFT_INDEL_INSTALL_PATH='/home/ubuntu/in-silico_tools/SIFT'
SIFT_INDEL_DB_PATH='/home/ubuntu/in-silico_tools/SIFT/SIFT_INDEL_HG38'
#SIFT 4GPATH
SIFT_4G_INSTALL_PATH = '/home/ubuntu/in-silico_tools/SIFT_4G'
#dbNSFP installation path
dbNSFP_PATH='/home/ubuntu/in-silico_tools/dbNSFP'

Converts xlsx file to vcf file

In [14]:
def convert_to_vcf(input_file, output_file):
    if input_file.endswith('.vcf'):
        # If the input file is already in VCF format, simply copy it to the output location
        shutil.copy(input_file, output_file)
        print(f"File '{input_file}' copied to '{output_file}'")
        return

    # Read the XLSX file into a pandas DataFrame
    df = pd.read_excel(input_file)

    # Extract CHROM and Position from 'Position (hg38)'
    df[['CHROM', 'POS']] = df['Position (hg38)'].str.extract(r'chr(\w+):(\d+)')

    # Create the VCF content
    vcf_content = '##fileformat=VCFv4.2\n'
    vcf_content += '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n'

    for _, row in df.iterrows():
        chrom = row['CHROM']
        pos = row['POS']
        ref = row['Ref']
        alt = row['Alt']
        info = row["VAF DNA RNA"]
        vcf_content += f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t{info}\n'

    # Write the VCF content to a temporary file
    temp_vcf_file_path = 'temp_vcf_file.vcf'
    with open(temp_vcf_file_path, 'w') as temp_vcf_file:
        temp_vcf_file.write(vcf_content)

    # Sort the temporary VCF file based on chromosome positions
    with open(temp_vcf_file_path, 'r') as temp_vcf_file:
        lines = temp_vcf_file.readlines()

    # Remove header lines for sorting
    header_lines = lines[:2]
    vcf_content_to_sort = lines[2:]

    # Sort the VCF content
    sorted_vcf_content = ''.join(sorted(vcf_content_to_sort, key=lambda x: (x.split('\t')[0], int(x.split('\t')[1]))))

    # Write the sorted VCF content to the output file
    with open(output_file, 'w') as vcf_file:
        vcf_file.write(''.join(header_lines) + sorted_vcf_content)

    # Remove temporary VCF file
    os.remove(temp_vcf_file_path)
    print(f"VCF file saved to '{output_file}'")

# Provide your input and output file paths
#input_file_path = 'somatic_snv_and_indel_with_new_variants.xlsx'
#input_file_path = 'Somatic_SNV.vcf_processed_15_var.vcf'
input_file_path = 'Somatic_SNV_with_pathogenic_var.vcf_cgp_snv_indel.vcf'
input_filename = os.path.basename(input_file_path)
input_filename = os.path.splitext(input_filename)[0]
output_file_name=input_filename + '.vcf'
output_file_path = os.path.join(USER_INPUT_FOLDER_PATH+ input_filename + '.vcf')

# Convert the XLSX file to VCF and sort based on chromosome
#convert_to_vcf(input_file_path, output_file_path)

The VCF saved is read and tools like SIFT INDEL, SIFT 4G, dNSFP and CADD-SNV is included. These tools take input as the VCF data

In [15]:
def read_vcf(input_file):
    try:
        with open(input_file, 'r', encoding='latin-1') as f:
            lines = [l for l in f if not l.startswith('##')]
        '''
        # Debug: Print sample lines after filtering
        print("Sample lines after filtering:")
        for line in lines[:5]:  # Print the first 5 lines for inspection
            print(line)
        '''
        data_frame = pd.read_csv(
            io.StringIO(''.join(lines)),
            dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
                   'QUAL': str, 'FILTER': str, 'INFO': str},
            sep='\t'
        )
        
        def extract_dp(text):
          for part in text.split(';'):
            k, v = part.strip().split('=')
            if k == 'DP':
              return int(v)  # Assuming DP value is an integer
          return None  # Return None if DP not found

        # Apply the function to extract DP values and create a new column
        data_frame['Depth'] = data_frame['INFO'].apply(extract_dp)
        data_frame['Allele Frequency (%)'] = (data_frame['HCC1187BL'].str.split(':', expand=True)[3])
        data_frame['Allele Frequency (%)']=data_frame['Allele Frequency (%)'].astype(float)
        data_frame['Allele Frequency (%)']=(data_frame['Allele Frequency (%)']*100)
        if data_frame['#CHROM'].str.contains('chr').any():
            data_frame['#CHROM'] = data_frame['#CHROM'].str.replace('chr', '')
        if data_frame['#CHROM'].str.contains('Chr').any():
            data_frame['#CHROM'] = data_frame['#CHROM'].str.replace('Chr', '')
        
        #data_frame.rename(columns={'INFO': 'Allele Frequency (%)'}, inplace=True)
        #data_frame['Allele Frequency (%)'] = (data_frame['Allele Frequency (%)'] * 100).astype(int)
        data_frame.drop_duplicates(subset=['POS'],inplace = True)
        
    
        return data_frame
    
    except Exception as e:
        print(f"Error reading VCF file: {e}")
        return None
#display(read_vcf('input_files/somatic_snv_and_indel_with_new_variants.vcf'))
#display(read_vcf('input_files/Somatic_SNV.vcf_processed_15_var.vcf'))
#inp_df = read_vcf('input_files/Somatic_SNV.vcf_processed_15_var.vcf')
# inp_df = read_vcf('input_files/Somatic_SNV.vcf_processed.vcf')
inp_df = read_vcf(USER_INPUT_FOLDER_PATH+input_file_path)
display(inp_df)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%)
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0
2,1,64931096,.,A,T,.,PASS,DP=206;MQ=105.45;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:50,0:0.000:25,0:25,0:50:.:.","0/1:126.57:81,75:0.481:33,36:48,39:156:46,35,3...",JAK1,206,0.0
3,1,64969201,.,G,GT,.,PASS,DP=210;MQ=214.69;FractionInformativeReads=0.886,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,0:0.000:18,0:27,0:45:.:.","0/1:110.62:74,67:0.475:34,37:40,30:141:35,39,2...",JAK1,210,0.0
4,1,65022230,.,G,A,.,PASS,DP=243;MQ=214.83;FractionInformativeReads=0.996,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:62,0:0.000:31,0:31,0:62:.:.","0/1:132.48:105,75:0.417:56,39:49,36:180:45,60,...",JAK1,243,0.0
5,1,97142697,.,T,G,.,PASS,DP=116;MQ=190.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:21,0:28,0:49:.:.","0/1:181.80:0,67:1.000:0,36:0,31:67:0,0,38,29:0...",DPYD,116,0.0
6,1,97177779,.,T,A,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.000:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",DPYD,116,0.0
7,1,97371462,.,G,A,.,PASS,DP=109;MQ=190.06;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:20,0:26,0:46:.:.","0/1:102.48:33,30:0.476:18,9:15,21:63:15,18,19,...",DPYD,109,0.0
8,1,97527794,.,GA,G,.,PASS,DP=132;MQ=193.39;FractionInformativeReads=0.780,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,2:0.059:17,1:15,1:34:.:.","0/1:56.78:31,38:0.551:14,20:17,18:69:15,16,15,...",DPYD,132,5.9
9,1,156865995,.,A,G,.,PASS,DP=238;MQ=208.22;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:72,0:0.000:38,0:34,0:72:.:.","0/1:27.68:158,8:0.048:73,2:85,6:166:88,70,3,5:...",NTRK1,238,0.0
10,1,162657625,.,A,T,.,PASS,DP=183;MQ=215.95;FractionInformativeReads=0.995,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:22,0:24,0:46:.:.","0/1:114.07:72,64:0.471:35,33:37,31:136:28,44,1...",DDR2,183,0.0
11,1,162696199,.,CT,C,.,PASS,DP=190;MQ=199.83;FractionInformativeReads=0.795,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:35,2:0.054:16,0:19,2:37:.:.","0/1:76.59:59,55:0.482:29,28:30,27:114:26,33,21...",DDR2,190,5.4
12,1,162763185,.,AT,A,.,PASS,DP=156;MQ=200.81;FractionInformativeReads=0.872,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:30,1:0.032:12,1:18,0:31:.:.","0/1:57.07:57,48:0.457:24,19:33,29:105:26,31,31...",DDR2,156,3.2
13,1,162772543,.,G,T,.,PASS,DP=207;MQ=211.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:28,0:31,0:59:.:.","0/1:67.24:114,34:0.230:55,18:59,16:148:67,47,1...",DDR2,207,0.0
14,1,179148318,.,G,A,.,PASS,DP=176;MQ=210.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:38,0:0.000:14,0:24,0:38:.:.","0/1:94.31:73,65:0.471:38,34:35,31:138:35,38,29...",ABL2,176,0.0
15,1,193123292,.,A,G,.,PASS,DP=211;MQ=152.15;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:54,0:0.000:24,0:30,0:54:.:.","0/1:141.73:74,83:0.529:31,35:43,48:157:42,32,3...",CDC73,211,0.0
16,1,240911986,.,CA,C,.,PASS,DP=137;MQ=156.33;FractionInformativeReads=0.876,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:34,3:0.081:16,1:18,2:37:.:.","0/1:17.70:59,24:0.289:30,15:29,9:83:42,17,12,1...",RGS7,137,8.1
17,1,241058004,.,C,A,.,PASS,DP=155;MQ=203.61;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:18,0:24,0:42:.:.","0/1:59.13:83,30:0.265:39,9:44,21:113:35,48,21,...",RGS7,155,0.0
18,1,241083225,.,CA,C,.,PASS,DP=156;MQ=148.37;FractionInformativeReads=0.788,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,2:0.053:21,1:15,1:38:.:.","0/1:62.10:42,43:0.506:29,19:13,24:85:12,30,24,...",RGS7,156,5.3
19,1,241087972,.,CTCTCTATA,C,.,PASS,DP=147;MQ=136.05;FractionInformativeReads=0.932,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:31,0:0.000:15,0:16,0:31:.:.","0/1:57.62:63,43:0.406:30,22:33,21:106:26,37,10...",RGS7,147,0.0
20,1,241094238,.,A,AAC,.,PASS,DP=147;MQ=180.33;FractionInformativeReads=0.585,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:26,0:0.000:12,0:14,0:26:.:.","0/1:55.38:28,32:0.533:11,15:17,17:60:10,18,14,...",RGS7,147,0.0
21,1,241126809,.,AT,A,.,PASS,DP=207;MQ=211.76;FractionInformativeReads=0.870,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,3:0.070:20,2:20,1:43:.:.","0/1:33.67:98,39:0.285:47,23:51,16:137:63,35,25...",RGS7,207,7.0
22,1,241128709,.,A,G,.,PASS,DP=207;MQ=198.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:72,1:0.014:31,1:41,0:73:.:.","0/1:71.38:104,30:0.224:59,16:45,14:134:71,33,1...",RGS7,207,1.4
23,1,241232136,.,C,T,.,PASS,DP=206;MQ=207.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:58,0:0.000:28,0:30,0:58:.:.","0/1:129.39:83,65:0.439:35,34:48,31:148:50,33,2...",RGS7,206,0.0
24,1,241234485,.,CT,C,.,PASS,DP=195;MQ=208.34;FractionInformativeReads=0.841,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,1:0.022:24,0:21,1:46:.:.","0/1:93.31:62,56:0.475:26,32:36,24:118:32,30,33...",RGS7,195,2.2
25,1,241318460,.,CT,C,.,PASS,DP=200;MQ=191.20;FractionInformativeReads=0.815,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,0:0.000:19,0:17,0:36:.:.","0/1:87.83:66,61:0.480:36,32:30,29:127:33,33,28...",RGS7,200,0.0
26,1,243727332,.,T,G,.,PASS,DP=156;MQ=194.28;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:41,0:0.000:24,0:17,0:41:.:.","0/1:122.28:42,73:0.635:24,36:18,37:115:20,22,4...",AKT3,156,0.0
27,2,29197299,.,C,G,.,PASS,DP=127;MQ=186.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:25,0:31,0:56:.:.","0/1:92.69:44,27:0.380:17,12:27,15:71:23,21,12,...",ALK,127,0.0
28,2,29249631,.,T,C,.,PASS,DP=123;MQ=182.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:57,0:0.000:25,0:32,0:57:.:.","0/1:100.58:39,27:0.409:19,20:20,7:66:19,20,15,...",ALK,123,0.0
29,2,29266768,.,T,C,.,PASS,DP=119;MQ=201.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:20,0:22,0:42:.:.","0/1:95.47:42,35:0.455:21,19:21,16:77:19,23,16,...",ALK,119,0.0
30,2,29394870,.,GT,G,.,PASS,DP=135;MQ=188.23;FractionInformativeReads=0.904,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:24,0:25,0:49:.:.","0/1:88.83:43,30:0.411:21,19:22,11:73:22,21,19,...",ALK,135,0.0
31,2,29705282,.,A,ATATATATATATATATAT,.,PASS,DP=81;MQ=120.41;FractionInformativeReads=0.852,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:24,0:22,0:46:.:.","0/1:43.22:17,6:0.261:8,4:9,2:23:12,5,4,2:13,4,6,0",ALK,81,0.0
32,2,29825713,.,GT,G,.,PASS,DP=119;MQ=180.17;FractionInformativeReads=0.924,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,1:0.020:27,1:22,0:50:.:.","0/1:89.84:31,29:0.483:13,13:18,16:60:17,14,10,...",ALK,119,2.0
33,2,39096885,.,CA,C,.,PASS,DP=120;MQ=145.46;FractionInformativeReads=0.858,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,2:0.051:19,2:18,0:39:.:.","0/1:70.34:30,34:0.531:13,10:17,24:64:15,15,18,...",SOS1,120,5.1
34,2,208248389,.,G,A,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.004,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.06:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",IDH1,116,6.0
35,2,211677577,.,TA,T,.,PASS,DP=97;MQ=139.68;FractionInformativeReads=0.866,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,0:0.000:20,0:17,0:37:.:.","0/1:144.11:1,46:0.979:0,20:1,26:47:1,0,25,21:0...",ERBB4,97,0.0
36,2,212322431,.,TA,T,.,PASS,DP=137;MQ=186.20;FractionInformativeReads=0.956,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:31,0:28,0:59:.:.","0/1:120.93:38,34:0.472:27,15:11,19:72:15,23,11...",ERBB4,137,0.0
37,2,212538253,.,A,T,.,PASS,DP=127;MQ=192.56;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:50,0:0.000:21,0:29,0:50:.:.","0/1:184.81:0,76:1.000:0,40:0,36:76:0,0,38,38:0...",ERBB4,127,0.0
38,2,233772291,.,G,T,.,PASS,DP=124;MQ=194.40;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:19,0:30,0:49:.:.","0/1:181.80:0,75:1.000:0,36:0,39:75:0,0,45,30:0...",UGT1A1,124,0.0
39,3,52406255,.,G,A,.,PASS,DP=120;MQ=193.65;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:48,0:0.000:15,0:33,0:48:.:.","0/1:179.21:0,72:1.000:0,37:0,35:72:0,0,40,32:0...",BAP1,120,0.0
40,3,53600934,.,C,G,.,PASS,DP=136;MQ=190.54;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:31,0:26,0:57:.:.","0/1:205.88:0,79:1.000:0,42:0,37:79:0,0,33,46:0...",CACNA1D,136,0.0
41,3,69848060,.,T,C,.,PASS,DP=107;MQ=164.67;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:32,0:24,0:56:.:.","0/1:58.68:38,13:0.255:23,8:15,5:51:22,16,12,1:...",MITF,107,0.0
42,3,169238554,.,CA,C,.,PASS,DP=153;MQ=190.79;FractionInformativeReads=0.941,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:60,0:0.000:26,0:34,0:60:.:.","0/1:216.39:0,84:1.000:0,47:0,37:84:0,0,44,40:0...",MECOM,153,0.0
43,3,169382849,.,C,CA,.,PASS,DP=118;MQ=162.14;FractionInformativeReads=0.814,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,4:0.111:14,3:18,1:36:.:.","0/1:87.17:4,56:0.933:3,29:1,27:60:2,2,23,33:1,...",MECOM,118,11.1
44,3,169451252,.,GA,G,.,PASS,DP=154;MQ=197.89;FractionInformativeReads=0.870,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:44,4:0.083:18,3:26,1:48:.:.","0/1:106.99:1,85:0.988:0,43:1,42:86:1,0,39,46:0...",MECOM,154,8.3
45,3,169606408,.,C,CA,.,PASS,DP=116;MQ=151.91;FractionInformativeReads=0.793,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,3:0.075:23,2:14,1:40:.:.","0/1:109.36:7,45:0.865:4,24:3,21:52:6,1,17,28:3...",MECOM,116,7.5
46,3,179175710,.,AT,A,.,PASS,DP=121;MQ=193.25;FractionInformativeReads=0.826,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.000:22,0:18,0:40:.:.","0/1:90.18:30,30:0.500:19,19:11,11:60:15,15,16,...",PIK3CA,121,0.0
47,3,179218304,.,A,G,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.001,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.07:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",PIK3CA,116,7.0
48,3,181714163,.,A,T,.,PASS,DP=129;MQ=170.18;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:55,0:0.000:29,0:26,0:55:.:.","0/1:119.37:38,35:0.479:22,19:16,16:73:26,12,14...",SOX2,129,0.0
49,4,152369596,.,G,GA,.,PASS,DP=148;MQ=183.68;FractionInformativeReads=0.905,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:59,0:0.000:35,0:24,0:59:.:.","0/1:213.50:0,75:1.000:0,37:0,38:75:0,0,36,39:0...",FBXW7,148,0.0
50,5,31463883,.,G,A,.,PASS,DP=167;MQ=209.94;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:20,0:29,0:49:.:.","0/1:75.40:82,36:0.305:46,20:36,16:118:40,42,13...",DROSHA,167,0.0
51,5,80733107,.,A,G,.,PASS,DP=138;MQ=194.95;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:53,0:0.000:22,0:31,0:53:.:.","0/1:193.71:0,85:1.000:0,36:0,49:85:0,0,40,45:0...",MSH3,138,0.0
52,5,132605268,.,C,T,.,PASS,DP=117;MQ=167.14;FractionInformativeReads=0.991,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:23,0:26,0:49:.:.","0/1:90.35:40,27:0.403:21,18:19,9:67:20,20,9,18...",RAD50,117,0.0
53,6,151891819,.,CA,C,.,PASS,DP=117;MQ=178.91;FractionInformativeReads=0.966,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:-0.00:56,0:0.000:26,0:30,0:56:.:.:151891819","0|1:200.45:0,57:1.000:0,29:0,28:57:0,0,31,26:0...",ESR1,117,0.0
54,6,151891824,.,A,T,.,PASS,DP=115;MQ=175.89;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:-0.00:58,0:0.000:27,0:31,0:58:.:.:151891819","0|1:204.89:0,57:1.000:0,29:0,28:57:0,0,31,26:0...",ESR1,115,0.0
55,6,151913052,.,G,A,.,PASS,DP=127;MQ=124.62;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:25,0:24,0:49:.:.","0/1:182.25:0,78:1.000:0,42:0,36:78:0,0,29,49:0...",ESR1,127,0.0
56,6,157187897,.,G,A,.,PASS,DP=132;MQ=180.38;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:63,0:0.000:23,0:40,0:63:.:.","0/1:141.82:33,36:0.522:16,15:17,21:69:17,16,19...",ARID1B,132,0.0
57,7,55053312,.,GGTGCATCTCTA,G,.,PASS,DP=196;MQ=214.29;FractionInformativeReads=0.980,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:24,0:25,0:49:.:.","0/1:53.55:113,30:0.210:63,19:50,11:143:49,64,1...",EGFR,196,0.0
58,7,55086578,.,C,G,.,PASS,DP=195;MQ=209.55;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:57,1:0.017:29,1:28,0:58:.:.","0/1:114.73:72,65:0.474:31,34:41,31:137:33,39,4...",EGFR,195,1.7
59,7,55106841,.,C,G,.,PASS,DP=224;MQ=214.87;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:58,0:0.000:33,0:25,0:58:.:.","0/1:61.17:132,34:0.205:58,15:74,19:166:66,66,1...",EGFR,224,0.0
60,7,55195555,.,C,T,.,PASS,DP=212;MQ=159.83;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:30,0:26,0:56:.:.","0/1:72.41:116,40:0.256:56,20:60,20:156:60,56,1...",EGFR,212,0.0
61,7,148710746,.,C,G,.,PASS,DP=167;MQ=192.49;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:26,0:21,0:47:.:.","0/1:53.26:94,26:0.217:45,16:49,10:120:44,50,13...",CUL1,167,0.0
62,7,151484856,.,C,T,.,PASS,DP=138;MQ=186.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:29,0:30,0:59:.:.","0/1:134.93:39,40:0.506:20,25:19,15:79:13,26,28...",RHEB,138,0.0
63,8,38432410,.,AT,A,.,PASS,DP=109;MQ=178.19;FractionInformativeReads=0.679,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:19,1:0.050:12,1:7,0:20:.:.","0/1:21.00:34,20:0.370:20,12:14,8:54:17,17,6,14...",FGFR1,109,5.0
64,8,51384860,.,A,C,.,PASS,DP=166;MQ=210.08;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:48,0:0.000:26,0:22,0:48:.:.","0/1:70.38:84,34:0.288:41,14:43,20:118:43,41,18...",PXDNL,166,0.0
65,8,51555485,.,A,AT,.,PASS,DP=156;MQ=214.26;FractionInformativeReads=0.929,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:35,0:0.000:14,0:21,0:35:.:.","0/1:68.86:70,40:0.364:32,17:38,23:110:35,35,25...",PXDNL,156,0.0
66,8,51576198,.,CA,C,.,PASS,DP=152;MQ=189.54;FractionInformativeReads=0.803,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,2:0.048:24,1:16,1:42:.:.","0/1:55.47:50,30:0.375:23,13:27,17:80:22,28,17,...",PXDNL,152,4.8
67,8,51724953,.,C,T,.,PASS,DP=126;MQ=203.20;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:38,0:0.000:22,0:16,0:38:.:.","0/1:73.05:55,32:0.368:28,12:27,20:87:25,30,13,...",PXDNL,126,0.0
68,8,92007467,.,TA,T,.,PASS,DP=136;MQ=194.90;FractionInformativeReads=0.809,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:39,0:0.000:20,0:19,0:39:.:.","0/1:129.11:19,52:0.732:10,22:9,30:71:8,11,28,2...",RUNX1T1,136,0.0
69,8,138145239,.,C,T,.,PASS,DP=151;MQ=188.96;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:53,0:0.000:30,0:23,0:53:.:.","0/1:95.91:61,37:0.378:33,20:28,17:98:38,23,21,...",FAM135B,151,0.0
70,8,138217522,.,C,A,.,PASS,DP=129;MQ=100.63;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,0:0.000:18,0:18,0:36:.:.","0/1:54.27:67,26:0.280:34,14:33,12:93:31,36,11,...",FAM135B,129,0.0
71,8,138227244,.,C,A,.,PASS,DP=169;MQ=206.34;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,1:0.019:27,1:25,0:53:.:.","0/1:31.33:104,12:0.103:58,5:46,7:116:42,62,6,6...",FAM135B,169,1.9
72,8,138298823,.,G,A,.,PASS,DP=159;MQ=175.51;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,0:0.000:23,0:22,0:45:.:.","0/1:81.09:74,40:0.351:37,22:37,18:114:42,32,20...",FAM135B,159,0.0
73,8,138353484,.,C,T,.,PASS,DP=136;MQ=194.12;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:54,0:0.000:27,0:27,0:54:.:.","0/1:81.96:55,27:0.329:29,20:26,7:82:28,27,11,1...",FAM135B,136,0.0
74,8,138357002,.,C,T,.,PASS,DP=146;MQ=200.60;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:27,0:25,0:52:.:.","0/1:87.25:61,33:0.351:29,12:32,21:94:28,33,16,...",FAM135B,146,0.0
75,8,138387843,.,C,G,.,PASS,DP=155;MQ=203.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:32,0:20,0:52:.:.","0/1:23.61:98,5:0.049:54,3:44,2:103:59,39,4,1:4...",FAM135B,155,0.0
76,8,138410083,.,A,C,.,PASS,DP=139;MQ=202.11;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:48,0:0.000:25,0:23,0:48:.:.","0/1:84.37:58,33:0.363:31,17:27,16:91:34,24,16,...",FAM135B,139,0.0
77,9,8327022,.,C,G,.,PASS,DP=66;MQ=19.59;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,2:0.042:17,1:29,1:48:.:.","0/1:98.53:0,18:1.000:0,9:0,9:18:0,0,7,11:0,0,12,6",PTPRD,66,4.2
78,9,8373832,.,GTA,G,.,PASS,DP=134;MQ=148.72;FractionInformativeReads=0.612,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:20,5:12,3:40:.:.:8373828","0|1:59.38:3,39:0.929:2,23:1,16:42:1,2,18,21:2,...",PTPRD,134,20.0
79,9,8373850,.,GTA,G,.,PASS,DP=123;MQ=127.34;FractionInformativeReads=0.659,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:19,5:13,3:40:.:.:8373828","0|1:53.99:3,38:0.927:2,23:1,15:41:1,2,18,20:2,...",PTPRD,123,20.0
80,9,8373854,.,G,C,.,PASS,DP=121;MQ=125.46;FractionInformativeReads=0.669,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:19,5:13,3:40:.:.:8373828","0|1:53.33:3,38:0.927:2,23:1,15:41:1,2,18,20:2,...",PTPRD,121,20.0
81,9,8772136,.,A,C,.,PASS,DP=167;MQ=195.04;FractionInformativeReads=0.898,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:29,0:28,0:57:.:.","0/1:171.16:33,60:0.645:19,33:14,27:93:18,15,41...",PTPRD,167,0.0
82,9,8775421,.,C,G,.,PASS,DP=149;MQ=201.33;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:32,0:20,0:52:.:.","0/1:106.60:56,41:0.423:32,19:24,22:97:20,36,17...",PTPRD,149,0.0
83,9,9030415,.,G,A,.,PASS,DP=113;MQ=211.66;FractionInformativeReads=0.991,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,0:0.000:15,0:17,0:32:.:.","0/1:131.08:0,80:1.000:0,44:0,36:80:0,0,40,40:0...",PTPRD,113,0.0
84,9,9238315,.,G,T,.,PASS,DP=172;MQ=216.51;FractionInformativeReads=0.994,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:20,0:22,0:42:.:.","0/1:73.99:86,43:0.333:47,25:39,18:129:37,49,22...",PTPRD,172,0.0
85,9,9352355,.,A,G,.,PASS,DP=133;MQ=127.89;FractionInformativeReads=0.947,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:43,0:0.000:24,0:19,0:43:.:.","0/1:163.53:1,82:0.988:1,38:0,44:83:1,0,28,54:1...",PTPRD,133,0.0
86,9,9447430,.,G,A,.,PASS,DP=157;MQ=187.29;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:39,0:0.000:18,0:21,0:39:.:.","0/1:151.70:0,118:1.000:0,54:0,64:118:0,0,52,66...",PTPRD,157,0.0
87,9,9783317,.,T,C,.,PASS,DP=178;MQ=217.72;FractionInformativeReads=0.989,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:43,0:0.000:27,0:16,0:43:.:.","0/1:115.74:57,76:0.571:30,39:27,37:133:32,25,4...",PTPRD,178,0.0
88,9,9819907,.,T,A,.,PASS,DP=187;MQ=197.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:63,0:0.000:36,0:27,0:63:.:.","0/1:223.95:0,124:1.000:0,53:0,71:124:0,0,71,53...",PTPRD,187,0.0
89,9,9984858,.,T,A,.,PASS,DP=126;MQ=210.02;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:37,0:0.000:17,0:20,0:37:.:.:9984858","0|1:141.67:0,89:1.000:0,45:0,44:89:0,0,42,47:0...",PTPRD,126,0.0
90,9,9984859,.,C,T,.,PASS,DP=127;MQ=210.36;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:37,0:0.000:17,0:20,0:37:.:.:9984858","0|1:141.67:0,90:1.000:0,46:0,44:90:0,0,42,48:0...",PTPRD,127,0.0
91,9,10203169,.,CT,C,.,PASS,DP=118;MQ=187.77;FractionInformativeReads=0.831,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,1:0.030:18,1:14,0:33:.:.","0/1:114.07:5,60:0.923:2,31:3,29:65:3,2,24,36:4...",PTPRD,118,3.0
92,9,10394957,.,C,CTTTTTTTTTTTTTT,.,PASS,DP=128;MQ=174.88;FractionInformativeReads=0.719,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:29,2:0.065:13,1:16,1:31:.:.","0/1:40.26:39,22:0.361:19,9:20,13:61:18,21,5,17...",PTPRD,128,6.5

In [16]:
import os

def SIFT_indel(data_frame, TEMP_FOLDER_PATH, USER_INPUT_FOLDER_PATH, input_filename, SIFT_INDEL_INSTALL_PATH, SIFT_INDEL_DB_PATH):
    """
    This function processes indel (insertion-deletion) mutations from a DataFrame,
    formats them for the SIFT Indel tool, and executes the SIFT Indel command.
    
    Args:
    - data_frame: pandas DataFrame containing VCF data
    - TEMP_FOLDER_PATH: str, path to temporary folder
    - USER_INPUT_FOLDER_PATH: str, path to user input folder
    - input_filename: str, name of the input file
    - SIFT_INDEL_INSTALL_PATH: str, path to SIFT Indel installation
    - SIFT_INDEL_DB_PATH: str, path to SIFT Indel database
    """
    
    # Extract relevant columns from the data frame
    ref = list(data_frame['REF'])
    alt = list(data_frame['ALT'])
    pos = list(data_frame['POS'])
    chrom = list(data_frame['#CHROM'])
    
    # Initialize lists for storing indel positions and sequences
    indel_list_pos = []
    indel_list_chrom = []
    indel_list_ref = []
    indel_list_alt = []

    # Identify indels (differences in length between ref and alt, with no commas in alt)
    for i in range(len(ref)):
        if len(ref[i]) != len(alt[i]) and ',' not in alt[i]:
            indel_list_pos.append(pos[i])
            indel_list_chrom.append(chrom[i])
            indel_list_ref.append(ref[i])
            indel_list_alt.append(alt[i])

    # Separate indels into insertions and deletions
    insertion_list_pos = []
    insertion_list_ref = []
    insertion_list_alt = []
    insertion_list_chrom = []

    deletion_list_chrom = []
    deletion_list_pos = []
    deletion_list_ref = []
    deletion_list_alt = []

    for i in range(len(indel_list_ref)):
        if len(indel_list_ref[i]) < len(indel_list_alt[i]):
            insertion_list_chrom.append(indel_list_chrom[i])
            insertion_list_pos.append(indel_list_pos[i])
            insertion_list_ref.append(indel_list_ref[i])
            insertion_list_alt.append(indel_list_alt[i])
        else:
            deletion_list_chrom.append(indel_list_chrom[i])
            deletion_list_pos.append(indel_list_pos[i])
            deletion_list_ref.append(indel_list_ref[i])
            deletion_list_alt.append(indel_list_alt[i])

    # Helper function to split a word into a list of characters
    def split(word):
        return [char for char in word]

    # Format deletions for SIFT Indel
    sift_format_deletion = []
    for i in range(len(deletion_list_ref)):
        sub = len(deletion_list_ref[i]) - len(deletion_list_alt[i])
        del_ref = split(deletion_list_ref[i])
        del_alt = split(deletion_list_alt[i])
        for j in range(len(del_alt)):
            del_ref.remove(del_alt[j])

        pos2 = deletion_list_pos[i] + sub
        sift_format_deletion.append(deletion_list_chrom[i] + ',' + str(deletion_list_pos[i]) + ',' + str(pos2) + ',' + '1' + ',' + '/')

    # Format insertions for SIFT Indel
    inserts = []
    sift_format_insertion = []

    for i in range(len(insertion_list_alt)):
        ins_strings = ''
        sub = len(insertion_list_alt[i]) - len(insertion_list_ref[i])
        ins_ref = split(insertion_list_ref[i])
        ins_alt = split(insertion_list_alt[i])
        for j in range(len(ins_ref)):
            ins_alt.remove(ins_ref[j])
        for k in range(len(ins_alt)):
            ins_strings += ins_alt[k]

        sift_format_insertion.append(insertion_list_chrom[i] + ',' + str(insertion_list_pos[i]) + ',' + str(insertion_list_pos[i]) + ',' + '1' + ',' + ins_strings)

    # Combine formatted insertions and deletions
    final_list = sift_format_insertion + sift_format_deletion

    # Write the formatted indels to a file for SIFT Indel processing
    sift_input_file = TEMP_FOLDER_PATH + "indel_file_" + input_filename + ".txt"
    with open(sift_input_file, "w") as textfile:
        for element in final_list:
            textfile.write(element + "\n")
    
    # Define output file paths for the SIFT Indel process
    sift_process_output = USER_INPUT_FOLDER_PATH + input_filename + "_sift_indel_process_out.txt"
    sift_prediction_file = USER_INPUT_FOLDER_PATH + 'SIFT_indel_' + input_filename + '.tsv'
    SIFTIndel_out = USER_INPUT_FOLDER_PATH + input_filename + '_SIFTIndel_out.txt'
    SIFTIndel_err = USER_INPUT_FOLDER_PATH + input_filename + '_SIFTIndel_err.txt'

    # Construct the command to run the SIFT Indel tool
    command = f'nohup sh SIFT_indel.sh {SIFT_INDEL_INSTALL_PATH} {sift_input_file} {SIFT_INDEL_DB_PATH} {TEMP_FOLDER_PATH} {sift_process_output} {sift_prediction_file} {USER_INPUT_FOLDER_PATH} > {SIFTIndel_out} 2> {SIFTIndel_err} &'
    
    # Execute the command
    os.system(command)
        

'''
def SIFT_indel(input_file):
    # data_frame=read_vcf(USER_INPUT_FOLDER_PATH+input_file)
    data_frame=input_file
    ref=list(data_frame['REF'])
    alt=list(data_frame['ALT'])
    pos=list(data_frame['POS'])
    chrom=list(data_frame['#CHROM'])

    indel_list_pos=[]
    indel_list_chrom=[]
    indel_list_ref=[]
    indel_list_alt=[]

    for i in range(len(ref)):
        if len(ref[i])!=len(alt[i])and ','not in alt[i]:
            indel_list_pos.append(pos[i])
            indel_list_chrom.append(chrom[i])
            indel_list_ref.append(ref[i])
            indel_list_alt.append(alt[i])

    insertion_list_pos=[]
    insertion_list_ref=[]
    insertion_list_alt=[]
    insertion_list_chrom=[]

    deletion_list_chrom=[]
    deletion_list_pos=[]
    deletion_list_ref=[]
    deletion_list_alt=[]

    for i in range(len(indel_list_ref)):
        if len(indel_list_ref[i])< len(indel_list_alt[i]):
            insertion_list_chrom.append(indel_list_chrom[i])
            insertion_list_pos.append(indel_list_pos[i])
            insertion_list_ref.append(indel_list_ref[i])
            insertion_list_alt.append(indel_list_alt[i])
        else:
            deletion_list_chrom.append(indel_list_chrom[i])
            deletion_list_pos.append(indel_list_pos[i])
            deletion_list_alt.append(indel_list_alt[i])
            deletion_list_ref.append(indel_list_ref[i])

    def split(word):
        return [char for char in word]

    sift_format_deletion=[]
    for i in range(len(deletion_list_ref)):
        sub=len(deletion_list_ref[i])-len(deletion_list_alt[i])
        del_ref=split(deletion_list_ref[i])
        del_alt=split(deletion_list_alt[i])
        for j in range(len(del_alt)):
            del_ref.remove(del_alt[j])

        pos2=deletion_list_pos[i]+sub
        sift_format_deletion.append(deletion_list_chrom[i]+','+str(deletion_list_pos[i])+','+str(pos2)+','+'1'+','+'/')

    inserts=[]
    sift_format_insertion=[]

    for i in range(len(insertion_list_alt)):
        ins_strings=''
        sub=len(insertion_list_alt[i])-len(insertion_list_ref[i])
        ins_ref=split(insertion_list_ref[i])
        ins_alt=split(insertion_list_alt[i])
        for j in range(len(ins_ref)):
            ins_alt.remove(ins_ref[j])
        for k in range(len(ins_alt)):
            ins_strings=ins_strings+ins_alt[k]
        
        sift_format_insertion.append(insertion_list_chrom[i]+','+str(insertion_list_pos[i])+','+str(insertion_list_pos[i])+','+'1'+','+ins_strings)

    final_list=sift_format_insertion+sift_format_deletion

    #input file prepared for SIFT Indel process
    sift_input_file = TEMP_FOLDER_PATH+"indel_file_"+ input_filename +".txt" 
    textfile = open(sift_input_file, "w")
    for element in final_list:
        textfile.write(element + "\n")
    textfile.close()
    
    #path="indel_file"+file+".txt"
    sift_process_output=USER_INPUT_FOLDER_PATH+input_filename+"_sift_indel_process_out.txt"
    sift_prediction_file=USER_INPUT_FOLDER_PATH+'SIFT_indel'+'_'+input_filename+'.tsv'
    SIFTIndel_out = USER_INPUT_FOLDER_PATH+input_filename+'_SIFTIndel_out.txt'
    SIFTIndel_err = USER_INPUT_FOLDER_PATH+input_filename+'_SIFTIndel_err.txt'
    
    command='nohup sh SIFT_indel.sh '+SIFT_INDEL_INSTALL_PATH +' '+sift_input_file+' '+SIFT_INDEL_DB_PATH +' '+TEMP_FOLDER_PATH +' '+ sift_process_output + ' ' + sift_prediction_file +' '+USER_INPUT_FOLDER_PATH+' >'+SIFTIndel_out + ' 2>'+SIFTIndel_err +' &'
    #print("Command :",command)
    r1=os.system(command)
'''

'\ndef SIFT_indel(input_file):\n    # data_frame=read_vcf(USER_INPUT_FOLDER_PATH+input_file)\n    data_frame=input_file\n    ref=list(data_frame[\'REF\'])\n    alt=list(data_frame[\'ALT\'])\n    pos=list(data_frame[\'POS\'])\n    chrom=list(data_frame[\'#CHROM\'])\n\n    indel_list_pos=[]\n    indel_list_chrom=[]\n    indel_list_ref=[]\n    indel_list_alt=[]\n\n    for i in range(len(ref)):\n        if len(ref[i])!=len(alt[i])and \',\'not in alt[i]:\n            indel_list_pos.append(pos[i])\n            indel_list_chrom.append(chrom[i])\n            indel_list_ref.append(ref[i])\n            indel_list_alt.append(alt[i])\n\n    insertion_list_pos=[]\n    insertion_list_ref=[]\n    insertion_list_alt=[]\n    insertion_list_chrom=[]\n\n    deletion_list_chrom=[]\n    deletion_list_pos=[]\n    deletion_list_ref=[]\n    deletion_list_alt=[]\n\n    for i in range(len(indel_list_ref)):\n        if len(indel_list_ref[i])< len(indel_list_alt[i]):\n            insertion_list_chrom.append(indel_list_chrom[i])\n            insertion_list_pos.append(indel_list_pos[i])\n            insertion_list_ref.append(indel_list_ref[i])\n            insertion_list_alt.append(indel_list_alt[i])\n        else:\n            deletion_list_chrom.append(indel_list_chrom[i])\n            deletion_list_pos.append(indel_list_pos[i])\n            deletion_list_alt.append(indel_list_alt[i])\n            deletion_list_ref.append(indel_list_ref[i])\n\n    def split(word):\n        return [char for char in word]\n\n    sift_format_deletion=[]\n    for i in range(len(deletion_list_ref)):\n        sub=len(deletion_list_ref[i])-len(deletion_list_alt[i])\n        del_ref=split(deletion_list_ref[i])\n        del_alt=split(deletion_list_alt[i])\n        for j in range(len(del_alt)):\n            del_ref.remove(del_alt[j])\n\n        pos2=deletion_list_pos[i]+sub\n        sift_format_deletion.append(deletion_list_chrom[i]+\',\'+str(deletion_list_pos[i])+\',\'+str(pos2)+\',\'+\'1\'+\',\'+\'/\')\n\n    inserts=[]\n    sift_format_insertion=[]\n\n    for i in range(len(insertion_list_alt)):\n        ins_strings=\'\'\n        sub=len(insertion_list_alt[i])-len(insertion_list_ref[i])\n        ins_ref=split(insertion_list_ref[i])\n        ins_alt=split(insertion_list_alt[i])\n        for j in range(len(ins_ref)):\n            ins_alt.remove(ins_ref[j])\n        for k in range(len(ins_alt)):\n            ins_strings=ins_strings+ins_alt[k]\n        \n        sift_format_insertion.append(insertion_list_chrom[i]+\',\'+str(insertion_list_pos[i])+\',\'+str(insertion_list_pos[i])+\',\'+\'1\'+\',\'+ins_strings)\n\n    final_list=sift_format_insertion+sift_format_deletion\n\n    #input file prepared for SIFT Indel process\n    sift_input_file = TEMP_FOLDER_PATH+"indel_file_"+ input_filename +".txt" \n    textfile = open(sift_input_file, "w")\n    for element in final_list:\n        textfile.write(element + "\n")\n    textfile.close()\n    \n    #path="indel_file"+file+".txt"\n    sift_process_output=USER_INPUT_FOLDER_PATH+input_filename+"_sift_indel_process_out.txt"\n    sift_prediction_file=USER_INPUT_FOLDER_PATH+\'SIFT_indel\'+\'_\'+input_filename+\'.tsv\'\n    SIFTIndel_out = USER_INPUT_FOLDER_PATH+input_filename+\'_SIFTIndel_out.txt\'\n    SIFTIndel_err = USER_INPUT_FOLDER_PATH+input_filename+\'_SIFTIndel_err.txt\'\n    \n    command=\'nohup sh SIFT_indel.sh \'+SIFT_INDEL_INSTALL_PATH +\' \'+sift_input_file+\' \'+SIFT_INDEL_DB_PATH +\' \'+TEMP_FOLDER_PATH +\' \'+ sift_process_output + \' \' + sift_prediction_file +\' \'+USER_INPUT_FOLDER_PATH+\' >\'+SIFTIndel_out + \' 2>\'+SIFTIndel_err +\' &\'\n    #print("Command :",command)\n    r1=os.system(command)\n'

In [24]:
# def SIFT_indel(inp_df):
#     #print(data_frame)
#     chrom = list(inp_df['#CHROM'].astype(str))
#     pos = list(inp_df['POS'].astype(str))
#     ref = list(inp_df['REF'].astype(str))
#     alt = list(inp_df['ALT'].astype(str))

#     indel_list_pos = []
#     indel_list_chrom = []
#     indel_list_ref = []
#     indel_list_alt = []
    
#     for i in range(len(ref)):
#         if len(ref[i])!=len(alt[i])and ','not in alt[i]:
#             indel_list_pos.append(pos[i])
#             indel_list_chrom.append(chrom[i])
#             indel_list_ref.append(ref[i])
#             indel_list_alt.append(alt[i])
#     #print('Indel list')
#     #print(indel_list_pos, indel_list_chrom, indel_list_ref, indel_list_alt)
        
#     insertion_list_pos=[]
#     insertion_list_ref=[]
#     insertion_list_alt=[]
#     insertion_list_chrom=[]

#     deletion_list_chrom=[]
#     deletion_list_pos=[]
#     deletion_list_ref=[]
#     deletion_list_alt=[]

#     for i in range(len(indel_list_ref)):
#         if len(indel_list_ref[i])< len(indel_list_alt[i]):
#             insertion_list_chrom.append(indel_list_chrom[i])
#             insertion_list_pos.append(indel_list_pos[i])
#             insertion_list_ref.append(indel_list_ref[i])
#             insertion_list_alt.append(indel_list_alt[i])
#         else:
#             deletion_list_chrom.append(indel_list_chrom[i])
#             deletion_list_pos.append(indel_list_pos[i])
#             deletion_list_alt.append(indel_list_alt[i])
#             deletion_list_ref.append(indel_list_ref[i])
#     #print('Insertion list')
#     #print(insertion_list_pos, insertion_list_ref, insertion_list_alt, insertion_list_chrom)
    
#     #print('Deletion list')
#     #print(deletion_list_chrom, deletion_list_pos, deletion_list_ref, deletion_list_alt)
#     def split(word):
#         return [char for char in word]
    
#     sift_format_deletion=[]
#     for i in range(len(deletion_list_ref)):
#         sub = str(len(deletion_list_ref[i]) - len(deletion_list_alt[i]))
#         #print(sub)
#         del_ref=split(deletion_list_ref[i])
#         del_alt=split(deletion_list_alt[i])
#         for j in range(len(del_alt)):
#             del_ref.remove(del_alt[j])

#         pos2=deletion_list_pos[i]+sub
#         sift_format_deletion.append(deletion_list_chrom[i]+','+str(deletion_list_pos[i])+','+str(pos2)+','+'1'+','+'/')
#     #print('SIFT deletion')
#     #print(sift_format_deletion)
    
#     inserts=[]
#     sift_format_insertion=[]
#     for i in range(len(insertion_list_alt)):
#         ins_strings=''
#         sub=len(insertion_list_alt[i])-len(insertion_list_ref[i])
#         ins_ref=split(insertion_list_ref[i])
#         ins_alt=split(insertion_list_alt[i])
#         for j in range(len(ins_ref)):
#             ins_alt.remove(ins_ref[j])
#         for k in range(len(ins_alt)):
#             ins_strings=ins_strings+ins_alt[k]
        
#         sift_format_insertion.append(insertion_list_chrom[i]+','+str(insertion_list_pos[i])+','+str(insertion_list_pos[i])+','+'1'+','+ins_strings)
#     #print('SIFT Insertion')
#     #print(sift_format_insertion)
    
#     final_list=sift_format_insertion+sift_format_deletion
#     sift_input_file = TEMP_FOLDER_PATH + "indel_file_" + input_filename + ".txt"
#     textfile = open(sift_input_file, "w")
#     for element in final_list:
#         textfile.write(element + "\n")
#     textfile.close()
#     sift_process_output = USER_INPUT_FOLDER_PATH + input_filename + "_sift_indel_process_out.txt"
#     sift_prediction_file = os.path.join(USER_INPUT_FOLDER_PATH, 'SIFT_indel' + '_' + input_filename + '.tsv')
#     SIFTIndel_out = USER_INPUT_FOLDER_PATH + input_filename + '_SIFTIndel_out.txt'
#     SIFTIndel_err = USER_INPUT_FOLDER_PATH + input_filename + '_SIFTIndel_err.txt'
#     #print(sift_prediction_file)
#     command='nohup sh SIFT_indel.sh '+SIFT_INDEL_INSTALL_PATH +' '+sift_input_file+' '+SIFT_INDEL_DB_PATH +' '+TEMP_FOLDER_PATH +' '+ sift_process_output + ' ' + sift_prediction_file +' '+USER_INPUT_FOLDER_PATH+' >'+SIFTIndel_out + ' 2>'+SIFTIndel_err +' &'
#     #print("Command :",command)
#     r1=os.system(command)

def SIFT4G_1(inp_df):
    #print('inside SIFT 4G')
    print(inp_df)
    SIFT4G_out = USER_INPUT_FOLDER_PATH+input_filename+'_SIFT4G_out.txt'
    SIFT4G_err = USER_INPUT_FOLDER_PATH+input_filename+'_SIFT4G_err.txt'
    SIFT4G_annotation_file = os.path.join(TEMP_FOLDER_PATH+input_filename+'_SIFTannotations.xls')
    #print(SIFT4G_annotation_file)
    SIFT4G='nohup sh SIFT_4G.sh '+SIFT_4G_INSTALL_PATH +' '+USER_INPUT_FOLDER_PATH+' '+ output_file_name +' '+TEMP_FOLDER_PATH+' '+SIFT4G_annotation_file+' >'+SIFT4G_out + ' 2>'+SIFT4G_err +' &'
    r=os.system(SIFT4G)
 
def dbNSFP_1(inp_df):
    dbnsfp_out = USER_INPUT_FOLDER_PATH+input_filename+'_dbNSFP_out.txt'
    dbnsfp_err = USER_INPUT_FOLDER_PATH+input_filename+'_dbNSFP_err.txt'
    db='nohup sh dbNSFP.sh '+dbNSFP_PATH +' '+USER_INPUT_FOLDER_PATH+ output_file_name+' >'+dbnsfp_out + ' 2>'+dbnsfp_err +' &'
    #print(db)
    result=os.system(db)

def fetch_data_from_cadd(url):
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch data from {url}")
        return None
    
def CADD_SNV(inp_df):
    output_data = []
    for index, row in inp_df.iterrows():
        chrom = row['#CHROM']
        pos = row['POS']
        alt = row['ALT']
        ref = row['REF']
        url = f'https://cadd.gs.washington.edu/api/v1.0/GRCh38-v1.7_inclAnno/{chrom}:{pos}_{ref}_{alt}'
        #print(f'Processing: {url}')
        response_data = fetch_data_from_cadd(url)
        if response_data:
            for item in response_data:
                item['Chrom'] = chrom
                item['Position'] = pos
                item['Ref'] = ref
                item['Alt'] = alt
            output_data.extend(response_data)
    return output_data

def clinvar_extraction(input_df,gref):
    #making a copy of the input file dataframe to add the intermediate processes columns
    input_df_copy=input_df.copy()
    dictionary_df=pd.DataFrame(columns=["Locus:ref:alt"])

    for index, row in input_df_copy.iterrows():
        output_df=pd.DataFrame()
        chr_no = row['#CHROM']
        chr_pos = row['POS']
        #coding = row["coding"]
        ref = row['REF']
        alt = row['ALT']
        check=f"{chr_no}:{chr_pos}:{ref}:{alt}"
        #print (check)
        #print(list(dictionary_df["Locus:ref:alt"]))
        if check in list(dictionary_df["Locus:ref:alt"]):
            #print("using cached data")
            cached_row = dictionary_df[dictionary_df["Locus:ref:alt"] == check].iloc[0]
            # Update input_df with cached data
            input_df.loc[index, 'Gene'] = cached_row['Gene']
            input_df.loc[index, 'Clinvar_accession_no'] = cached_row['Clinvar_accession_no']
            input_df.loc[index, 'Clinvar_Protein_change'] = cached_row['ClinVar_Protein_change']
            input_df.loc[index, 'gnomAD_value'] = cached_row['gnomAD_value']
            input_df.loc[index, '1000_Genomes_value'] = cached_row['1000_Genomes_value']
            input_df.loc[index, 'ExAC_value'] = cached_row['ExAC_value']
            input_df.loc[index, 'dbSNP_id'] = cached_row['dbSNP_id']
            input_df.loc[index, 'OMIM_id'] = cached_row['OMIM_id']
            input_df.loc[index, 'Germline_classification'] = cached_row['Germline_classification']
            input_df.loc[index, 'Somatic_clinical_impact'] = cached_row['Somatic_clinical_impact']
            input_df.loc[index, 'Clinvar_link'] = cached_row['Clinvar_link']
        else:
            if len(ref)==len(alt)==1:
                output_df=clinvar_ref_alt_input(chr_no,chr_pos,ref,alt,gref)
                output_df.loc[0,"Locus:ref:alt"]= f"{chr_no}:{chr_pos}:{ref}:{alt}"
                dictionary_df=pd.concat([dictionary_df, output_df], axis=0)
                #display(dictionary_df)
            else:
                ref=ref.strip()
                alt=alt.strip()
                output_df= clinvar_ref_alt_input_indel(chr_no,chr_pos,ref,alt,gref)
                output_df.loc[0,"Locus:ref:alt"]= f"{chr_no}:{chr_pos}:{ref}:{alt}"
                dictionary_df=pd.concat([dictionary_df, output_df], axis=0)
            if not output_df.empty:
                #Adding the clinvar annotation columns to the original input file dataframe
                input_df.loc[index, 'Gene'] = output_df.loc[0,'Gene']
                input_df.loc[index, 'Clinvar_accession_no'] = output_df.loc[0,'Clinvar_accession_no']
                input_df.loc[index, 'Clinvar_Protein_change'] = output_df.loc[0,'ClinVar_Protein_change']
                input_df.loc[index, 'gnomAD_value'] = output_df.loc[0,'gnomAD_value']
                input_df.loc[index, '1000_Genomes_value'] = output_df.loc[0,'1000_Genomes_value']
                input_df.loc[index, 'ExAC_value'] = output_df.loc[0,'ExAC_value']
                input_df.loc[index, 'dbSNP_id'] = output_df.loc[0,'dbSNP_id']
                input_df.loc[index, 'OMIM_id'] = output_df.loc[0,'OMIM_id']
                input_df.loc[index, 'Germline_classification'] = output_df.loc[0,'Germline_classification']
                input_df.loc[index, 'Somatic_clinical_impact'] = output_df.loc[0,'Somatic_clinical_impact']
                input_df.loc[index, 'Clinvar_link'] = output_df.loc[0,'Clinvar_link']
    input_df['Clinvar_Protein_change']= input_df['Clinvar_Protein_change'].fillna("")
    return input_df

def dbsnp_extraction(input_df,gref):
    """ Function for extraction of dnsnp id and gnomad-genomes-global frequecy from the dbsnp database
    Args: input_df: the input dataframe with the chromosome no, chroomosome position,reference allele and alternate allele columns
    gref: reference genome "37" or "38"
    returns: the input dataframe with the dbSNP_Id and gnomAD-genomes columns added to it
    """
    #define the column names in the input dataframe
    chr_no = '#CHROM'
    chr_pos = 'POS'
    ref = 'REF'
    alt = 'ALT'
    vtype = "vtype"
    #process the columns required for constructing the input query for dbsnp and matching with the database
    input_df= input_dataframe_processing(input_df,ref,alt)
    display(input_df)
    #iterate through the rows of the input dataframe and fetch the dbsnp data
    for index, row in input_df.iterrows():
        chr_no_row = row[chr_no]
        chr_pos_row = row[chr_pos]
        ref_row = row[ref+"_dbsnp ref"]
        alt_row = row[alt+"_dbsnp alt"]
        vtype_row=row["vtype"]
        dbsnp_id,freq=dbsnp(chr_no_row,chr_pos_row,ref_row,alt_row,vtype_row,"38")#function call to extract from the database
        #populate input dataframe with the values
        input_df.at[index, "dbSNP_rs_id"] = dbsnp_id
        input_df.at[index, "gnomAD_value_dbSNP"] = freq
    #drop extra columns generated while processing 
    input_df = input_df.drop([vtype,ref+"_dbsnp ref",alt+"_dbsnp alt"], axis=1)
    # display(input_df)
    #return the output
    return input_df
    
    
# Example usage for processing a single VCF file
#inp_df = read_vcf(output_file_path)

In [25]:
def getCKBCoreData(input_df):
    gene_id_dict={}#dict for storing extracted ncbi_id
    ckb_dict={}#dict for storing extracted ckb core data
    gcolumn="Gene name_BED file"# Name of the column with gene names
    input_df[gcolumn]=input_df[gcolumn].fillna("") #fill empty rows in gene name column
    if gcolumn in input_df.columns:
        for i,row in input_df.iterrows():
            gname =row[gcolumn]
            print(gname)
            if gname is not "":
                if gname in gene_id_dict.keys(): # accessing stored ckb core data from previous parsing
                    ncbi_id=gene_id_dict[gname]
                    ckb_data=ckb_dict[gname]
                    print(f"Using cached data for {gname}")
                else:
                    ncbi_id = get_gene_id(gname) #calling the function to get gene id from NCBI
                    gene_id_dict[gname]=ncbi_id
                    if ncbi_id is not None:
                        ckb_data = getCKBGeneInfoForGeneID(ncbi_id) # calling funciton to fetch ckb core information
                        ckb_dict[gname]=ckb_data #storing the data in the dict
                    else:
                        ckb_dict[gname]={}  
                print(ncbi_id)
                print(ckb_data)
                #check if ncbi_id was extracted and populate input dataframe new columns
                if ncbi_id is not None:
                    input_df.loc[i, 'NCBI Gene ID'] = ncbi_id
                    #check if ckb core data is availiable
                    if len(ckb_data)!=0:
                        input_df.loc[i, 'CKB Core _Synonyms'] = ckb_data['Synonyms']
                        input_df.loc[i, 'CKB Core_GeneRole'] = ckb_data['Gene Role']
                        input_df.loc[i, 'CKB Core_Gene_Description'] = ckb_data['Gene Description']
                    else:
                        print(f"No data in CKB core for {gname}-{ncbi_id}")
                
    else:
        raise Exception("getCKBCoreData:'Gene name_BED file' column expected in input. Aborting....")
        
    return input_df

In [26]:
# %run "getGeneInfoFromGeneCardsAndNCBI.ipynb"
# def getCKBCoreData(input_df):
#     if 'Gene name_BED file' in input_df.columns:
#         for i,row in input_df.iterrows():
#             gname =row['Gene name_BED file']
#             gc_name,alias,ncbi_id = getGeneCardsData(gname)
#             input_df.loc[i, 'NCBI Gene ID'] = ncbi_id
#             ckb_data = getCKBGeneInfoForGeneID(ncbi_id)
#             display(ckb_data)
#             input_df.loc[i, 'CKB Core _Synonyms'] = ckb_data['Synonyms']
#             input_df.loc[i, 'CKB Core_GeneRole'] = ckb_data['Gene Role']
#             input_df.loc[i, 'CKB Core_Gene_Description'] = ckb_data['Gene Description']            
#     else:
#         raise Exception("getCKBCoreData:'Gene name_BED file' column expected in input. Aborting....")
        
#     return input_df    
'''
ckb_output = getCKBCoreData(inp_df)
if not ckb_output.empty:
    output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_CKBCore_output.xlsx')
    ckb_output.to_excel(output_files_path, index=False)
    print(f"CKB Core Output is saved to {output_files_path}")
'''

'\nckb_output = getCKBCoreData(inp_df)\nif not ckb_output.empty:\n    output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+\'_CKBCore_output.xlsx\')\n    ckb_output.to_excel(output_files_path, index=False)\n    print(f"CKB Core Output is saved to {output_files_path}")\n'

In [27]:
#annotations runs SIFT indel, SIFT4G and dbNSFP processes
def annotations(inp_df, input_filename):

    print('SIFT Indel annotations have begun for ', input_filename)
    SIFT_indel(inp_df)
    print('SIFT 4G annotations have begun for',input_filename)
    SIFT4G_1(inp_df)
    print('dbNSFP annotations have begun for',input_filename)
    dbNSFP_1(inp_df)

    #Clinvar data Extraction
    Clinvar_output=clinvar_extraction(inp_df, "38")
    if not Clinvar_output.empty:
        output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_clinvar_output.xlsx')
        Clinvar_output.to_excel(output_files_path, index=False)
        print(f"Clinvar Output is saved to {output_files_path}")

    #CADD Output
    cadd_data = CADD_SNV(inp_df)
    if cadd_data:
        df_cadd = pd.DataFrame(cadd_data)
        # Reordering columns to have 'Chrom', 'Position', 'Ref', and 'Alt' at the beginning
        df_cadd = df_cadd[['Chrom', 'Position', 'Ref', 'Alt'] + [col for col in df_cadd.columns if col not in ['Chrom', 'Position', 'Ref', 'Alt']]]
        output_files_path = os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_cadd_data.xlsx')
        df_cadd.to_excel(output_files_path, index=False)
        print(f"Cadd Output is saved to {output_files_path}")
    
    #OncoKB processing
    oncokb_output = oncokb_open_page(inp_df, '33ddcd81-d4ed-4ede-9f24-93d1dacd65df')
    if not oncokb_output.empty:
        output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_OncoKB_output.xlsx')
        oncokb_output.to_excel(output_files_path, index=False)
        print(f"OncoKB Output is saved to {output_files_path}")
    
    #CKB Core 
    ckb_output = getCKBCoreData(inp_df)
    if not ckb_output.empty:
        output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_CKBCore_output.xlsx')
        ckb_output.to_excel(output_files_path, index=False)
        print(f"CKB Core Output is saved to {output_files_path}")

    #dbSNP
    dbsnp_output = dbsnp_extraction(inp_df,"38")
    if not dbsnp_output.empty:
        output_files_path=os.path.join(USER_INPUT_FOLDER_PATH, input_filename+'_dbSNP_output.xlsx')
        dbsnp_output.to_excel(output_files_path, index=False)
        print(f"dbSNP Output is saved to {output_files_path}")
    

#staus checks whether or not the file annotations is complete
def status(input_filename):
    SIFT_indel_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+'SIFT_indel_'+input_filename+'.tsv')
    SIFT4G_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_SIFTannotations.xls')
    dbNSFP_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'.vcf_dbNSFP.tsv')
    df_cadd_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_cadd_data.xlsx')
    Clinvar_output_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_clinvar_output.xlsx')
    oncokb_output_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_OncoKB_output.xlsx')
    ckb_output_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_CKBCore_output.xlsx')
    dbSNP_output_annotation_file=os.path.exists(USER_INPUT_FOLDER_PATH+input_filename+'_dbSNP_output.xlsx')
    
    display_refresh = False
    if SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==True and dbNSFP_annotation_file==True and df_cadd_annotation_file==True and Clinvar_output_annotation_file==True and oncokb_output_annotation_file==True and ckb_output_annotation_file ==True and dbSNP_output_annotation_file== True:
        print('Annotations are complete')
    elif SIFT_indel_annotation_file==False:
        print('SIFT, SIFT 4G, dbNSFP, OncoKB, CADD and ClinVar annotations are going on')
        print('Please come back after sometime <Need to mention approx time based on input variants count>')
        display_refresh=True
    elif SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==False and dbNSFP_annotation_file==False and df_cadd_annotation_file==False and Clinvar_output_annotation_file==False and oncokb_output_annotation_file==False:
        print('SIFT annotations are completed , SIFT4G, OncoKB, CADD and ClinVar and dbNSFP annotations are going on')
        display_refresh=True
    elif SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==False and dbNSFP_annotation_file==False and df_cadd_annotation_file==False and Clinvar_output_annotation_file==True and oncokb_output_annotation_file==False:
        print('SIFT and ClinVar annotations are completed , SIFT4G, OncoKB, CADD and dbNSFP annotations are going on')
        display_refresh=True
    elif SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==False and dbNSFP_annotation_file==False and df_cadd_annotation_file==True and Clinvar_output_annotation_file==True and oncokb_output_annotation_file==False:
        print('SIFT, CADD and ClinVar annotations are completed , SIFT4G, OncoKB and dbNSFP annotations are going on')
        display_refresh=True
    elif SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==False and dbNSFP_annotation_file==False and df_cadd_annotation_file==True and Clinvar_output_annotation_file==True and oncokb_output_annotation_file==True:
        print('SIFT, CADD, OncoKB and ClinVar annotations are completed , SIFT4G and dbNSFP annotations are going on')
        display_refresh=True
    elif SIFT_indel_annotation_file==True and SIFT4G_annotation_file ==True and dbNSFP_annotation_file==False and df_cadd_annotation_file==True and Clinvar_output_annotation_file==True:
        print('SIFT, SIFT 4G, CADD and ClinVar annotations are completed , dbNSFP annotations is going on')
        display_refresh=True
    
    if display_refresh==True:
        previewButton1 = widgets.Button(description = "Refresh")
        previewButton1.on_click(functools.partial(click_refresh, input_filename=input_filename))
        display(previewButton1)
        
def click_refresh(b,input_filename):
    status(input_filename)

annotations(inp_df, input_filename)
status(input_filename)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),REF_dbsnp ref,ALT_dbsnp alt,vtype,dbSNP_Id,gnomAD-Genomes
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,A,G,SNV,,
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,T,A,SNV,,
2,1,64931096,.,A,T,.,PASS,DP=206;MQ=105.45;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:50,0:0.000:25,0:25,0:50:.:.","0/1:126.57:81,75:0.481:33,36:48,39:156:46,35,3...",JAK1,206,0.0,A,T,SNV,,
3,1,64969201,.,G,GT,.,PASS,DP=210;MQ=214.69;FractionInformativeReads=0.886,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,0:0.000:18,0:27,0:45:.:.","0/1:110.62:74,67:0.475:34,37:40,30:141:35,39,2...",JAK1,210,0.0,,T,ins,,
4,1,65022230,.,G,A,.,PASS,DP=243;MQ=214.83;FractionInformativeReads=0.996,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:62,0:0.000:31,0:31,0:62:.:.","0/1:132.48:105,75:0.417:56,39:49,36:180:45,60,...",JAK1,243,0.0,G,A,SNV,,
5,1,97142697,.,T,G,.,PASS,DP=116;MQ=190.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:21,0:28,0:49:.:.","0/1:181.80:0,67:1.000:0,36:0,31:67:0,0,38,29:0...",DPYD,116,0.0,T,G,SNV,,
6,1,97177779,.,T,A,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.000:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",DPYD,116,0.0,T,A,SNV,,
7,1,97371462,.,G,A,.,PASS,DP=109;MQ=190.06;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:20,0:26,0:46:.:.","0/1:102.48:33,30:0.476:18,9:15,21:63:15,18,19,...",DPYD,109,0.0,G,A,SNV,1352251059,0.000007
8,1,97527794,.,GA,G,.,PASS,DP=132;MQ=193.39;FractionInformativeReads=0.780,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,2:0.059:17,1:15,1:34:.:.","0/1:56.78:31,38:0.551:14,20:17,18:69:15,16,15,...",DPYD,132,5.9,A,,del,,
9,1,156865995,.,A,G,.,PASS,DP=238;MQ=208.22;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:72,0:0.000:38,0:34,0:72:.:.","0/1:27.68:158,8:0.048:73,2:85,6:166:88,70,3,5:...",NTRK1,238,0.0,A,G,SNV,,
10,1,162657625,.,A,T,.,PASS,DP=183;MQ=215.95;FractionInformativeReads=0.995,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:22,0:24,0:46:.:.","0/1:114.07:72,64:0.471:35,33:37,31:136:28,44,1...",DDR2,183,0.0,A,T,SNV,,
11,1,162696199,.,CT,C,.,PASS,DP=190;MQ=199.83;FractionInformativeReads=0.795,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:35,2:0.054:16,0:19,2:37:.:.","0/1:76.59:59,55:0.482:29,28:30,27:114:26,33,21...",DDR2,190,5.4,T,,del,,
12,1,162763185,.,AT,A,.,PASS,DP=156;MQ=200.81;FractionInformativeReads=0.872,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:30,1:0.032:12,1:18,0:31:.:.","0/1:57.07:57,48:0.457:24,19:33,29:105:26,31,31...",DDR2,156,3.2,T,,del,,
13,1,162772543,.,G,T,.,PASS,DP=207;MQ=211.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:28,0:31,0:59:.:.","0/1:67.24:114,34:0.230:55,18:59,16:148:67,47,1...",DDR2,207,0.0,G,T,SNV,,
14,1,179148318,.,G,A,.,PASS,DP=176;MQ=210.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:38,0:0.000:14,0:24,0:38:.:.","0/1:94.31:73,65:0.471:38,34:35,31:138:35,38,29...",ABL2,176,0.0,G,A,SNV,72709463,0.022405
15,1,193123292,.,A,G,.,PASS,DP=211;MQ=152.15;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:54,0:0.000:24,0:30,0:54:.:.","0/1:141.73:74,83:0.529:31,35:43,48:157:42,32,3...",CDC73,211,0.0,A,G,SNV,,
16,1,240911986,.,CA,C,.,PASS,DP=137;MQ=156.33;FractionInformativeReads=0.876,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:34,3:0.081:16,1:18,2:37:.:.","0/1:17.70:59,24:0.289:30,15:29,9:83:42,17,12,1...",RGS7,137,8.1,A,,del,,
17,1,241058004,.,C,A,.,PASS,DP=155;MQ=203.61;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:18,0:24,0:42:.:.","0/1:59.13:83,30:0.265:39,9:44,21:113:35,48,21,...",RGS7,155,0.0,C,A,SNV,,
18,1,241083225,.,CA,C,.,PASS,DP=156;MQ=148.37;FractionInformativeReads=0.788,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,2:0.053:21,1:15,1:38:.:.","0/1:62.10:42,43:0.506:29,19:13,24:85:12,30,24,...",RGS7,156,5.3,A,,del,,
19,1,241087972,.,CTCTCTATA,C,.,PASS,DP=147;MQ=136.05;FractionInformativeReads=0.932,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:31,0:0.000:15,0:16,0:31:.:.","0/1:57.62:63,43:0.406:30,22:33,21:106:26,37,10...",RGS7,147,0.0,TCTCTATA,,del,,
20,1,241094238,.,A,AAC,.,PASS,DP=147;MQ=180.33;FractionInformativeReads=0.585,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:26,0:0.000:12,0:14,0:26:.:.","0/1:55.38:28,32:0.533:11,15:17,17:60:10,18,14,...",RGS7,147,0.0,,AC,ins,,
21,1,241126809,.,AT,A,.,PASS,DP=207;MQ=211.76;FractionInformativeReads=0.870,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,3:0.070:20,2:20,1:43:.:.","0/1:33.67:98,39:0.285:47,23:51,16:137:63,35,25...",RGS7,207,7.0,T,,del,,
22,1,241128709,.,A,G,.,PASS,DP=207;MQ=198.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:72,1:0.014:31,1:41,0:73:.:.","0/1:71.38:104,30:0.224:59,16:45,14:134:71,33,1...",RGS7,207,1.4,A,G,SNV,,
23,1,241232136,.,C,T,.,PASS,DP=206;MQ=207.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:58,0:0.000:28,0:30,0:58:.:.","0/1:129.39:83,65:0.439:35,34:48,31:148:50,33,2...",RGS7,206,0.0,C,T,SNV,,
24,1,241234485,.,CT,C,.,PASS,DP=195;MQ=208.34;FractionInformativeReads=0.841,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,1:0.022:24,0:21,1:46:.:.","0/1:93.31:62,56:0.475:26,32:36,24:118:32,30,33...",RGS7,195,2.2,T,,del,,
25,1,241318460,.,CT,C,.,PASS,DP=200;MQ=191.20;FractionInformativeReads=0.815,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,0:0.000:19,0:17,0:36:.:.","0/1:87.83:66,61:0.480:36,32:30,29:127:33,33,28...",RGS7,200,0.0,T,,del,,
26,1,243727332,.,T,G,.,PASS,DP=156;MQ=194.28;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:41,0:0.000:24,0:17,0:41:.:.","0/1:122.28:42,73:0.635:24,36:18,37:115:20,22,4...",AKT3,156,0.0,T,G,SNV,,
27,2,29197299,.,C,G,.,PASS,DP=127;MQ=186.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:25,0:31,0:56:.:.","0/1:92.69:44,27:0.380:17,12:27,15:71:23,21,12,...",ALK,127,0.0,C,G,SNV,,
28,2,29249631,.,T,C,.,PASS,DP=123;MQ=182.39;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:57,0:0.000:25,0:32,0:57:.:.","0/1:100.58:39,27:0.409:19,20:20,7:66:19,20,15,...",ALK,123,0.0,T,C,SNV,,
29,2,29266768,.,T,C,.,PASS,DP=119;MQ=201.00;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:20,0:22,0:42:.:.","0/1:95.47:42,35:0.455:21,19:21,16:77:19,23,16,...",ALK,119,0.0,T,C,SNV,,
30,2,29394870,.,GT,G,.,PASS,DP=135;MQ=188.23;FractionInformativeReads=0.904,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:24,0:25,0:49:.:.","0/1:88.83:43,30:0.411:21,19:22,11:73:22,21,19,...",ALK,135,0.0,T,,del,,
31,2,29705282,.,A,ATATATATATATATATAT,.,PASS,DP=81;MQ=120.41;FractionInformativeReads=0.852,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,0:0.000:24,0:22,0:46:.:.","0/1:43.22:17,6:0.261:8,4:9,2:23:12,5,4,2:13,4,6,0",ALK,81,0.0,,TATATATATATATATAT,ins,1558451342,
32,2,29825713,.,GT,G,.,PASS,DP=119;MQ=180.17;FractionInformativeReads=0.924,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,1:0.020:27,1:22,0:50:.:.","0/1:89.84:31,29:0.483:13,13:18,16:60:17,14,10,...",ALK,119,2.0,T,,del,,
33,2,39096885,.,CA,C,.,PASS,DP=120;MQ=145.46;FractionInformativeReads=0.858,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,2:0.051:19,2:18,0:39:.:.","0/1:70.34:30,34:0.531:13,10:17,24:64:15,15,18,...",SOS1,120,5.1,A,,del,,
34,2,208248389,.,G,A,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.004,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.06:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",IDH1,116,6.0,G,A,SNV,121913499,0.000007
35,2,211677577,.,TA,T,.,PASS,DP=97;MQ=139.68;FractionInformativeReads=0.866,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,0:0.000:20,0:17,0:37:.:.","0/1:144.11:1,46:0.979:0,20:1,26:47:1,0,25,21:0...",ERBB4,97,0.0,A,,del,,
36,2,212322431,.,TA,T,.,PASS,DP=137;MQ=186.20;FractionInformativeReads=0.956,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:31,0:28,0:59:.:.","0/1:120.93:38,34:0.472:27,15:11,19:72:15,23,11...",ERBB4,137,0.0,A,,del,,
37,2,212538253,.,A,T,.,PASS,DP=127;MQ=192.56;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:50,0:0.000:21,0:29,0:50:.:.","0/1:184.81:0,76:1.000:0,40:0,36:76:0,0,38,38:0...",ERBB4,127,0.0,A,T,SNV,,
38,2,233772291,.,G,T,.,PASS,DP=124;MQ=194.40;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:19,0:30,0:49:.:.","0/1:181.80:0,75:1.000:0,36:0,39:75:0,0,45,30:0...",UGT1A1,124,0.0,G,T,SNV,,
39,3,52406255,.,G,A,.,PASS,DP=120;MQ=193.65;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:48,0:0.000:15,0:33,0:48:.:.","0/1:179.21:0,72:1.000:0,37:0,35:72:0,0,40,32:0...",BAP1,120,0.0,G,A,SNV,772448753,
40,3,53600934,.,C,G,.,PASS,DP=136;MQ=190.54;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:31,0:26,0:57:.:.","0/1:205.88:0,79:1.000:0,42:0,37:79:0,0,33,46:0...",CACNA1D,136,0.0,C,G,SNV,,
41,3,69848060,.,T,C,.,PASS,DP=107;MQ=164.67;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:32,0:24,0:56:.:.","0/1:58.68:38,13:0.255:23,8:15,5:51:22,16,12,1:...",MITF,107,0.0,T,C,SNV,2063761744,
42,3,169238554,.,CA,C,.,PASS,DP=153;MQ=190.79;FractionInformativeReads=0.941,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:60,0:0.000:26,0:34,0:60:.:.","0/1:216.39:0,84:1.000:0,47:0,37:84:0,0,44,40:0...",MECOM,153,0.0,A,,del,,
43,3,169382849,.,C,CA,.,PASS,DP=118;MQ=162.14;FractionInformativeReads=0.814,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,4:0.111:14,3:18,1:36:.:.","0/1:87.17:4,56:0.933:3,29:1,27:60:2,2,23,33:1,...",MECOM,118,11.1,,A,ins,,
44,3,169451252,.,GA,G,.,PASS,DP=154;MQ=197.89;FractionInformativeReads=0.870,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:44,4:0.083:18,3:26,1:48:.:.","0/1:106.99:1,85:0.988:0,43:1,42:86:1,0,39,46:0...",MECOM,154,8.3,A,,del,,
45,3,169606408,.,C,CA,.,PASS,DP=116;MQ=151.91;FractionInformativeReads=0.793,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:37,3:0.075:23,2:14,1:40:.:.","0/1:109.36:7,45:0.865:4,24:3,21:52:6,1,17,28:3...",MECOM,116,7.5,,A,ins,,
46,3,179175710,.,AT,A,.,PASS,DP=121;MQ=193.25;FractionInformativeReads=0.826,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.000:22,0:18,0:40:.:.","0/1:90.18:30,30:0.500:19,19:11,11:60:15,15,16,...",PIK3CA,121,0.0,T,,del,,
47,3,179218304,.,A,G,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.001,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.07:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",PIK3CA,116,7.0,A,G,SNV,121913274,
48,3,181714163,.,A,T,.,PASS,DP=129;MQ=170.18;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:55,0:0.000:29,0:26,0:55:.:.","0/1:119.37:38,35:0.479:22,19:16,16:73:26,12,14...",SOX2,129,0.0,A,T,SNV,186572523,0.000143
49,4,152369596,.,G,GA,.,PASS,DP=148;MQ=183.68;FractionInformativeReads=0.905,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:59,0:0.000:35,0:24,0:59:.:.","0/1:213.50:0,75:1.000:0,37:0,38:75:0,0,36,39:0...",FBXW7,148,0.0,,A,ins,,
50,5,31463883,.,G,A,.,PASS,DP=167;MQ=209.94;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:20,0:29,0:49:.:.","0/1:75.40:82,36:0.305:46,20:36,16:118:40,42,13...",DROSHA,167,0.0,G,A,SNV,,
51,5,80733107,.,A,G,.,PASS,DP=138;MQ=194.95;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:53,0:0.000:22,0:31,0:53:.:.","0/1:193.71:0,85:1.000:0,36:0,49:85:0,0,40,45:0...",MSH3,138,0.0,A,G,SNV,,
52,5,132605268,.,C,T,.,PASS,DP=117;MQ=167.14;FractionInformativeReads=0.991,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:23,0:26,0:49:.:.","0/1:90.35:40,27:0.403:21,18:19,9:67:20,20,9,18...",RAD50,117,0.0,C,T,SNV,,
53,6,151891819,.,CA,C,.,PASS,DP=117;MQ=178.91;FractionInformativeReads=0.966,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:-0.00:56,0:0.000:26,0:30,0:56:.:.:151891819","0|1:200.45:0,57:1.000:0,29:0,28:57:0,0,31,26:0...",ESR1,117,0.0,A,,del,,
54,6,151891824,.,A,T,.,PASS,DP=115;MQ=175.89;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:-0.00:58,0:0.000:27,0:31,0:58:.:.:151891819","0|1:204.89:0,57:1.000:0,29:0,28:57:0,0,31,26:0...",ESR1,115,0.0,A,T,SNV,,
55,6,151913052,.,G,A,.,PASS,DP=127;MQ=124.62;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:49,0:0.000:25,0:24,0:49:.:.","0/1:182.25:0,78:1.000:0,42:0,36:78:0,0,29,49:0...",ESR1,127,0.0,G,A,SNV,751979171,0.000014
56,6,157187897,.,G,A,.,PASS,DP=132;MQ=180.38;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:63,0:0.000:23,0:40,0:63:.:.","0/1:141.82:33,36:0.522:16,15:17,21:69:17,16,19...",ARID1B,132,0.0,G,A,SNV,1019085413,0.000014
57,7,55053312,.,GGTGCATCTCTA,G,.,PASS,DP=196;MQ=214.29;FractionInformativeReads=0.980,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:49,0:0.000:24,0:25,0:49:.:.","0/1:53.55:113,30:0.210:63,19:50,11:143:49,64,1...",EGFR,196,0.0,GTGCATCTCTA,,del,,
58,7,55086578,.,C,G,.,PASS,DP=195;MQ=209.55;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:57,1:0.017:29,1:28,0:58:.:.","0/1:114.73:72,65:0.474:31,34:41,31:137:33,39,4...",EGFR,195,1.7,C,G,SNV,1209074985,0.000014
59,7,55106841,.,C,G,.,PASS,DP=224;MQ=214.87;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:58,0:0.000:33,0:25,0:58:.:.","0/1:61.17:132,34:0.205:58,15:74,19:166:66,66,1...",EGFR,224,0.0,C,G,SNV,1792163144,
60,7,55195555,.,C,T,.,PASS,DP=212;MQ=159.83;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:56,0:0.000:30,0:26,0:56:.:.","0/1:72.41:116,40:0.256:56,20:60,20:156:60,56,1...",EGFR,212,0.0,C,T,SNV,,
61,7,148710746,.,C,G,.,PASS,DP=167;MQ=192.49;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:26,0:21,0:47:.:.","0/1:53.26:94,26:0.217:45,16:49,10:120:44,50,13...",CUL1,167,0.0,C,G,SNV,,
62,7,151484856,.,C,T,.,PASS,DP=138;MQ=186.92;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:59,0:0.000:29,0:30,0:59:.:.","0/1:134.93:39,40:0.506:20,25:19,15:79:13,26,28...",RHEB,138,0.0,C,T,SNV,,
63,8,38432410,.,AT,A,.,PASS,DP=109;MQ=178.19;FractionInformativeReads=0.679,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:19,1:0.050:12,1:7,0:20:.:.","0/1:21.00:34,20:0.370:20,12:14,8:54:17,17,6,14...",FGFR1,109,5.0,T,,del,,
64,8,51384860,.,A,C,.,PASS,DP=166;MQ=210.08;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:48,0:0.000:26,0:22,0:48:.:.","0/1:70.38:84,34:0.288:41,14:43,20:118:43,41,18...",PXDNL,166,0.0,A,C,SNV,,
65,8,51555485,.,A,AT,.,PASS,DP=156;MQ=214.26;FractionInformativeReads=0.929,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:35,0:0.000:14,0:21,0:35:.:.","0/1:68.86:70,40:0.364:32,17:38,23:110:35,35,25...",PXDNL,156,0.0,,T,ins,,
66,8,51576198,.,CA,C,.,PASS,DP=152;MQ=189.54;FractionInformativeReads=0.803,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,2:0.048:24,1:16,1:42:.:.","0/1:55.47:50,30:0.375:23,13:27,17:80:22,28,17,...",PXDNL,152,4.8,A,,del,,
67,8,51724953,.,C,T,.,PASS,DP=126;MQ=203.20;FractionInformativeReads=0.992,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:38,0:0.000:22,0:16,0:38:.:.","0/1:73.05:55,32:0.368:28,12:27,20:87:25,30,13,...",PXDNL,126,0.0,C,T,SNV,,
68,8,92007467,.,TA,T,.,PASS,DP=136;MQ=194.90;FractionInformativeReads=0.809,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:39,0:0.000:20,0:19,0:39:.:.","0/1:129.11:19,52:0.732:10,22:9,30:71:8,11,28,2...",RUNX1T1,136,0.0,A,,del,,
69,8,138145239,.,C,T,.,PASS,DP=151;MQ=188.96;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:53,0:0.000:30,0:23,0:53:.:.","0/1:95.91:61,37:0.378:33,20:28,17:98:38,23,21,...",FAM135B,151,0.0,C,T,SNV,,
70,8,138217522,.,C,A,.,PASS,DP=129;MQ=100.63;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:36,0:0.000:18,0:18,0:36:.:.","0/1:54.27:67,26:0.280:34,14:33,12:93:31,36,11,...",FAM135B,129,0.0,C,A,SNV,,
71,8,138227244,.,C,A,.,PASS,DP=169;MQ=206.34;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,1:0.019:27,1:25,0:53:.:.","0/1:31.33:104,12:0.103:58,5:46,7:116:42,62,6,6...",FAM135B,169,1.9,C,A,SNV,,
72,8,138298823,.,G,A,.,PASS,DP=159;MQ=175.51;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:45,0:0.000:23,0:22,0:45:.:.","0/1:81.09:74,40:0.351:37,22:37,18:114:42,32,20...",FAM135B,159,0.0,G,A,SNV,,
73,8,138353484,.,C,T,.,PASS,DP=136;MQ=194.12;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:54,0:0.000:27,0:27,0:54:.:.","0/1:81.96:55,27:0.329:29,20:26,7:82:28,27,11,1...",FAM135B,136,0.0,C,T,SNV,,
74,8,138357002,.,C,T,.,PASS,DP=146;MQ=200.60;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:27,0:25,0:52:.:.","0/1:87.25:61,33:0.351:29,12:32,21:94:28,33,16,...",FAM135B,146,0.0,C,T,SNV,,
75,8,138387843,.,C,G,.,PASS,DP=155;MQ=203.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:32,0:20,0:52:.:.","0/1:23.61:98,5:0.049:54,3:44,2:103:59,39,4,1:4...",FAM135B,155,0.0,C,G,SNV,,
76,8,138410083,.,A,C,.,PASS,DP=139;MQ=202.11;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:48,0:0.000:25,0:23,0:48:.:.","0/1:84.37:58,33:0.363:31,17:27,16:91:34,24,16,...",FAM135B,139,0.0,A,C,SNV,,
77,9,8327022,.,C,G,.,PASS,DP=66;MQ=19.59;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:46,2:0.042:17,1:29,1:48:.:.","0/1:98.53:0,18:1.000:0,9:0,9:18:0,0,7,11:0,0,12,6",PTPRD,66,4.2,C,G,SNV,13285902,0.027679
78,9,8373832,.,GTA,G,.,PASS,DP=134;MQ=148.72;FractionInformativeReads=0.612,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:20,5:12,3:40:.:.:8373828","0|1:59.38:3,39:0.929:2,23:1,16:42:1,2,18,21:2,...",PTPRD,134,20.0,TA,,del,,
79,9,8373850,.,GTA,G,.,PASS,DP=123;MQ=127.34;FractionInformativeReads=0.659,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:19,5:13,3:40:.:.:8373828","0|1:53.99:3,38:0.927:2,23:1,15:41:1,2,18,20:2,...",PTPRD,123,20.0,TA,,del,,
80,9,8373854,.,G,C,.,PASS,DP=121;MQ=125.46;FractionInformativeReads=0.669,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB:PS,"0|0:0.00:32,8:0.200:19,5:13,3:40:.:.:8373828","0|1:53.33:3,38:0.927:2,23:1,15:41:1,2,18,20:2,...",PTPRD,121,20.0,G,C,SNV,199627123,
81,9,8772136,.,A,C,.,PASS,DP=167;MQ=195.04;FractionInformativeReads=0.898,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:29,0:28,0:57:.:.","0/1:171.16:33,60:0.645:19,33:14,27:93:18,15,41...",PTPRD,167,0.0,A,C,SNV,953605091,
82,9,8775421,.,C,G,.,PASS,DP=149;MQ=201.33;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:52,0:0.000:32,0:20,0:52:.:.","0/1:106.60:56,41:0.423:32,19:24,22:97:20,36,17...",PTPRD,149,0.0,C,G,SNV,,
83,9,9030415,.,G,A,.,PASS,DP=113;MQ=211.66;FractionInformativeReads=0.991,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:32,0:0.000:15,0:17,0:32:.:.","0/1:131.08:0,80:1.000:0,44:0,36:80:0,0,40,40:0...",PTPRD,113,0.0,G,A,SNV,140988336,
84,9,9238315,.,G,T,.,PASS,DP=172;MQ=216.51;FractionInformativeReads=0.994,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:42,0:0.000:20,0:22,0:42:.:.","0/1:73.99:86,43:0.333:47,25:39,18:129:37,49,22...",PTPRD,172,0.0,G,T,SNV,,
85,9,9352355,.,A,G,.,PASS,DP=133;MQ=127.89;FractionInformativeReads=0.947,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:43,0:0.000:24,0:19,0:43:.:.","0/1:163.53:1,82:0.988:1,38:0,44:83:1,0,28,54:1...",PTPRD,133,0.0,A,G,SNV,9408764,0.00635
86,9,9447430,.,G,A,.,PASS,DP=157;MQ=187.29;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:39,0:0.000:18,0:21,0:39:.:.","0/1:151.70:0,118:1.000:0,54:0,64:118:0,0,52,66...",PTPRD,157,0.0,G,A,SNV,746991250,
87,9,9783317,.,T,C,.,PASS,DP=178;MQ=217.72;FractionInformativeReads=0.989,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:43,0:0.000:27,0:16,0:43:.:.","0/1:115.74:57,76:0.571:30,39:27,37:133:32,25,4...",PTPRD,178,0.0,T,C,SNV,,

no:1,pos:9665241,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%209665241[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:11216105,ref:T,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2011216105[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:64931096,ref:A,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2064931096[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:64969201,ref:,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2064969201[Base%20Position])%20AND%20ins
Error occured 'NoneType' object is not subscriptable
no:1,pos:65022230,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2065022230[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:97142697,ref:T,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2097142697[Base%20Position])%20AND%20SNV
1360740492
Alleles: T>C
['T>C']
T>G
rs id not found
False
no:1,pos:97177779,ref:T,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2097177779[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:97371462,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2097371462[Base%20Position])%20AND%20SNV
1352251059
Alleles: G>A
['G>A']
G>A
The rs id is 1352251059
True
1352251059
https://www.ncbi.nlm.nih.gov/snp/rs1352251059#frequency_tab
Extracted value: A=0.000007
Allele frequency for the A allele is 0.000007
no:1,pos:97527794,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%2097527794[Base%20Position])%20AND%20del
1649261083
Alleles: delGA
['delGA']
rs id not found
False
no:1,pos:156865995,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20156865995[Base%20Position])%20AND%20SNV
959318178
Alleles: A>T
['A>T']
A>G
rs id not found
False
no:1,pos:162657625,ref:A,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20162657625[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:162696199,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20162696199[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:162763185,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20162763185[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:162772543,ref:G,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20162772543[Base%20Position])%20AND%20SNV
1165463099
Alleles: G>A
['G>A']
G>T
rs id not found
False
no:1,pos:179148318,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20179148318[Base%20Position])%20AND%20SNV
72709463
Alleles: G>A
['G>A']
G>A
The rs id is 72709463
True
72709463
https://www.ncbi.nlm.nih.gov/snp/rs72709463#frequency_tab
Extracted value: A=0.022405
Allele frequency for the A allele is 0.022405
no:1,pos:193123292,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20193123292[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:240911986,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20240911986[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:241058004,ref:C,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241058004[Base%20Position])%20AND%20SNV
73125553
Alleles: C>G
['C>G']
C>A
rs id not found
False
no:1,pos:241083225,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241083225[Base%20Position])%20AND%20del
2063241683
Alleles: delCAA
['delCAA']
rs id not found
False
1491500245
Alleles: delCA
['delCA']
rs id not found
False
1163602445
Alleles: delC
['delC']
rs id not found
False
no:1,pos:241087972,ref:TCTCTATA,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241087972[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:241094238,ref:,alt:AC
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241094238[Base%20Position])%20AND%20ins
2064091055
Alleles: insC / ins(CA)<sub>5</sub>C
['insC', ' ins(CA)<sub>5</sub>C']
rs id not found
False
no:1,pos:241126809,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241126809[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:241128709,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241128709[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:241232136,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241232136[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:1,pos:241234485,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241234485[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:241318460,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20241318460[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:1,pos:243727332,ref:T,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((1[Chromosome])%20AND%20243727332[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:2,pos:29197299,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029197299[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:2,pos:29249631,ref:T,alt:C
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029249631[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:2,pos:29266768,ref:T,alt:C
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029266768[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:2,pos:29394870,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029394870[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:2,pos:29705282,ref:,alt:TATATATATATATATAT
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029705282[Base%20Position])%20AND%20ins
1558451342
Alleles: insT / insTAT / insTATAT / ins(TA)<sub>3</sub>T / ins(TA)<sub>4</sub>T / ins(TA)<sub>5</sub>T / ins(TA)<sub>6</sub>T / ins(TA)<sub>7</sub>T / ins(TA)<sub>8</sub>T / ins(TA)<sub>9</sub>T / ins(TA)<sub>10</sub>T / insTCT
['insT', ' insTAT', ' insTATAT', ' ins(TA)<sub>3</sub>T', ' ins(TA)<sub>4</sub>T', ' ins(TA)<sub>5</sub>T', ' ins(TA)<sub>6</sub>T', ' ins(TA)<sub>7</sub>T', ' ins(TA)<sub>8</sub>T', ' ins(TA)<sub>9</sub>T', ' ins(TA)<sub>10</sub>T', ' insTCT']
insTATATATATATATATAT==match
The rs id is 1558451342
True
1558451342
https://www.ncbi.nlm.nih.gov/snp/rs1558451342#frequency_tab
no:2,pos:29825713,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2029825713[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:2,pos:39096885,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%2039096885[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:2,pos:208248389,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%20208248389[Base%20Position])%20AND%20SNV
121913501
N/A
['N/A']
G>A
rs id not found
False
121913499
Alleles: G>A / G>C / G>T
['G>A', ' G>C', ' G>T']
G>A
The rs id is 121913499
G>A
G>A
True
121913499
https://www.ncbi.nlm.nih.gov/snp/rs121913499#frequency_tab
Extracted value: A=0.000007
Allele frequency for the A allele is 0.000007
no:2,pos:211677577,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%20211677577[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:2,pos:212322431,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%20212322431[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:2,pos:212538253,ref:A,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%20212538253[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:2,pos:233772291,ref:G,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((2[Chromosome])%20AND%20233772291[Base%20Position])%20AND%20SNV
1248654212
Alleles: G>A
['G>A']
G>T
rs id not found
False
no:3,pos:52406255,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%2052406255[Base%20Position])%20AND%20SNV
772448753
Alleles: G>A / G>C / G>T
['G>A', ' G>C', ' G>T']
G>A
The rs id is 772448753
G>A
G>A
True
772448753
https://www.ncbi.nlm.nih.gov/snp/rs772448753#frequency_tab
no:3,pos:53600934,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%2053600934[Base%20Position])%20AND%20SNV
2093433535
Alleles: C>T
['C>T']
C>G
rs id not found
False
no:3,pos:69848060,ref:T,alt:C
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%2069848060[Base%20Position])%20AND%20SNV
2063761744
Alleles: T>C
['T>C']
T>C
The rs id is 2063761744
True
2063761744
https://www.ncbi.nlm.nih.gov/snp/rs2063761744#frequency_tab
no:3,pos:169238554,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20169238554[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:3,pos:169382849,ref:,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20169382849[Base%20Position])%20AND%20ins
Error occured 'NoneType' object is not subscriptable
no:3,pos:169451252,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20169451252[Base%20Position])%20AND%20del
1745527164
Alleles: delG
['delG']
rs id not found
False
no:3,pos:169606408,ref:,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20169606408[Base%20Position])%20AND%20ins
Error occured 'NoneType' object is not subscriptable
no:3,pos:179175710,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20179175710[Base%20Position])%20AND%20del
1723679701
Alleles: delA
['delA']
rs id not found
False
no:3,pos:179218304,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20179218304[Base%20Position])%20AND%20SNV
121913274
Alleles: A>C / A>G / A>T
['A>C', ' A>G', ' A>T']
A>G
A>G
The rs id is 121913274
A>G
True
121913274
https://www.ncbi.nlm.nih.gov/snp/rs121913274#frequency_tab
no:3,pos:181714163,ref:A,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((3[Chromosome])%20AND%20181714163[Base%20Position])%20AND%20SNV
186572523
Alleles: A>T
['A>T']
A>T
The rs id is 186572523
True
186572523
https://www.ncbi.nlm.nih.gov/snp/rs186572523#frequency_tab
Extracted value: T=0.000143
Allele frequency for the T allele is 0.000143
no:4,pos:152369596,ref:,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((4[Chromosome])%20AND%20152369596[Base%20Position])%20AND%20ins
Error occured 'NoneType' object is not subscriptable
no:5,pos:31463883,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((5[Chromosome])%20AND%2031463883[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:5,pos:80733107,ref:A,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((5[Chromosome])%20AND%2080733107[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:5,pos:132605268,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((5[Chromosome])%20AND%20132605268[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:6,pos:151891819,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((6[Chromosome])%20AND%20151891819[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:6,pos:151891824,ref:A,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((6[Chromosome])%20AND%20151891824[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:6,pos:151913052,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((6[Chromosome])%20AND%20151913052[Base%20Position])%20AND%20SNV
751979171
Alleles: G>A / G>T
['G>A', ' G>T']
G>A
The rs id is 751979171
G>A
True
751979171
https://www.ncbi.nlm.nih.gov/snp/rs751979171#frequency_tab
Extracted value: A=0.000014
Allele frequency for the A allele is 0.000014
no:6,pos:157187897,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((6[Chromosome])%20AND%20157187897[Base%20Position])%20AND%20SNV
1019085413
Alleles: G>A
['G>A']
G>A
The rs id is 1019085413
True
1019085413
https://www.ncbi.nlm.nih.gov/snp/rs1019085413#frequency_tab
Extracted value: A=0.000014
Allele frequency for the A allele is 0.000014
no:7,pos:55053312,ref:GTGCATCTCTA,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%2055053312[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:7,pos:55086578,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%2055086578[Base%20Position])%20AND%20SNV
1209074985
Alleles: C>G
['C>G']
C>G
The rs id is 1209074985
True
1209074985
https://www.ncbi.nlm.nih.gov/snp/rs1209074985#frequency_tab
Extracted value: G=0.000014
Allele frequency for the G allele is 0.000014
no:7,pos:55106841,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%2055106841[Base%20Position])%20AND%20SNV
1792163144
Alleles: C>G
['C>G']
C>G
The rs id is 1792163144
True
1792163144
https://www.ncbi.nlm.nih.gov/snp/rs1792163144#frequency_tab
no:7,pos:55195555,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%2055195555[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:7,pos:148710746,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%20148710746[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:7,pos:151484856,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((7[Chromosome])%20AND%20151484856[Base%20Position])%20AND%20SNV
1802439977
Alleles: C>A
['C>A']
C>T
rs id not found
False
no:8,pos:38432410,ref:T,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2038432410[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:8,pos:51384860,ref:A,alt:C
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2051384860[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:51555485,ref:,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2051555485[Base%20Position])%20AND%20ins
Error occured 'NoneType' object is not subscriptable
no:8,pos:51576198,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2051576198[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:8,pos:51724953,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2051724953[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:92007467,ref:A,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%2092007467[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:8,pos:138145239,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138145239[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:138217522,ref:C,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138217522[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:138227244,ref:C,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138227244[Base%20Position])%20AND%20SNV
1819526660
Alleles: C>T
['C>T']
C>A
rs id not found
False
no:8,pos:138298823,ref:G,alt:A
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138298823[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:138353484,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138353484[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:138357002,ref:C,alt:T
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138357002[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:8,pos:138387843,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138387843[Base%20Position])%20AND%20SNV
1279318332
Alleles: C>T
['C>T']
C>G
rs id not found
False
no:8,pos:138410083,ref:A,alt:C
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((8[Chromosome])%20AND%20138410083[Base%20Position])%20AND%20SNV
Error occured 'NoneType' object is not subscriptable
no:9,pos:8327022,ref:C,alt:G
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((9[Chromosome])%20AND%208327022[Base%20Position])%20AND%20SNV
13285902
Alleles: C>A / C>G / C>T
['C>A', ' C>G', ' C>T']
C>G
C>G
The rs id is 13285902
C>G
True
13285902
https://www.ncbi.nlm.nih.gov/snp/rs13285902#frequency_tab
Extracted value: G=0.027679
Allele frequency for the G allele is 0.027679
no:9,pos:8373832,ref:TA,alt:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=snp&term=((9[Chromosome])%20AND%208373832[Base%20Position])%20AND%20del
Error occured 'NoneType' object is not subscriptable
no:9,pos:8373850,ref:TA,alt:

TO CREATE A DISPLAY TABLE

In [32]:
def displayVariants(file):
    file_name = os.path.splitext(file)[0]
    
    input_vcf_df=read_vcf(USER_INPUT_FOLDER_PATH+file)
    input_vcf_df["snp_pos"] = input_vcf_df["#CHROM"].astype(str) + ","+input_vcf_df["POS"].astype(str)
    chr_no=list(input_vcf_df['#CHROM'])
    print('Total Number of Variants:',len(chr_no))
        
    display(input_vcf_df.head(2))
    
    #Integration of SIFT INDEL 
    try:
        #trying to open a file in read mode
        df_SIFT = pd.read_csv(USER_INPUT_FOLDER_PATH+'SIFT_indel_'+file_name+'.tsv',sep='\t') 
        print('SIFT Indel OUTPUT')
        display(df_SIFT.head(2))
    except FileNotFoundError:
        print("SIFT Annotations in progress..")
        return
    except:
        print("Other error")
        return
    # Splitting 'Coordinates' column into separate columns
    df_SIFT[['N1', 'N2', 'UK1','UK2','UK3']] = df_SIFT['Coordinates'].str.split(',', expand=True)
    #display(df_SIFT.head(2))
    # Combining 'N1' and 'N2' columns to create 'snp_pos' column
    df_SIFT['snp_pos']=df_SIFT['N1'].astype(str) + ','+df_SIFT['N2'].astype(str)
    
    # Selecting required columns from SIFT INDEL 
    df_SIFT=df_SIFT[['snp_pos','Gene Name','Amino acid position change','Amino acid change','Substitution Type','Effect','Region']]
    #print('DF--------------')
    #display(df.head(2))
    # Merging SIFT dataframe with input_vcf_df on 'snp_pos' column
    merged = pd.merge(input_vcf_df,df_SIFT, how='left', on='snp_pos')
    # Renaming columns according to the display table requirement
    merged.rename(columns = {'Amino acid position change':'Amino acid position','Amino acid change_y':'Amino acid change','Substitution Type':'Mutation type','Effect':'SIFT4G prediction'}, inplace = True)
    print('Merged SIFT Indel-------------')
    display(merged.head(2))
    

    #Intergration of SIFT 4G
    try:
        sift_4g_file=TEMP_FOLDER_PATH+file_name+'_SIFTannotations.xls'
    except FileNotFoundError:
        print("SIFT4G Annotations in progress..")
        return
    except:
        print("Other error")
        return

    sift_4g_df = pd.read_csv(sift_4g_file, sep='\t')
    print('SIFT 4G output')
    display(sift_4g_df.head(2))
    # Combining chromosome and position to create 'snp_pos' column
    sift_4g_df["snp_pos"] = sift_4g_df["CHROM"].astype(str) + "," + sift_4g_df["POS"].astype(str)
    sift_4g_df['snp_pos'] = sift_4g_df['snp_pos'].str.replace('chr', '') 
    sift_4g_df['aa_change'] = sift_4g_df["REF_AMINO"].astype(str) + sift_4g_df["AMINO_POS"].astype(str) + sift_4g_df["ALT_AMINO"].astype(str)
    
    # Merging SIFT 4G dataframe with the previously merged dataframe on 'snp_pos' column
    merged_SIFT4G = pd.merge(merged, sift_4g_df, how='left', on='snp_pos')
    merged_SIFT4G.replace(np.NaN, '', inplace=True)
    merged_SIFT4G.replace(np.nan, '', inplace=True)
    merged_SIFT4G.replace(to_replace=["nan", 'nannannan'], value="", inplace=True)
    
    # Concatenating relevant columns from SIFT INDEL AND SIFT 4G 
    merged_SIFT4G["Gene_Name"] = merged_SIFT4G["Gene Name"] + merged_SIFT4G["GENE_NAME"]
    merged_SIFT4G["Amino_acid_position"] = merged_SIFT4G["Amino acid position"] + merged_SIFT4G["AMINO_POS"].astype(str)
    merged_SIFT4G["Amino_acid_change"] = merged_SIFT4G["Amino acid change"] + merged_SIFT4G["aa_change"]
    merged_SIFT4G["Mutation_type"] = merged_SIFT4G["Mutation type"] + merged_SIFT4G["VARIANT_TYPE"]
    merged_SIFT4G["SIFT4G_prediction"] = merged_SIFT4G["SIFT4G prediction"] + merged_SIFT4G["SIFT_PREDICTION"]
    
    merged_SIFT4G['HGVS nomenclature'] = ''
    merged_SIFT4G['Amino_acid_position'] = merged_SIFT4G['Amino_acid_position'].astype(str).apply(lambda x: x.replace('.0', ''))
    merged_SIFT4G['Amino_acid_change'] = merged_SIFT4G['Amino_acid_change'].astype(str).apply(lambda x: x.replace('.0', ''))
    merged_SIFT4G.rename(columns={'dbSNP':'dbsnp', 'POS_x': 'POS'}, inplace=True)
    merged_SIFT4G['dbsnp'] = merged_SIFT4G['dbsnp'].apply(lambda x: x if isinstance(x, str) and (x.startswith('rs') or x == 'novel') else '')
    merged_SIFT4G['REGION'] = merged_SIFT4G['Region'] + merged_SIFT4G['REGION']
    
    # Dropping unnecessary columns
    columns_to_drop = ['Region', 'CHROM', 'POS_y', 'REF_ALLELE', 'ALT_ALLELE', 'REF_AMINO', 'ALT_AMINO', 
                       'Gene Name', 'Mutation type', 'Amino acid change', 'SIFT4G prediction', 'Amino acid position', 
                       'GENE_NAME', 'VARIANT_TYPE', 'SIFT_PREDICTION', 'AMINO_POS', 'aa_change', 'TRANSCRIPT_ID', 
                       'GENE_ID', 'SIFT_SCORE', 'SIFT_MEDIAN', 'NUM_SEQS']
    merged_SIFT4G.drop(columns=columns_to_drop, axis=1, inplace=True)
    
    print("merged_SIFT4G")
    display(merged_SIFT4G.head(2))
    
    #Integration of dbNSFP
    try:
        #db_path=file_path+file_new+'.vcf.tsv'
        dbnsfp_path=USER_INPUT_FOLDER_PATH+file_name+'.vcf_dbNSFP.tsv'
    except FileNotFoundError:
        print("dbNSFP Annotations in progress..")
        return
    except:
        print("Other error")
        return

    # Reading dbNSFP file
    dbnsfp_df = pd.read_csv(dbnsfp_path, sep='\t', encoding='latin1')
    print('dbNSFP output')
    display(dbnsfp_df.head(2))
    dbnsfp_df['dbNSFP Amino acid change'] = dbnsfp_df['MutationTaster_AAE'].astype(str).str.replace(".;", "").str.replace(";", " ")
    dbnsfp_df['POS']=list(dbnsfp_df['POS'])
    
    #The check_splicesite function determines if a row in the DataFrame corresponds to a splicesite mutation by checking if both 'aaref' and 'aaalt' are either '.' or non-string/empty values, and labels such rows as 'Splicesite'. This function is then applied to each row in dbnsfp_df, and the result is stored in the new column 'Mutation_Type'.
    def check_splicesite(row):
        if (row['aaref'] == '.' and row['aaalt'] == '.' or
            not isinstance(row['aaref'], str) and not isinstance(row['aaalt'], str) or
            row['aaref'] == '' and row['aaalt'] == ''):
            return 'Splicesite'
        return '' 
    dbnsfp_df['Mutation_Type'] = dbnsfp_df.apply(check_splicesite, axis=1)
    
    # Selecting required columns from dbNSFP dataframe
    dbnsfp_df['aapos']=dbnsfp_df['aapos'].str.split(';').apply(set).str.join(',')
    dbnsfp_df['genename']=dbnsfp_df['genename'].str.split(';').apply(set).str.join(',')
    dbnsfp_df=dbnsfp_df[['POS','aapos','genename','MutationTaster_AAE','rs_dbSNP','Mutation_Type', 'dbNSFP Amino acid change']]
    dbnsfp_df['rs_dbSNP'] = dbnsfp_df['rs_dbSNP'].apply(lambda x: x if isinstance(x, str) and (x.startswith('rs') or x == 'novel') else '')
    
    # Merging dbNSFP dataframe with merged_SIFT4G dataframe on 'POS' column
    all_columns = list(dbnsfp_df) 
    dbnsfp_df[all_columns] = dbnsfp_df[all_columns].astype(str)
    all_columns = list(merged_SIFT4G) 
    merged_SIFT4G[all_columns] = merged_SIFT4G[all_columns].astype(str)
    merged_SIFT4G_dbNSFP = pd.merge(merged_SIFT4G,dbnsfp_df, how='left', on='POS')

    # Concatenating relevant columns between dbNSFP dataframe and merged_SIFT4G dataframe
    merged_SIFT4G_dbNSFP["dbSNP"] = merged_SIFT4G_dbNSFP["dbsnp"] +' '+merged_SIFT4G_dbNSFP["rs_dbSNP"]
    merged_SIFT4G_dbNSFP["Amino acid position"] = merged_SIFT4G_dbNSFP["Amino_acid_position"]+' '+merged_SIFT4G_dbNSFP["aapos"]
    merged_SIFT4G_dbNSFP["Gene Name"] = merged_SIFT4G_dbNSFP["Gene_Name"]+' '+merged_SIFT4G_dbNSFP["genename"]
    merged_SIFT4G_dbNSFP["Amino acid change"] = merged_SIFT4G_dbNSFP["Amino_acid_change"]
    merged_SIFT4G_dbNSFP["Mutation type"] = merged_SIFT4G_dbNSFP["Mutation_type"]+' '+merged_SIFT4G_dbNSFP["Mutation_Type"]

    # Additional modifications to clean the column 
    merged_SIFT4G_dbNSFP['dbSNP'] = merged_SIFT4G_dbNSFP['dbSNP'].astype(str).replace('nan', '')
    merged_SIFT4G_dbNSFP['dbSNP'] = merged_SIFT4G_dbNSFP['dbSNP'].str.split(' ').apply(set).str.join(' ')
    merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'] = merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'].astype(str).replace('nan', '')
    merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'] = merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'].str.split(' ').apply(set).str.join(' ')
    merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'] = merged_SIFT4G_dbNSFP['dbNSFP Amino acid change'].str.replace('.', '')
    merged_SIFT4G_dbNSFP['Gene Name'] = merged_SIFT4G_dbNSFP['Gene Name'].astype(str)
    merged_SIFT4G_dbNSFP['Gene Name']=merged_SIFT4G_dbNSFP['Gene Name'].str.split(' ').apply(set).str.join(' ')
    merged_SIFT4G_dbNSFP['Gene Name'] = merged_SIFT4G_dbNSFP['Gene Name'].str.replace(' ', '')
    merged_SIFT4G_dbNSFP['Mutation type']=merged_SIFT4G_dbNSFP['Mutation type'].astype(str)
    merged_SIFT4G_dbNSFP['Mutation type']=merged_SIFT4G_dbNSFP['Mutation type'].str.split(' ').apply(set).str.join(' ')
    
    # Dropping unnecessary columns
    merged_SIFT4G_dbNSFP.drop(['dbsnp','rs_dbSNP','Gene_Name','Mutation_Type','Amino_acid_change','Amino_acid_position','genename','Mutation_type','aapos',"MutationTaster_AAE"], axis =1, inplace=True)
    # Reordering columns
    merged_SIFT4G_dbNSFP=merged_SIFT4G_dbNSFP[['#CHROM','POS','REF','ALT','FILTER','Depth', 'Allele Frequency (%)', 'Gene name_BED file','snp_pos','SIFT4G_prediction','dbSNP','Amino acid position','Gene Name','Amino acid change','dbNSFP Amino acid change','REGION','Mutation type','HGVS nomenclature']]
    
    # Handling missing values in 'Gene Name' column
    # Filtering rows with missing 'Gene Name' in merged_SIFT4G_dbNSFP dataframe
    db_fill_gene=merged_SIFT4G_dbNSFP.loc[merged_SIFT4G_dbNSFP['Gene Name'] == '']
    # Reading dbNSFP file again to fill missing values
    dbnsfp_fill = pd.read_csv(dbnsfp_path, sep='\t', encoding='latin1')

    # Creating a dataframe to store the relevant columns from dbNSFP for filling missing values
    db_fill_gene1=pd.DataFrame()
    db_fill_gene1['#CHROM']=list(dbnsfp_fill['#CHROM'])
    db_fill_gene1['POS']=list(dbnsfp_fill['POS'])
    db_fill_gene1['Amino acid position']=list(dbnsfp_fill['aapos'])
    db_fill_gene1['Gene Name']=list(dbnsfp_fill['genename'])
    db_fill_gene1['dbSNP']=list(dbnsfp_fill['rs_dbSNP'])
    
    db_fill_gene1['SIFT4G_prediction']=list(dbnsfp_fill['SIFT4G_pred'])
    
    db_fill_gene1['Gene Name'] = db_fill_gene1['Gene Name'].str.split(';').str[0]
    # Replacing 'D' with 'DELETERIOUS' in 'SIFT4G_prediction' column
    db_fill_gene1['SIFT4G_prediction'].replace({'D':'DELETERIOUS'}, regex=True, inplace=True)

    # Merging db_fill_gene and db_fill_gene1 dataframes to fill missing values in merged_SIFT4G_dbNSFP dataframe
    db_fill_gene['#CHROM']=db_fill_gene['#CHROM'].astype(str)
    db_fill_gene1['#CHROM']=db_fill_gene1['#CHROM'].astype(str)
    db_fill_gene1['POS']=db_fill_gene1['POS'].astype(str)
    db_fil = pd.merge(db_fill_gene,db_fill_gene1, how='left', on=['#CHROM','POS'])
    
    # Dropping unnecessary columns and renaming columns
    db_fil.drop(['SIFT4G_prediction_x', 'dbSNP_x', 'Amino acid position_x','Gene Name_x'], axis = 1, inplace=True)
    db_fil.rename(columns = {'Amino acid position_y':'Amino acid position', 'Gene Name_y':'Gene Name', 'dbSNP_y':'dbSNP','SIFT4G_prediction_y':'SIFT4G_prediction'}, inplace = True)
    # Reordering columns
    db_fil=db_fil[['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'Depth', 
           'snp_pos', 'SIFT4G_prediction','dbSNP','Amino acid position', 'Gene Name','Amino acid change',
           'dbNSFP Amino acid change', 'REGION', 'Mutation type',
           'HGVS nomenclature']]
    
    # Setting values for 'REGION' and 'Mutation type' columns where 'Gene Name' is not missing
    db_fil.loc[db_fil['Gene Name'].isnull() == False, 'REGION'] = 'CDS'                       
    db_fil.loc[db_fil['Gene Name'].isnull() == False, 'Mutation type'] = 'NONSYNONYMOUS'  
    
    # Concatenating the filled dataframe with the original dataframe
    merged_SIFT4G_dbNSFP1=merged_SIFT4G_dbNSFP.copy(deep=True)
    merged_SIFT4G_dbNSFP1.drop(merged_SIFT4G_dbNSFP1.index[merged_SIFT4G_dbNSFP1['Gene Name'] == ''], inplace=True)
    merged_SIFT4G_dbNSFP2 = pd.concat([merged_SIFT4G_dbNSFP1, db_fil])
    
    # Sorting the concatenated dataframe
    def custom_sort_key(value):
        if pd.isna(value): # If the value is NaN, assign it a priority of 1
            return (1, value)  
        elif isinstance(value, str) and value.isdigit(): # If the value is a string of digits, convert it to int and assign a priority of 2
            return (2, int(value))  
        else: # For all other cases, assign a priority of 3
            return (3, value) 
            
    # Apply the custom sorting key function to the '#CHROM' column of the merged dataframe
    merged_SIFT4G_dbNSFP2['_sort_key'] = merged_SIFT4G_dbNSFP2['#CHROM'].apply(custom_sort_key)
    # Sort the dataframe based on the '_sort_key' column
    merged_SIFT4G_dbNSFP2.sort_values(by='_sort_key', inplace=True)
    merged_SIFT4G_dbNSFP2.drop('_sort_key', axis=1, inplace=True)
    merged_SIFT4G_dbNSFP2.reset_index(drop=True, inplace=True)
    merged_SIFT4G_dbNSFP3 = merged_SIFT4G_dbNSFP2.copy(deep=True)

    # Creating 'snp_pos1' column
    merged_SIFT4G_dbNSFP3["snp_pos1"] = 'chr'+merged_SIFT4G_dbNSFP3["#CHROM"].astype(str) +':'+ merged_SIFT4G_dbNSFP3["POS"].astype(str)
    merged_SIFT4G_dbNSFP3.snp_pos1 = merged_SIFT4G_dbNSFP3.snp_pos1.str.replace(' ', '')
    merged_SIFT4G_dbNSFP3["snp_pos1"]
    
    print('merged_dbNSFP3')
    display(merged_SIFT4G_dbNSFP3.head(2))

    #Integration of CADD-SNV
    try:
        cadd_path = USER_INPUT_FOLDER_PATH+file_name+'_cadd_data.xlsx'
    except FileNotFoundError:
        print("CADD Annotations in progress..")
        return
    except:
        print("Other error")
        return
    cadd_df = pd.read_excel(cadd_path)
    print('CADD output')
    display(cadd_df.head(2))
    cadd_df['snp_pos1'] = 'chr'+cadd_df['Chrom'].astype(str) +':'+ cadd_df['Position'].astype(str)
    cadd_selected_columns = ['Consequence', 'Exon', 'Intron', 'PHRED', 'Grantham', 'snp_pos1']
    cadd_df = cadd_df[cadd_selected_columns]
    new_column_names = {'Consequence': 'CADD_Consequence', 'Exon': 'Exon Number', 'Intron': 'Intron number', 'PHRED': 'CADD_PHRED', 'Grantham': 'CADD_Grantham'}
    cadd_df = cadd_df.rename(columns=new_column_names)
    def determine_cadd_prediction(phred_value):
        if pd.isnull(phred_value) or phred_value == '':
            return ''  
        elif phred_value >= 15:
            return 'Deleterious'
        else:
            return 'Benign'
    cadd_df['CADD_Prediction'] = cadd_df['CADD_PHRED'].apply(determine_cadd_prediction)
    merged_dbNSFP1_cadd= pd.merge(merged_SIFT4G_dbNSFP3, cadd_df, how='left', on='snp_pos1')
    merged_dbNSFP1_cadd = merged_dbNSFP1_cadd.drop_duplicates()
    print('merged_CADD')
    display(merged_dbNSFP1_cadd.head(2))
    
    #Integration of ClinVar
    try:
        clinvar_path = USER_INPUT_FOLDER_PATH+file_name+'_clinvar_output.xlsx'
    except FileNotFoundError:
        print("ClinVar Annotations in progress..")
        return
    except:
        print("Other error")
        return
    clinvar_file = pd.read_excel(clinvar_path)
    print('Clinvar output')
    display(clinvar_file.head(2))
    clinvar_file['snp_pos1'] = 'chr'+clinvar_file["#CHROM"].astype(str) +':'+ clinvar_file["POS"].astype(str)
    clinvar_file.drop(['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'Depth', 'Allele Frequency (%)'], axis=1, inplace=True)
    merged_cadd_clinvar= pd.merge(merged_dbNSFP1_cadd,clinvar_file, how='left', on='snp_pos1')
    merged_cadd_clinvar.drop(['Gene name_BED file_y'], axis = 1, inplace=True)
    merged_cadd_clinvar.rename(columns = {'Gene name_BED file_x':'Gene name_BED file'}, inplace = True)
    desired_column_order = ['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'Depth', 'Allele Frequency (%)', 'Gene name_BED file','SIFT4G_prediction', 'dbSNP', 'Amino acid position', 'Gene Name', 'Amino acid change', 'dbNSFP Amino acid change', 'REGION', 'Mutation type',  'HGVS nomenclature', 'Gene', 'Clinvar_accession_no', 'Clinvar_Protein_change', 'gnomAD_value', '1000_Genomes_value', 'ExAC_value', 'dbSNP_id', 'OMIM_id', 'Germline_classification', 'Somatic_clinical_impact', 'Clinvar_link', 'CADD_Consequence', 'Exon Number', 'Intron number', 'CADD_PHRED', 'CADD_Prediction', 'CADD_Grantham', 'snp_pos1']
    merged_cadd_clinvar = merged_cadd_clinvar[desired_column_order]
    print('merged_clinvar')
    display(merged_cadd_clinvar.head(2))
    
    #Integration of Cancer hotspot
    merged_clinvar_cancerhotspot = cancer_hotspot_annotation_for_whole_file(merged_cadd_clinvar)
    
    #Integration of Intogen
    merged_cancerhotspot_intogen_out=intogen_annotation(merged_clinvar_cancerhotspot)
    
       
    #Integration of OncoKB 
    try:
        oncokb_path = USER_INPUT_FOLDER_PATH+file_name+'_OncoKB_output.xlsx'
    except FileNotFoundError:
        print("OncoKB Annotations in progress..")
        return
    except:
        print("Other error")
        return
    oncokb_file = pd.read_excel(oncokb_path)
    print('OncoKb Output')
    display(oncokb_file.head(2))
    oncokb_file['snp_pos1'] = 'chr'+oncokb_file["chr_no"].astype(str) +':'+ oncokb_file["chr_pos"].astype(str)
    oncokb_file['OncoKB_link']="https://www.oncokb.org/hgvsg/"+oncokb_file["chr_no"].astype(str)+":g."+oncokb_file["chr_pos"].astype(str)+oncokb_file["ref"].astype(str)+'>'+oncokb_file["alt"].astype(str)+"?refGenome=GRCh38"
    oncokb_file.rename(columns = {'oncogenic':'OncoKB_oncogenic_status', 'mutation_effect_known_effect':'OncoKB_mutation_effect'}, inplace=True)
    desired_column_order = ['OncoKB_link', 'OncoKB_oncogenic_status', 'OncoKB_mutation_effect', 'snp_pos1']
    oncokb_file=oncokb_file[desired_column_order]
    oncokb_file['OncoKB_oncogenic_status'] = oncokb_file['OncoKB_oncogenic_status'].replace('Unknown', '')
    oncokb_file['OncoKB_mutation_effect'] = oncokb_file['OncoKB_mutation_effect'].replace('Unknown', '')
    merged_intogen_oncokb= pd.merge(merged_cancerhotspot_intogen_out,oncokb_file, how='left', on='snp_pos1')

    #Integrating CKB Core
    try:
        ckb_path = USER_INPUT_FOLDER_PATH+file_name+'_CKBCore_output.xlsx'
    except FileNotFoundError:
        print("CKB Core Annotations in progress..")
        return
    except:
        print("Other error")
        return
    ckb_df = pd.read_excel(ckb_path)
    print('CKb output')
    display(ckb_df.head(2))
    ckb_df['snp_pos1'] = 'chr'+ckb_df["#CHROM"].astype(str) +':'+ ckb_df["POS"].astype(str)
    ckb_df.drop(['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'ID', 'QUAL', 'INFO', 'FORMAT', 'HCC1187BL', 'HCC1187C', 'Gene name_BED file', 'Depth', 'Allele Frequency (%)', 'Gene', 'Clinvar_accession_no', 'Clinvar_Protein_change', 'gnomAD_value', '1000_Genomes_value', 'ExAC_value', 'dbSNP_id', 'OMIM_id', 'Germline_classification', 'Somatic_clinical_impact', 'Clinvar_link'], axis=1, inplace=True)
    merged_ckb= pd.merge(merged_intogen_oncokb,ckb_df, how='left', on='snp_pos1')
    # merged_ckb.drop(['snp_pos1'], axis =1, inplace=True)
    desired_order = ['CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'Depth', 'Allele Frequency (%)', 'Gene name_BED file','SIFT4G_prediction', 'dbSNP', 'Amino acid position',  'Gene Name', 'Amino acid change', 'dbNSFP Amino acid change', 'REGION',  'Mutation type', 'HGVS nomenclature', 'Gene', 'Clinvar_accession_no', 'Clinvar_Protein_change', 'gnomAD_value', '1000_Genomes_value', 'ExAC_value', 'dbSNP_id', 'OMIM_id', 'Germline_classification', 'Somatic_clinical_impact',  'Clinvar_link', 'CADD_Consequence', 'Exon Number', 'Intron number', 'CADD_PHRED', 'CADD_Prediction', 'CADD_Grantham', 'Cancer Hotspot_Gene mutation_Sample frequency', 'Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition', 'Cancer Hotspot_Mutation site_Sample frequency', 'Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition', 'Cancer Hotspot_Exact Mutation_Sample frequency', 'Intogen_Gene Mutation_Sample frequency', 'Intogen_Mutation Site_Sample frequency', 'Intogen_Exact Mutation_Sample frequency', 'Intogen_Known Driver', 'OncoKB_link', 'OncoKB_oncogenic_status', 'OncoKB_mutation_effect', 'NCBI Gene ID', 'CKB Core _Synonyms', 'CKB Core_GeneRole', 'CKB Core_Gene_Description']
    print('merged_ckb')
    display(merged_ckb.head(2))

    #integrating dbSNP
    try:
        dbsnp_path = USER_INPUT_FOLDER_PATH+file_name+'_dbSNP_output.xlsx'
    except FileNotFoundError:
        print("dbSNP Annotations in progress..")
        return
    except:
        print("Other error")
        return
    dbsnp_df = pd.read_excel(dbsnp_path)
    print('dbsnp output')
    display(dbsnp_df.head(2))
    dbsnp_df['snp_pos1'] = 'chr'+dbsnp_df["#CHROM"].astype(str) +':'+ dbsnp_df["POS"].astype(str)
    dbsnp_df.drop(['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'ID', 'QUAL', 'INFO', 'FORMAT', 'HCC1187BL', 'HCC1187C', 'Gene name_BED file', 'Depth', 'Allele Frequency (%)'], axis=1, inplace=True)
    merged_dbsnp= pd.merge(merged_ckb,dbsnp_df, how='left', on='snp_pos1')
    merged_dbsnp.drop(['snp_pos1'], axis =1, inplace=True)
    desired_order = ['#CHROM', 'POS', 'REF', 'ALT', 'FILTER', 'Depth', 'Allele Frequency (%)', 'Gene name_BED file','SIFT4G_prediction', 'dbSNP', 'dbSNP_rs_id','Amino acid position',  'Gene Name', 'Amino acid change', 'dbNSFP Amino acid change', 'REGION',  'Mutation type', 'HGVS nomenclature', 'Gene', 'Clinvar_accession_no', 'Clinvar_Protein_change', 'gnomAD_value',"gnomAD_value_dbSNP", '1000_Genomes_value', 'ExAC_value', 'dbSNP_id', 'OMIM_id', 'Germline_classification', 'Somatic_clinical_impact',  'Clinvar_link', 'CADD_Consequence', 'Exon Number', 'Intron number', 'CADD_PHRED', 'CADD_Prediction', 'CADD_Grantham', 'Cancer Hotspot_Gene mutation_Sample frequency', 'Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition', 'Cancer Hotspot_Mutation site_Sample frequency', 'Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition', 'Cancer Hotspot_Exact Mutation_Sample frequency', 'Intogen_Gene Mutation_Sample frequency', 'Intogen_Mutation Site_Sample frequency', 'Intogen_Exact Mutation_Sample frequency', 'Intogen_Known Driver', 'OncoKB_link', 'OncoKB_oncogenic_status', 'OncoKB_mutation_effect', 'NCBI Gene ID', 'CKB Core _Synonyms', 'CKB Core_GeneRole', 'CKB Core_Gene_Description']
    merged_dbsnp=merged_dbsnp[desired_order]
    print("merged_dbsnp")
    display(merged_dbsnp.head(2))
    
    excel_file_path = USER_INPUT_FOLDER_PATH+input_filename+"_Display_Table.xlsx"
    merged_dbsnp.to_excel(excel_file_path, index=False)
    print(f"DataFrame saved to {excel_file_path}")
    display(merged_dbsnp.head(2))

#displayVariants('somatic_snv_and_indel_with_new_variants.vcf')
displayVariants(input_file_path)

Total Number of Variants: 176

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),snp_pos
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,"1,9665241"
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,"1,11216105"

SIFT Indel OUTPUT

,Coordinates,Gene ID,Transcript ID,Substitution Type,Region,Amino acid position change,Effect,Confidence Score,Classification Path,Nucleotide change,Amino acid change,Indel Location,Causes NMD,Repeat detected,Transcript visualization,Gene Name,Gene Desc,Protein Family ID,Protein Family Desc,Transcript Status,Protein Family Size,Ka/Ks (Mouse),Ka/Ks (Macaque),OMIM Disease,1000 Genomes
0,"8,92007467,92007468,1,-/",ENSG00000079102,ENST00000265814,NaN,INTRON,NaN,NaN,NaN,NaN,TAATT-a-AAAAA,NaN,31%,NaN,NaN,<---{}[]--[]--[]--[]--[]--[]--[]-*.-[]--[]--[]...,RUNX1T1,runt-related transcription factor 1; transloca...,ENSFM00250000001209,CBF MTG8,KNOWN,42.0,0.103279,0.418142,"RUNT-RELATED TRANSCRIPTION FACTOR 1, TRANSLOCA...",NaN
1,"7,55053312,55053323,1,-/",ENSG00000146648,ENST00000275493,NaN,INTRON,NaN,NaN,NaN,NaN,GGAGG-gtgcatctcta-GAAAT,NaN,2%,NaN,NaN,|---{}[]-.*-[]--[]--[]--[]--[]--[]--[]--[]--[]...,EGFR,epidermal growth factor receptor [Source:HGNC ...,ENSFM00410000138465,RECEPTOR TYROSINE KINASE ERBB PRECURSOR EC_2.7...,KNOWN,36.0,0.068909,0.040964,EPIDERMAL GROWTH FACTOR RECEPTOR; EGFR;;V-ERB-...,NaN

Merged SIFT Indel-------------

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),snp_pos,Gene Name,Amino acid position,Amino acid change,Mutation type,SIFT4G prediction,Region
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,"1,9665241",NaN,NaN,NaN,NaN,NaN,NaN
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,"1,11216105",NaN,NaN,NaN,NaN,NaN,NaN

SIFT 4G output

,CHROM,POS,REF_ALLELE,ALT_ALLELE,TRANSCRIPT_ID,GENE_ID,GENE_NAME,REGION,VARIANT_TYPE,REF_AMINO,ALT_AMINO,AMINO_POS,SIFT_SCORE,SIFT_MEDIAN,NUM_SEQS,dbSNP,SIFT_PREDICTION
0,chr2,208248389,G,A,ENST00000345146,ENSG00000138413,IDH1,CDS,NONSYNONYMOUS,R,C,132.0,0.000,3.22,397.0,rs121913499,DELETERIOUS
1,chr2,233772291,G,T,ENST00000373409,ENSG00000244474,UGT1A4,CDS,NONSYNONYMOUS,S,I,446.0,0.047,2.70,155.0,novel,DELETERIOUS

merged_SIFT4G

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),snp_pos,REGION,dbsnp,Gene_Name,Amino_acid_position,Amino_acid_change,Mutation_type,SIFT4G_prediction,HGVS nomenclature
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,"1,9665241",,,,,,,,
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,"1,11216105",,,,,,,,

dbNSFP output

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,#chr,pos(1-based),ref,alt,aaref,aaalt,rs_dbSNP,hg19_chr,hg19_pos(1-based),hg18_chr,hg18_pos(1-based),aapos,genename,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,Uniprot_acc,Uniprot_entry,HGVSc_ANNOVAR,HGVSp_ANNOVAR,HGVSc_snpEff,HGVSp_snpEff,HGVSc_VEP,HGVSp_VEP,APPRIS,GENCODE_basic,TSL,VEP_canonical,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,VindijiaNeandertal,ChagyrskayaNeandertal,SIFT_score,SIFT_converted_rankscore,SIFT_pred,SIFT4G_score,SIFT4G_converted_rankscore,SIFT4G_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_score,MutationAssessor_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,MetaRNN_score,MetaRNN_rankscore,MetaRNN_pred,M-CAP_score,M-CAP_rankscore,M-CAP_pred,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,MVP_score,MVP_rankscore,gMVP_score,gMVP_rankscore,MPC_score,MPC_rankscore,PrimateAI_score,PrimateAI_rankscore,PrimateAI_pred,DEOGEN2_score,DEOGEN2_rankscore,DEOGEN2_pred,BayesDel_addAF_score,BayesDel_addAF_rankscore,BayesDel_addAF_pred,BayesDel_noAF_score,BayesDel_noAF_rankscore,BayesDel_noAF_pred,LIST-S2_score,LIST-S2_rankscore,LIST-S2_pred,VARITY_R_score,VARITY_R_rankscore,VARITY_ER_score,VARITY_ER_rankscore,VARITY_R_LOO_score,VARITY_R_LOO_rankscore,VARITY_ER_LOO_score,VARITY_ER_LOO_rankscore,ESM1b_score,ESM1b_rankscore,ESM1b_pred,EVE_score,EVE_rankscore,EVE_Class10_pred,EVE_Class20_pred,EVE_Class25_pred,EVE_Class30_pred,EVE_Class40_pred,EVE_Class50_pred,EVE_Class60_pred,EVE_Class70_pred,EVE_Class75_pred,EVE_Class80_pred,EVE_Class90_pred,AlphaMissense_score,AlphaMissense_rankscore,AlphaMissense_pred,Aloft_Fraction_transcripts_affected,Aloft_prob_Tolerant,Aloft_prob_Recessive,Aloft_prob_Dominant,Aloft_pred,Aloft_Confidence,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,fathmm-XF_coding_score,fathmm-XF_coding_rankscore,fathmm-XF_coding_pred,Eigen-raw_coding,Eigen-raw_coding_rankscore,Eigen-phred_coding,Eigen-PC-raw_coding,Eigen-PC-raw_coding_rankscore,Eigen-PC-phred_coding,integrated_fitCons_score,integrated_fitCons_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP470way_mammalian,phyloP470way_mammalian_rankscore,phyloP17way_primate,phyloP17way_primate_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons470way_mammalian,phastCons470way_mammalian_rankscore,phastCons17way_primate,phastCons17way_primate_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,bStatistic,bStatistic_converted_rankscore,1000Gp3_AC,1000Gp3_AF,1000Gp3_AFR_AC,1000Gp3_AFR_AF,1000Gp3_EUR_AC,1000Gp3_EUR_AF,1000Gp3_AMR_AC,1000Gp3_AMR_AF,1000Gp3_EAS_AC,1000Gp3_EAS_AF,1000Gp3_SAS_AC,1000Gp3_SAS_AF,TWINSUK_AC,TWINSUK_AF,ALSPAC_AC,ALSPAC_AF,UK10K_AC,UK10K_AF,ESP6500_AA_AC,ESP6500_AA_AF,ESP6500_EA_AC,ESP6500_EA_AF,ExAC_AC,ExAC_AF,ExAC_Adj_AC,ExAC_Adj_AF,ExAC_AFR_AC,ExAC_AFR_AF,ExAC_AMR_AC,ExAC_AMR_AF,ExAC_EAS_AC,ExAC_EAS_AF,ExAC_FIN_AC,ExAC_FIN_AF,ExAC_NFE_AC,ExAC_NFE_AF,ExAC_SAS_AC,ExAC_SAS_AF,ExAC_nonTCGA_AC,ExAC_nonTCGA_AF,ExAC_nonTCGA_Adj_AC,ExAC_nonTCGA_Adj_AF,ExAC_nonTCGA_AFR_AC,ExAC_nonTCGA_AFR_AF,ExAC_nonTCGA_AMR_AC,ExAC_nonTCGA_AMR_AF,ExAC_nonTCGA_EAS_AC,ExAC_nonTCGA_EAS_AF,ExAC_nonTCGA_FIN_AC,ExAC_nonTCGA_FIN_AF,ExAC_nonTCGA_NFE_AC,ExAC_nonTCGA_NFE_AF,ExAC_nonTCGA_SAS_AC,ExAC_nonTCGA_SAS_AF,ExAC_nonpsych_AC,ExAC_nonpsych_AF,ExAC_nonpsych_Adj_AC,ExAC_nonpsych_Adj_AF,ExAC_nonpsych_AFR_AC,ExAC_nonpsych_AFR_AF,ExAC_nonpsych_AMR_AC,ExAC_nonpsych_AMR_AF,ExAC_nonpsych_EAS_AC,ExAC_nonpsych_EAS_AF,ExAC_nonpsych_FIN_AC,ExAC_nonpsych_FIN_AF,ExAC_nonpsych_NFE_AC,ExAC_nonpsych_NFE_AF,ExAC_nonpsych_SAS_AC,ExAC_nonpsych_SAS_AF,gnomAD_exomes_flag,gnomAD_exomes_AC,gnomAD_exomes_AN,gnomAD_exomes_AF,gnomAD_exomes_nhomalt,gnomAD_exomes_POPMAX_AC,gnomAD_exomes_POPMAX_AN,gnomAD_exomes_POPMAX_AF,gnomAD_exomes_POPMAX_nhomalt,gnomAD_exomes_AFR_AC,gnomAD_exomes_AFR_AN,gnomAD_exomes_AFR_AF,gnomAD_exomes_AFR_nhomalt,gnomAD_exomes_AMR_AC,gnomAD_exomes_AMR_AN,gnomAD_exomes_AMR_AF,gnomAD_exomes_AMR_nhomalt,gnomAD_exomes_ASJ_AC,gnomAD_exomes_ASJ_AN,gnomAD_exomes_ASJ_AF,gnomAD_exomes_ASJ_nhomalt,gnomAD_exomes_EAS_AC,gnomAD_exomes_EAS_AN,gnomAD_exomes_EAS_AF,gnomAD_exomes_EAS_nhomalt,gnomAD_exomes_FIN_AC,gnomAD_exomes_FIN_AN,gnomAD_exomes_FIN_AF,gnomAD_exomes_FIN_nhomalt,gnomAD_exomes_MID_AC,gnomAD_exomes_MID_AN,gnomAD_exomes_MID_AF,gnomAD_exomes_MID_nhomalt,gnomAD_exomes_NFE_AC,gnomAD_exomes_NFE_AN,gnomAD_exomes_NFE_AF,gnomAD_exomes_NFE_nhomalt,gnomAD_exomes_SAS_AC,gnomAD_exomes_SAS_AN,gnomAD_exomes_SAS_AF,gnomAD_exomes_SAS_nhomalt,gnomAD_exomes_non_ukb_AC,gnomAD_exomes_non_ukb_AN,gnomAD_exomes_non_ukb_AF,gnomAD_exomes_non_ukb_nhomalt,gnomAD_exomes_non_ukb_AFR_AC,gnomAD_exomes_non_ukb_AFR_AN,gnomAD_exomes_non_ukb_AFR_AF,gnomAD_exomes_non_ukb_AFR_nhomalt,gnomAD_exomes_non_ukb_AMR_AC,gnomAD_exomes_non_ukb_AMR_AN,gnomAD_exomes_non_ukb_AMR_AF,gnomAD_exomes_non_ukb_AMR_nhomalt,gnomAD_exomes_non_ukb_ASJ_AC,gnomAD_exomes_non_ukb_ASJ_AN,gnomAD_exomes_non_ukb_ASJ_AF,gnomAD_exomes_non_ukb_ASJ_nhomalt,gnomAD_exomes_non_ukb_EAS_AC,gnomAD_exomes_non_ukb_EAS_AN,gnomAD_exomes_non_ukb_EAS_AF,gnomAD_exomes_non_ukb_EAS_nhomalt,gnomAD_exomes_non_ukb_FIN_AC,gnomAD_exomes_non_ukb_FIN_AN,gnomAD_exomes_non_ukb_FIN_AF,gnomAD_exomes_non_ukb_FIN_nhomalt,gnomAD_exomes_non_ukb_MID_AC,gnomAD_exomes_non_ukb_MID_AN,gnomAD_exomes_non_ukb_MID_AF,gnomAD_exomes_non_ukb_MID_nhomalt,gnomAD_exomes_non_ukb_NFE_AC,gnomAD_exomes_non_ukb_NFE_AN,gnomAD_exomes_non_ukb_NFE_AF,gnomAD_exomes_non_ukb_NFE_nhomalt,gnomAD_exomes_non_ukb_SAS_AC,gnomAD_exomes_non_ukb_SAS_AN,gnomAD_exomes_non_ukb_SAS_AF,gnomAD_exomes_non_ukb_SAS_nhomalt,gnomAD_genomes_flag,gnomAD_genomes_AC,gnomAD_genomes_AN,gnomAD_genomes_AF,gnomAD_genomes_nhomalt,gnomAD_genomes_POPMAX_AC,gnomAD_genomes_POPMAX_AN,gnomAD_genomes_POPMAX_AF,gnomAD_genomes_POPMAX_nhomalt,gnomAD_genomes_AFR_AC,gnomAD_genomes_AFR_AN,gnomAD_genomes_AFR_AF,gnomAD_genomes_AFR_nhomalt,gnomAD_genomes_AMI_AC,gnomAD_genomes_AMI_AN,gnomAD_genomes_AMI_AF,gnomAD_genomes_AMI_nhomalt,gnomAD_genomes_AMR_AC,gnomAD_genomes_AMR_AN,gnomAD_genomes_AMR_AF,gnomAD_genomes_AMR_nhomalt,gnomAD_genomes_ASJ_AC,gnomAD_genomes_ASJ_AN,gnomAD_genomes_ASJ_AF,gnomAD_genomes_ASJ_nhomalt,gnomAD_genomes_EAS_AC,gnomAD_genomes_EAS_AN,gnomAD_genomes_EAS_AF,gnomAD_genomes_EAS_nhomalt,gnomAD_genomes_FIN_AC,gnomAD_genomes_FIN_AN,gnomAD_genomes_FIN_AF,gnomAD_genomes_FIN_nhomalt,gnomAD_genomes_MID_AC,gnomAD_genomes_MID_AN,gnomAD_genomes_MID_AF,gnomAD_genomes_MID_nhomalt,gnomAD_genomes_NFE_AC,gnomAD_genomes_NFE_AN,gnomAD_genomes_NFE_AF,gnomAD_genomes_NFE_nhomalt,gnomAD_genomes_SAS_AC,gnomAD_genomes_SAS_AN,gnomAD_genomes_SAS_AF,gnomAD_genomes_SAS_nhomalt,ALFA_European_AC,ALFA_European_AN,ALFA_European_AF,ALFA_African_Others_AC,ALFA_African_Others_AN,ALFA_African_Others_AF,ALFA_East_Asian_AC,ALFA_East_Asian_AN,ALFA_East_Asian_AF,ALFA_African_American_AC,ALFA_African_American_AN,ALFA_African_American_AF,ALFA_Latin_American_1_AC,ALFA_Latin_American_1_AN,ALFA_Latin_American_1_AF,ALFA_Latin_American_2_AC,ALFA_Latin_American_2_AN,ALFA_Latin_American_2_AF,ALFA_Other_Asian_AC,ALFA_Other_Asian_AN,ALFA_Other_Asian_AF,ALFA_South_Asian_AC,ALFA_South_Asian_AN,ALFA_South_Asian_AF,ALFA_Other_AC,ALFA_Other_AN,ALFA_Other_AF,ALFA_African_AC,ALFA_African_AN,ALFA_African_AF,ALFA_Asian_AC,ALFA_Asian_AN,ALFA_Asian_AF,ALFA_Total_AC,ALFA_Total_AN,ALFA_Total_AF,clinvar_id,clinvar_clnsig,clinvar_trait,clinvar_review,clinvar_hgvs,clinvar_var_source,clinvar_MedGen_id,clinvar_OMIM_id,clinvar_Orphanet_id,Interpro_domain,GTEx_V8_eQTL_gene,GTEx_V8_eQTL_tissue,GTEx_V8_sQTL_gene,GTEx_V8_sQTL_tissue,eQTLGen_snp_id,eQTLGen_gene_id,eQTLGen_gene_symbol,eQTLGen_cis_or_trans,Geuvadis_eQTL_target_gene,Gene_old_names,Gene_other_names,Uniprot_acc(HGNC/Uniprot),Uniprot_id(HGNC/Uniprot),Entrez_gene_id,CCDS_id,Refseq_id,ucsc_id,MIM_id,OMIM_id,Gene_full_name,Pathway(Uniprot),Pathway(BioCarta)_short,Pathway(BioCarta)_full,Pathway(ConsensusPathDB),Pathway(KEGG)_id,Pathway(KEGG)_full,Function_description,Disease_description,MIM_phenotype_id,MIM_disease,Orphanet_disorder_id,Orphanet_disorder,Orphanet_association_type,Trait_association(GWAS),HPO_id,HPO_name,GO_biological_process,GO_cellular_component,GO_molecular_function,Tissue_specificity(Uniprot),Expression(egenetics),Expression(GNF/Atlas),Interactions(IntAct),Interactions(BioGRID),Interactions(ConsensusPathDB),P(HI),HIPred_score,HIPred,GHIS,P(rec),Known_rec_info,RVIS_EVS,RVIS_percentile_EVS,LoF-FDR_ExAC,RVIS_ExAC,RVIS_percentile_ExAC,ExAC_pLI,ExAC_pRec,ExAC_pNull,ExAC_nonTCGA_pLI,ExAC_nonTCGA_pRec,ExAC_nonTCGA_pNull,ExAC_nonpsych_pLI,ExAC_nonpsych_pRec,ExAC_nonpsych_pNull,gnomAD_pLI,gnomAD_pRec,gnomAD_pNull,ExAC_del.score,ExAC_dup.score,ExAC_cnv.score,ExAC_cnv_flag,GDI,GDI-Phred,Gene damage prediction (all disease-causing genes),Gene damage prediction (all Mendelian disease-causing genes),Gene damage prediction (Mendelian AD disease-causing genes),Gene damage prediction (Mendelian AR disease-causing genes),Gene damage prediction (all PID disease-causing genes),Gene damage prediction (PID AD disease-causing genes),Gene damage prediction (PID AR disease-causing genes),Gene damage prediction (all cancer disease-causing genes),Gene damage prediction (cancer recessive disease-causing genes),Gene damage prediction (cancer dominant disease-causing genes),LoFtool_score,SORVA_LOF_MAF0.005_HetOrHom,SORVA_LOF_MAF0.005_HomOrCompoundHet,SORVA_LOF_MAF0.001_HetOrHom,SORVA_LOF_MAF0.001_HomOrCompoundHet,SORVA_LOForMissense_MAF0.005_HetOrHom,SORVA_LOForMissense_MAF0.005_HomOrCompoundHet,SORVA_LOForMissense_MAF0.001_HetOrHom,SORVA_LOForMissense_MAF0.001_HomOrCompoundHet,Essential_gene,Essential_gene_CRISPR,Essential_gene_CRISPR2,Essential_gene_gene-trap,Gene_indispensability_score,Gene_indispensability_pred,MGI_mouse_gene,MGI_mouse_phenotype,ZFIN_zebrafish_gene,ZFIN_zebrafish_structure,ZFIN_zebrafish_phenotype_quality,ZFIN_zebrafish_phenotype_tag
0,chr17,7673776,.,G,A,.,PASS,DP=116;MQ=195.08;FractionInformativeReads=1.002,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:40,0:0.06:19,0:21,0:40:.:.","0/1:92.37:41,35:0.461:18,14:23,21:76:13,28,14,...",TP53,17,7673776,G,A,R,W,rs28934574,17,7577094,17,7517819,282;150;150;150;123;123;123;243;282;243;282;28...,TP53;TP53;TP53;TP53;TP53;TP53;TP53;TP53;TP53;T...,ENSG00000141510;ENSG00000141510;ENSG0000014151...,ENST00000359597;ENST00000504290;ENST0000051038...,ENSP00000352610;ENSP00000484409;ENSP0000047849...,J3KP33;P04637-9;P04637-8;P04637-7;A0A087X1Q1;A...,J3KP33_HUMAN;P53_HUMAN;P53_HUMAN;P53_HUMAN;A0A...,c.844C>T;c.448C>T;c.448C>T;c.448C>T;c.367C>T;c...,p.R282W;p.R150W;p.R150W;p.R150W;p.R123W;p.R123...,c.844C>T;c.448C>T;c.448C>T;c.448C>T;c.367C>T;c...,p.Arg282Trp;p.Arg150Trp;p.Arg150Trp;p.Arg150Tr...,c.844C>T;c.448C>T;c.448C>T;c.448C>T;c.367C>T;c...,p.Arg282Trp;p.Arg150Trp;p.Arg150Trp;p.Arg150Tr...,.;.;.;.;.;.;.;.;principal2;.;.;.;.;.;.;princip...,Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;Y;.,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;5;4,.;.;.;.;.;.;.;.;YES;.;.;.;.;.;.;.;.;.;.,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-,CGG;CGG;CGG;CGG;CGG;CGG;CGG;CGG;CGG;CGG;CGG;CG...,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1,2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2,G,G/G,G/G,G/G,G/G,0.002;.;.;.;.;.;.;.;0.002;.;.;0.002;0.002;.;.;...,0.72154,D;.;.;.;.;.;.;.;D;.;.;D;D;.;.;D;.;.;D,0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0....,0.92824,D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D,0.000000,0.84330,D,0.000000,0.999999;0.999999;0.999999;0.999999;0.999999;1,0.81001,A;A;A;A;A;A,simple_aae;simple_aae;simple_aae;simple_aae;si...,R282W;R282W;R282W;R282W;R282W;.,.;.;.;.;.;.;.;.;3.145;.;3.145;3.145;3.145;.;.;...,0.88303,.;.;.;.;.;.;.;.;M;.;M;M;M;.;.;M;.;.;.,-7.34;.;.;.;.;.;.;.;-7.34;.;.;-7.34;-7.34;.;.;...,0.99868,D;.;.;.;.;.;.;.;D;.;.;D;D;.;.;D;.;.;D,-7.38;.;.;.;.;.;.;.;-7.65;.;.;-7.38;-7.38;.;.;...,0.95483,D;.;.;.;.;.;.;.;D;.;.;D;D;.;.;D;.;.;D,1.0192,0.97520,D,0.9922,0.99810,D,9,0.9585321;0.9585321;0.9585321;0.9585321;0.9585...,0.95237,D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D;D,0.675578,0.97303,D,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,0.980238935356;0.980238935356;0.980238935356;0...,0.98002,.;.;.;.;.;.;.;.;0.8391295158354916;.;.;.;.;.;....,0.83872,.;.;.;.;.;.;.;.;0.392008185795;.;.;.;.;.;.;.;....,0.40396,0.640371799469,0.58617,T,0.845699;.;.;.;.;0.269245;0.297706;.;0.995057;...,0.99989,D;.;.;.;.;T;T;.;D;.;.;.;.;.;.;D;.;.;.,0.542691,0.95507,D,0.541762,0.95440,D,0.915408;0.915408;0.915408;0.915408;0.913909;0...,0.69895,D;D;D;D;D;D;D;.;.;.;D;D;.;D;D;D;D;D;D,.;.;.;.;.;.;.;.;0.90636075;.;.;.;.;.;.;0.90636...,0.91958,.;.;.;.;.;.;.;.;0.7978396;.;.;.;.;.;.;0.797839...,0.88134,.;.;.;.;.;.;.;.;0.89165527;.;.;.;.;.;.;0.89165...,0.90650,.;.;.;.;.;.;.;.;0.85779256;.;.;.;.;.;.;0.85779...,0.92030,.;-11.659;-11.549;-11.977;.;.;.;-12.18;-11.739...,0.85717,.;D;D;D;.;.;.;D;D;D;D;D;D;D;D;D;D;.;.,.;.;.;.;.;.;.;.;0.9168720303468678;.;.;.;.;.;....,0.96296,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,.;.;.;.;.;.;.;.;P;.;.;.;.;.;.;P;.;.;.,0.9469;0.7469;0.7409;0.8216;0.8522;0.8042;0.77...,0.86586,P;P;P;P;P;P;P;.;P;.;.;P;P;P;P;P;P;P;P,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;,0.998919,0.96589,0.98673,0.85416,D,AEFGBI,0.831851,0.75033,D,0.395382723831395,0.61171,4.31469,0.221923140594956,0.51065,3.292387,0.722319,0.85440,0,0.702456,0.74545,0,0.724815,0.87919,0,0.735409,0.98432,0,4.75,1.49,0.21966,4.023,0.56921,6.503,0.55788,0.672,0.70159,1.0,0.71638,1.0,0.68203,0.997,0.79791,0.0:0.1376:0.5833:0.2792,8.7508,0.33774,432,0.80690,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,0,0.0,2,2.3255813953488373E-4,2,1.647e-05,2,1.659e-05,0,0,0,0,0,0,0,0,2,3.014e-05,0,0,1,9.415e-06,1,9.484e-06,0,0,0,0,0,0,0,0,1,1.850e-05,0,0,2,2.204e-05,2,2.219e-05,0,0,0,0,0,0,0,0,2,4.769e-05,0,0,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,1,152016,6.578250e-06,0,1,68022,1.470110e-05,0,0,41386,0.000000e+00,0,0,912,0.000000e+00,0,0,15254,0.000000e+00,0,0,3468,0.000000e+00,0,0,5164,0.000000e+00,0,0,10584,0.000000e+00,0,0,316,0.000000e+00,0,1,68022,1.470110e-05,0,0,4826,0.000000e+00,0,1,22944,4.3584379358437934E-5,0,8,0,0,26,0,0,606,0,0,354,0,0,18,0,0,30,0,0,0,0,1,6360,1.5723270440251572E-4,0,614,0,0,56,0,2,30346,6.590654451987082E-5,12364,Pathogenic/Likely_pathogenic,Prostate_adenocarcinoma|Malignant_neoplasm_of_...,"criteria_provided,_multiple_submitters,_no_con...",NC_000017.11:g.7673776G>A,ClinGen:CA000454|OMIM:191170.0018|UniProtKB:P0...,C0007112|C0153574|C3661900|C0279663|C0278701|C...,114500|114550|167000|PS151623|605074|151623|27...,70482|140162|88673|547|524|47044|251589|251607...,"p53, DNA-binding domain|p53, DNA-binding domai...",.,.,.,.,.,.,.,.,.,.,p53;LFS1,P04637,P53_HUMAN,7157,CCDS11118;CCDS45605;CCDS45606;CCDS73963;CCDS73...,NM_000546,uc060aur.1,191170,191170,tumor protein p53,.,chemicalPathway;atmPathway;btg2Pathway;g1Pathw...,Apoptotic Signaling in Response to DNA Damage;...,"Fluoropyrimidine Pathway, Pharmacodynamics;PI3...",hsa04010;hsa04110;hsa04115;hsa04210;hsa04310;h...,MAPK signaling pathway;Cell cycle;p53 signalin...,FUNCTION: Acts as a tumor suppressor in many t...,DISEASE: Note=TP53 is found in increased amoun...,133239;151623;202300;211980;260500;275355;614740;,[MIM:133239]Esophageal cancer;[MIM:151623]Li-F...,524;251576;251579;251899;2807;210159;145;668;6...,Li-Fraumeni syndrome;Gliosarcoma;Giant cell gl...,Disease-causing germline mutation(s) in;Biomar...,Uterine fibroids[30194396];Basal cell carcinom...,HP:0001428;HP:0000006;HP:0001425;HP:0003002;HP...,Somatic mutation;Autosomal dominant inheritanc...,negative regulation of transcription by RNA po...,nuclear chromatin;nucleus;nucleoplasm;transcri...,RNA polymerase II proximal promoter sequence-s...,Ubiquitous. Isoforms are expressed in a wide r...,thymus;epididymis;tongue;skin;stomach;testis;l...,white blood cells;superior cervical ganglion;a...,414,1051,4628,0.99999,0.831385493278503,Y,0.599240746,0.99980,.,-0.25,35.99,0.008590594,-0.1111262,42.39503644,0.91222295333147,0.0877503280810861,2.6718587444359e-05,0.971650426065643,0.0283419013333493,7.67260100730332e-06,0.860627362894222,0.13926351971534,0.000109117390438318,8.0950e-01,1.8611e-01,4.3920e-03,0.222886025110909,-0.406454992014386,-0.196655082882549,N,15.3263,0.55115,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,9.65E-04,0.0,0.0,0.0,0.0,0.010782747603833865,0.0,0.00718849840255591,0.0,E,N,S,N,1,E,Trp53,behavior/neurological phenotype (the observabl...,tp53,nucleate erythrocyte,immature,abnormal

merged_dbNSFP3

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,snp_pos,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,snp_pos1
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,"1,9665241",,,NaN,nan,,,,nan,,chr1:9665241
1,1,243727332,T,G,PASS,156,0.0,AKT3,"1,243727332",,,NaN,nan,,,,nan,,chr1:243727332

CADD output

,Chrom,Position,Ref,Alt,AnnoType,Aparent2,CCDS,CDSpos,ConsDetail,ConsScore,Consequence,CpG,Dist2Mutation,Domain,Dst2SplType,Dst2Splice,EncodeDNase-max,EncodeDNase-sum,EncodeH2AFZ-max,EncodeH2AFZ-sum,EncodeH3K27ac-max,EncodeH3K27ac-sum,EncodeH3K27me3-max,EncodeH3K27me3-sum,EncodeH3K36me3-max,EncodeH3K36me3-sum,EncodeH3K4me1-max,EncodeH3K4me1-sum,EncodeH3K4me2-max,EncodeH3K4me2-sum,EncodeH3K4me3-max,EncodeH3K4me3-sum,EncodeH3K79me2-max,EncodeH3K79me2-sum,EncodeH3K9ac-max,EncodeH3K9ac-sum,EncodeH3K9me3-max,EncodeH3K9me3-sum,EncodeH4K20me1-max,EncodeH4K20me1-sum,EncodetotalRNA-max,EncodetotalRNA-sum,EnsembleRegulatoryFeature,EsmScoreFrameshift,EsmScoreInFrame,EsmScoreMissense,Exon,FeatureID,Freq10000bp,Freq1000bp,Freq100bp,GC,GeneID,GeneName,GerpN,GerpRS,GerpRSpval,GerpS,Grantham,Intron,Length,MMSp_acceptor,MMSp_acceptorIntron,MMSp_donor,MMSp_donorIntron,MMSp_exon,PHRED,PolyPhenCat,PolyPhenVal,Pos,Rare10000bp,Rare1000bp,Rare100bp,RawScore,RegSeq0,RegSeq1,RegSeq2,RegSeq3,RegSeq4,RegSeq5,RegSeq6,RegSeq7,RemapOverlapCL,RemapOverlapTF,Roulette-AR,Roulette-FILTER,Roulette-MR,SIFTcat,SIFTval,Sngl10000bp,Sngl1000bp,Sngl100bp,SpliceAI-acc-gain,SpliceAI-acc-loss,SpliceAI-don-gain,SpliceAI-don-loss,Type,ZooPriPhyloP,ZooRoCC,ZooUCE,ZooVerPhyloP,bStatistic,cDNApos,cHmm_E1,cHmm_E10,cHmm_E11,cHmm_E12,cHmm_E13,cHmm_E14,cHmm_E15,cHmm_E16,cHmm_E17,cHmm_E18,cHmm_E19,cHmm_E2,cHmm_E20,cHmm_E21,cHmm_E22,cHmm_E23,cHmm_E24,cHmm_E25,cHmm_E3,cHmm_E4,cHmm_E5,cHmm_E6,cHmm_E7,cHmm_E8,cHmm_E9,dbscSNV-ada_score,dbscSNV-rf_score,mamPhCons,mamPhyloP,minDistTSE,minDistTSS,mirSVR-Aln,mirSVR-E,mirSVR-Score,motifDist,motifECount,motifEHIPos,motifEName,motifEScoreChng,nAA,oAA,priPhCons,priPhyloP,protPos,relCDSpos,relProtPos,relcDNApos,tOverlapMotifs,targetScan,verPhCons,verPhyloP
0,1,9665241,A,G,Transcript,NaN,CCDS104.1,NaN,intron,2,INTRONIC,0.0,18,NaN,NaN,NaN,0.05,0.21,1.28,6.03,1.98,6.4,1.85,10.87,5.02,15.8,1.61,7.19,1.91,4.87,1.4,4.93,41.01,61.15,1.53,5.32,1.71,3.11,20.81,39.96,0.01,0.01,NaN,NaN,NaN,NaN,NaN,ENST00000377346,17,0,0.0,0.371,ENSG00000171608,PIK3CD,0.0432,NaN,NaN,0.0432,NaN,1/23,0,NaN,NaN,NaN,NaN,NaN,3.331,NaN,NaN,9665241,66,5,2.0,0.305346,0.003046,0.002875,0.000345,0.000976,0.00011,0.001194,0.002384,-0.007361,NaN,NaN,NaN,low,0.236,NaN,NaN,1312,116,14.0,0.0,0.0,0.0,0.0,SNV,0.006,NaN,NaN,0.333,774,NaN,0,2,2,0,0,1,18,0,0,0,0,0,0,9,2,0,1,0,0,6,0,0,4,2,1,NaN,NaN,0.099,0.103,50314,13472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.099,0.104,NaN,NaN,NaN,NaN,NaN,NaN,0.099,0.103
1,1,9665241,A,G,Intergenic,NaN,NaN,NaN,upstream,1,UPSTREAM,0.0,18,NaN,NaN,NaN,0.05,0.21,1.28,6.03,1.98,6.4,1.85,10.87,5.02,15.8,1.61,7.19,1.91,4.87,1.4,4.93,41.01,61.15,1.53,5.32,1.71,3.11,20.81,39.96,0.01,0.01,NaN,NaN,NaN,NaN,NaN,ENST00000426570,17,0,0.0,0.371,ENSG00000233268,NaN,0.0432,NaN,NaN,0.0432,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,3.331,NaN,NaN,9665241,66,5,2.0,0.305346,0.003046,0.002875,0.000345,0.000976,0.00011,0.001194,0.002384,-0.007361,NaN,NaN,NaN,low,0.236,NaN,NaN,1312,116,14.0,NaN,NaN,NaN,NaN,SNV,0.006,NaN,NaN,0.333,774,NaN,0,2,2,0,0,1,18,0,0,0,0,0,0,9,2,0,1,0,0,6,0,0,4,2,1,NaN,NaN,0.099,0.103,50314,13472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.099,0.104,NaN,NaN,NaN,NaN,NaN,NaN,0.099,0.103

merged_CADD

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,snp_pos,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,snp_pos1,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Grantham,CADD_Prediction
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,"1,9665241",,,NaN,nan,,,,nan,,chr1:9665241,INTRONIC,NaN,1/23,3.331,NaN,Benign
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,"1,9665241",,,NaN,nan,,,,nan,,chr1:9665241,UPSTREAM,NaN,NaN,3.331,NaN,Benign

Clinvar output

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

merged_clinvar

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,snp_pos1
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,chr1:9665241
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,chr1:9665241

Fetching Cancer hotspot annotations....
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['S446I', 'nan', 'S177I', 'S445I', 'S442I', 'S444I']
Looking for matches for protein position :446 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :177 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :445 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :442 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :444 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['S446I', 'nan', 'S177I', 'S445I', 'S442I', 'S444I']
Looking for matches for protein position :446 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :177 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :445 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :442 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position :444 in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['R132C']
Looking for matches for protein position :132 in cancer hotspot database
132 is a match
List of matched sample numbers:[766]
766 mutation(s) at this position
['R132C']
Looking for matches for protein position :132 in cancer hotspot database
132 is a match
List of matched sample numbers:[766]
766 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
Looking for matches for protein position : in cancer hotspot database
List of matched sample numbers:[]
0 mutation(s) at this position
['', 'nan']
Looking for matches for protein position : in cancer hotspot database

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,snp_pos1,Cancer Hotspot_Gene mutation_Sample frequency,Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition,Cancer Hotspot_Mutation site_Sample frequency,Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition,Cancer Hotspot_Exact Mutation_Sample frequency,AA_change,Protein_position,Intogen_Ref_allele,Intogen_Alt_allele,Intogen_var_format
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,chr1:9665241,,,,,,"[, nan]","['', '']",A,G,1:9665241:A>G
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,chr1:9665241,,,,,,"[, nan]","['', '']",A,G,1:9665241:A>G
2,1,243727332,T,G,PASS,156,0.0,AKT3,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/2,4.61,Benign,NaN,chr1:243727332,,,,,,"[, nan]","['', '']",T,G,1:243727332:T>G
3,1,243727332,T,G,PASS,156,0.0,AKT3,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/13,4.61,Benign,NaN,chr1:243727332,,,,,,"[, nan]","['', '']",T,G,1:243727332:T>G
4,1,241318460,CT,C,PASS,200,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241318460,,,,,,"[, nan]","['', '']",T,-,1:241318460:T>-
5,1,241234485,CT,C,PASS,195,2.1999999999999997,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241234485,,,,,,"[, nan]","['', '']",T,-,1:241234485:T>-
6,1,241232136,C,T,PASS,206,0.0,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/18,7.746,Benign,NaN,chr1:241232136,,,,,,"[, nan]","['', '']",C,T,1:241232136:C>T
7,1,241128709,A,G,PASS,207,1.4000000000000001,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/18,3.134,Benign,NaN,chr1:241128709,,,,,,"[, nan]","['', '']",A,G,1:241128709:A>G
8,1,241128709,A,G,PASS,207,1.4000000000000001,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.134,Benign,NaN,chr1:241128709,,,,,,"[, nan]","['', '']",A,G,1:241128709:A>G
9,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.597,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
10,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.597,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
11,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.736,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
12,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.736,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
13,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.568,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
14,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.568,Benign,NaN,chr1:241094238,,,,,,"[, nan]","['', '']",-,AC,1:241094238:->AC
15,1,241087972,CTCTCTATA,C,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241087972,,,,,,"[, nan]","['', '']",TCTCTATA,-,1:241087972:TCTCTATA>-
16,1,241083225,CA,C,PASS,156,5.3,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241083225,,,,,,"[, nan]","['', '']",A,-,1:241083225:A>-
17,1,241058004,C,A,PASS,155,0.0,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.82,Benign,NaN,chr1:241058004,,,,,,"[, nan]","['', '']",C,A,1:241058004:C>A
18,1,240911986,CA,C,PASS,137,8.1,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:240911986,,,,,,"[, nan]","['', '']",A,-,1:240911986:A>-
19,1,193123292,A,G,PASS,211,0.0,CDC73,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,2.154,Benign,NaN,chr1:193123292,,,,,,"[, nan]","['', '']",A,G,1:193123292:A>G
20,1,193123292,A,G,PASS,211,0.0,CDC73,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.154,Benign,NaN,chr1:193123292,,,,,,"[, nan]","['', '']",A,G,1:193123292:A>G
21,1,179148318,G,A,PASS,176,0.0,ABL2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/11,1.465,Benign,NaN,chr1:179148318,,,,,,"[, nan]","['', '']",G,A,1:179148318:G>A
22,1,241126809,AT,A,PASS,207,7.000000000000001,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241126809,,,,,,"[, nan]","['', '']",T,-,1:241126809:T>-
23,1,162763185,AT,A,PASS,156,3.2,DDR2,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:162763185,,,,,,"[, nan]","['', '']",T,-,1:162763185:T>-
24,1,162772543,G,T,PASS,207,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.321,Benign,NaN,chr1:162772543,,,,,,"[, nan]","['', '']",G,T,1:162772543:G>T
25,1,162772543,G,T,PASS,207,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,13/17,1.321,Benign,NaN,chr1:162772543,,,,,,"[, nan]","['', '']",G,T,1:162772543:G>T
26,1,11216105,T,A,PASS,155,0.0,MTOR,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/57,1.825,Benign,NaN,chr1:11216105,,,,,,"[, nan]","['', '']",T,A,1:11216105:T>A
27,1,64931096,A,T,PASS,206,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/24,7.148,Benign,NaN,chr1:64931096,,,,,,"[, nan]","['', '']",A,T,1:64931096:A>T
28,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.562,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
29,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.562,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
30,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.46,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
31,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.46,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
32,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.467,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
33,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.467,Benign,NaN,chr1:64969201,,,,,,"[, nan]","['', '']",-,T,1:64969201:->T
34,1,97142697,T,G,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/22,11.29,Benign,NaN,chr1:97142697,,,,,,"[, nan]","['', '']",T,G,1:97142697:T>G
35,1,97142697,T,G,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/4,11.29,Benign,NaN,chr1:97142697,,,,,,"[, nan]","['', '']",T,G,1:97142697:T>G
36,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,13.84,Benign,NaN,chr1:65022230,,,,,,"[, nan]","['', '']",G,A,1:65022230:G>A
37,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,13.84,Benign,NaN,chr1:65022230,,,,,,"[, nan]","['', '']",G,A,1:65022230:G>A
38,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/25,13.84,Benign,NaN,chr1:65022230,,,,,,"[, nan]","['', '']",G,A,1:65022230:G>A
39,1,97371462,G,A,PASS,109,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,16/22,0.056,Benign,NaN,chr1:97371462,,,,,,"[, nan]","['', '']",G,A,1:97371462:G>A
40,1,97527794,GA,G,PASS,132,5.8999999999999995,DPYD,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:97527794,,,,,,"[, nan]","['', '']",A,-,1:97527794:A>-
41,1,156865995,A,G,PASS,238,0.0,NTRK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.992,Benign,NaN,chr1:156865995,,,,,,"[, nan]","['', '']",A,G,1:156865995:A>G
42,1,156865995,A,G,PASS,238,0.0,NTRK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/16,1.992,Benign,NaN,chr1:156865995,,,,,,"[, nan]","['', '']",A,G,1:156865995:A>G
43,1,162657625,A,T,PASS,183,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/17,0.036,Benign,NaN,chr1:162657625,,,,,,"[, nan]","['', '']",A,T,1:162657625:A>T
44,1,162696199,CT,C,PASS,190,5.4,DDR2,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:162696199,,,,,,"[, nan]","['', '']",T,-,1:162696199:T>-
45,1,97177779,T,A,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/4,1.742,Benign,NaN,chr1:97177779,,,,,,"[, nan]","['', '']",T,A,1:97177779:T>A
46,1,97177779,T,A,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/22,1.742,Benign,NaN,chr1:97177779,,,,,,"[, nan]","['', '']",T,A,1:97177779:T>A
47,2,233772291,G,T,PASS,124,0.0,UGT1A1,DELETERIOUS,novel,"446 445,446,444,177,442","UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1...",S446I,"S446I,S177I,S445I,S442I,S444I",CDS,NONSYNONYMOUS,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON_SYNONYMOUS,5/5,NaN,24.0,Deleterious,142.0,chr2:233772291,,,,,,"[S446I, nan, S177I, S445I, S442I, S444I]","['446', '', '177', '445', '442', '444']",G,T,2:233772291:G>T
48,2,233772291,G,T,PASS,124,0.0,UGT1A1,DELETERIOUS,novel,"446 445,446,444,177,442","UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1...",S446I,"S446I,S177I,S445I,S442I,S444I",CDS,NONSYNONYMOUS,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,24.0,Deleterious,NaN,chr2:233772291,,,,,,"[S446I, nan, S177I, S445I, S442I, S444I]","['446', '', '177', '445', '442', '444']",G,T,2:233772291:G>T
49,2,208248389,G,A,PASS,116,6.0,IDH1,DELETERIOUS,rs121913499,132 132,IDH1,R132C,R132C,CDS,NONSYNONYMOUS,,IDH1,VCV000375891,R132C,0.00001,NaN,NaN,121913499.0,,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,REGULATORY,NaN,NaN,31.0,Deleterious,NaN,chr2:208248389,766,"{'brain': 612, 'biliary_tract': 57, 'skin': 25...",{'132': 766},"{'132': {'brain': 612, 'biliary_tract': 57, 's...",{'R132C': 139},[R132C],['132'],G,A,2:208248389:G>A
50,2,208248389,G,A,PASS,116,6.0,IDH1,DELETERIOUS,rs121913499,132 132,IDH1,R132C,R132C,CDS,NONSYNONYMOUS,,IDH1,VCV000375891,R132C,0.00001,NaN,NaN,121913499.0,,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,NON_SYNONYMOUS,4/10,NaN,31.0,Deleterious,180.0,chr2:208248389,766,"{'brain': 612, 'biliary_tract': 57, 'skin': 25...",{'132': 766},"{'132': {'brain': 612, 'biliary_tract': 57, 's...",{'R132C': 139},[R132C],['132'],G,A,2:208248389:G>A
51,2,212538253,A,T,PASS,127,0.0,ERBB4,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,6.162,Benign,NaN,chr2:212538253,,,,,,"[, nan]","['', '']",A,T,2:212538253:A>T
52,2,212538253,A,T,PASS,127,0.0,ERBB4,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/27,6.162,Benign,NaN,chr2:212538253,,,,,,"[, nan]","['', '']",A,T,2:212538253:A>T
53,2,212322431,TA,T,PASS,137,0.0,ERBB4,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:212322431,,,,,,"[, nan]","['', '']",A,-,2:212322431:A>-
54,2,211677577,TA,T,PASS,97,0.0,ERBB4,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:211677577,,,,,,"[, nan]","['', '']",A,-,2:211677577:A>-
55,2,39096885,CA,C,PASS,120,5.1,SOS1,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:39096885,,,,,,"[, nan]","['', '']",A,-,2:39096885:A>-
56,2,29249631,T,C,PASS,123,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,12/28,0.492,Benign,NaN,chr2:29249631,,,,,,"[, nan]","['', '']",T,C,2:29249631:T>C
57,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.603,Benign,NaN,chr2:29705282,,,,,,"[, nan]","['', '']",-,TATATATATATATATAT,2:29705282:->TATATATATATATATAT
58,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.651,Benign,NaN,chr2:29705282,,,,,,"[, nan]","['', '']",-,TATATATATATATATAT,2:29705282:->TATATATATATATATAT
59,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.573,Benign,NaN,chr2:29705282,,,,,,"[, nan]","['', '']",-,TATATATATATATATAT,2:29705282:->TATATATATATATATAT
60,2,29394870,GT,G,PASS,135,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:29394870,,,,,,"[, nan]","['', '']",T,-,2:29394870:T>-
61,2,29266768,T,C,PASS,119,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,11/28,3.107,Benign,NaN,chr2:29266768,,,,,,"[, nan]","['', '']",T,C,2:29266768:T>C
62,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.713,Benign,NaN,chr2:29197299,,,,,,"[, nan]","['', '']",C,G,2:29197299:C>G
63,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,27/28,1.713,Benign,NaN,chr2:29197299,,,,,,"[, nan]","['', '']",C,G,2:29197299:C>G
64,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3PRIME_UTR,17/17,NaN,1.713,Benign,NaN,chr2:29197299,,,,,,"[, nan]","['', '']",C,G,2:29197299:C>G
65,2,29825713,GT,G,PASS,119,2.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:29825713,,,,,,"[, nan]","['', '']",T,-,2:29825713:T>-
66,3,179175710,AT,A,PASS,121,0.0,PIK3CA,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:179175710,,,,,,"[, nan]","['', '']",T,-,3:179175710:T>-
67,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,"[, nan]","['', '']",A,T,3:181714163:A>T
68,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,"[, nan]","['', '']",A,T,3:181714163:A>T
69,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3PRIME_UTR,1/1,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,"[, nan]","['', '']",A,T,3:181714163:A>T
70,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,7/10,9.667,Benign,NaN,chr3:181714163,,,,,,"[, nan]","['', '']",A,T,3:181714163:A>T
71,3,179218304,A,G,PASS,116,7.000000000000001,PIK3CA,DELETERIOUS,rs121913274,545 545,PIK3CA,E545G,E545G,CDS,NONSYNONYMOUS,,PIK3CA,VCV000013656,E545G,NaN,NaN,NaN,121913274.0,171834.0004,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,NON_SYNONYMOUS,10/21,NaN,29.5,Deleterious,98.0,chr3:179218304,2627,"{'breast': 884, 'bowel': 347, 'uterus': 282, '...",{'545': 633},"{'545': {'breast': 174, 'bowel': 97, 'bladder'...",{'E545G': 21},[E545G],['545'],A,G,3:179218304:A>G
72,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.49,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
73,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.49,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
74,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.374,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
75,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.374,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
76,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.599,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
77,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.599,Benign,NaN,chr3:169606408,,,,,,"[, nan]","['', '']",-,A,3:169606408:->A
78,3,169451252,GA,G,PASS,154,8.3,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:169451252,,,,,,"[, nan]","['', '']",A,-,3:169451252:A>-
79,3,169238554,CA,C,PASS,153,0.0,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:169238554,,,,,,"[, nan]","['', '']",A,-,3:169238554:A>-
80,3,69848060,T,C,PASS,107,0.0,MITF,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/9,0.512,Benign,NaN,chr3:69848060,,,,,,"[, nan]","['', '']",T,C,3:69848060:T>C
81,3,53600934,C,G,PASS,136,0.0,CACNA1D,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/47,0.195,Benign,NaN,chr3:53600934,,,,,,"[, nan]","['', '']",C,G,3:53600934:C>G
82,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,"Q261*,Q243*",CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,"[Q261*, Q243*, nan]","['261', '243', '']",G,A,3:52406255:G>A
83,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,"Q261*,Q243*",CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STOP_GAINED,9/17,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,"[Q261*, Q243*, nan]","['261', '243', '']",G,A,3:52406255:G>A
84,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,"Q261*,Q243*",CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,"[Q261*, Q243*, nan]","['261', '243', '']",G,A,3:52406255:G>A
85,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.022,Benign,NaN,chr3:169382849,,,,,,"[, nan]","['', '']",-,A,3:169382849:->A
86,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.868,Benign,NaN,chr3:169382849,,,,,,"[, nan]","['', '']",-,A,3:169382849:->A
87,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.193,Benign,NaN,chr3:169382849,,,,,,"[, nan]","['', '']",-,A,3:169382849:->A

<class 'list'>
No results for nan.
No results for nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
No results for UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1A1,UGT1A10,UGT1A6UGT1A4.
No results for UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1A1,UGT1A10,UGT1A6UGT1A4
<class 'list'>
Using cached data for gene: UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1A1,UGT1A10,UGT1A6UGT1A4
<class 'list'>
Number of mutated samples: 665
Known driver text: True
Distribution table for IDH1 extracted
132
Looking for matches for protein position :132 in intogen database
132 is a match
132 is a match
132 is a match
132 is a match
132 is a match
131-132 is a match
List of matched sample numbers:[476, 144, 30, 21, 16, 1]
688 mutation(s) at this position
Gene name:IDH1,mutation_site_freq:{'132': 688},exact_mutation_frequency:144
<class 'list'>
Using cached data for gene: IDH1
132
Looking for matches for protein position :132 in intogen database
132 is a match
132 is a match
132 is a match
132 is a match
132 is a match
131-132 is a match
List of matched sample numbers:[476, 144, 30, 21, 16, 1]
688 mutation(s) at this position
Gene name:IDH1,mutation_site_freq:{'132': 688},exact_mutation_frequency:144
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Number of mutated samples: 2,446
Known driver text: True
Distribution table for PIK3CA extracted
545
Looking for matches for protein position :545 in intogen database
545 is a match
545 is a match
545 is a match
545 is a match
545 is a match
545 is a match
545 is a match
List of matched sample numbers:[546, 31, 15, 15, 7, 4, 1]
619 mutation(s) at this position
Gene name:PIK3CA,mutation_site_freq:{'545': 619},exact_mutation_frequency:15
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Number of mutated samples: 198
Known driver text: True
Distribution table for BAP1 extracted
261
Looking for matches for protein position :261 in intogen database
259-261 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position
243
Looking for matches for protein position :243 in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
Gene name:BAP1,mutation_site_freq:{'261': 1},exact_mutation_frequency:
<class 'list'>
Using cached data for gene: BAP1
261
Looking for matches for protein position :261 in intogen database
259-261 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position
243
Looking for matches for protein position :243 in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
Gene name:BAP1,mutation_site_freq:{'261': 1},exact_mutation_frequency:
<class 'list'>
Using cached data for gene: BAP1
261
Looking for matches for protein position :261 in intogen database
259-261 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position
243
Looking for matches for protein position :243 in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
Gene name:BAP1,mutation_site_freq:{'261': 1},exact_mutation_frequency:
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Number of mutated samples: 9,039
Known driver text: True
Distribution table for TP53 extracted
136
Looking for matches for protein position :136 in intogen database
136 is a match
136 is a match
136 is a match
136 is a match
130-142 is a match
135-140 is a match
135-139 is a match
136-139 is a match
136-137 is a match
135-137 is a match
136-137 is a match
136 is a match
136 is a match
List of matched sample numbers:[25, 12, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
52 mutation(s) at this position
43
Looking for matches for protein position :43 in intogen database
43 is a match
43-45 is a match
36-45 is a match
43-44 is a match
43 is a match
43 is a match
?-43 is a match
List of matched sample numbers:[4, 1, 1, 1, 1, 1, 1]
10 mutation(s) at this position
175
Looking for matches for protein position :175 in intogen database
175 is a match
175 is a match
175 is a match
175-179 is a match
175 is a match
173-180 is a match
173-178 is a match
157-177 is a match
175-177 is a match
175 is a match
175 is a match
174-175 is a match
172-175 is a match
172-175 is a match
List of matched sample numbers:[417, 15, 4, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
450 mutation(s) at this position
16
Looking for matches for protein position :16 in intogen database
14-16 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position
Gene name:TP53,mutation_site_freq:{'136': 52, '43': 10, '175': 450, '16': 1},exact_mutation_frequency:417
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: TP53
51
Looking for matches for protein position :51 in intogen database
51 is a match
51 is a match
50-51 is a match
51-59 is a match
46-55 is a match
47-54 is a match
49-54 is a match
51-52 is a match
50-51 is a match
46-51 is a match
51 is a match
48-51 is a match
List of matched sample numbers:[7, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
20 mutation(s) at this position
12
Looking for matches for protein position :12 in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
Gene name:TP53,mutation_site_freq:{'51': 20},exact_mutation_frequency:7
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: TP53

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
123
Looking for matches for protein position :123 in intogen database
123-? is a match
123-125 is a match
123 is a match
121-123 is a match
123 is a match
122-123 is a match
122-123 is a match
122-123 is a match
List of matched sample numbers:[1, 1, 1, 1, 1, 1, 1, 1]
8 mutation(s) at this position
282
Looking for matches for protein position :282 in intogen database
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282-292 is a match
280-286 is a match
282-283 is a match
280-283 is a match
281-283 is a match
282-283 is a match
282-283 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
281-282 is a match
282 is a match
282 is a match
281-282 is a match
275-282 is a match
281-282 is a match
281-282 is a match
281-282 is a match
281-282 is a match
List of matched sample numbers:[226, 9, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
266 mutation(s) at this position
150
Looking for matches for protein position :150 in intogen database
150-154 is a match
149-165 is a match
142-151 is a match
150-153 is a match
149-153 is a match
144-152 is a match
150 is a match
148-150 is a match
List of matched sample numbers:[4, 2, 2, 1, 1, 1, 1, 1]
13 mutation(s) at this position
243
Looking for matches for protein position :243 in intogen database
241-246 is a match
243 is a match
237-249 is a match
242-246 is a match
234-244 is a match
238-243 is a match
243 is a match
240-243 is a match
239-243 is a match
236-243 is a match
List of matched sample numbers:[2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
12 mutation(s) at this position
Gene name:TP53,mutation_site_freq:{'123': 8, '282': 266, '150': 13, '243': 12},exact_mutation_frequency:226
<class 'list'>
Using cached data for gene: TP53

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
123
Looking for matches for protein position :123 in intogen database
123-? is a match
123-125 is a match
123 is a match
121-123 is a match
123 is a match
122-123 is a match
122-123 is a match
122-123 is a match
List of matched sample numbers:[1, 1, 1, 1, 1, 1, 1, 1]
8 mutation(s) at this position
282
Looking for matches for protein position :282 in intogen database
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282-292 is a match
280-286 is a match
282-283 is a match
280-283 is a match
281-283 is a match
282-283 is a match
282-283 is a match
282 is a match
282 is a match
282 is a match
282 is a match
282 is a match
281-282 is a match
282 is a match
282 is a match
281-282 is a match
275-282 is a match
281-282 is a match
281-282 is a match
281-282 is a match
281-282 is a match
List of matched sample numbers:[226, 9, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
266 mutation(s) at this position
150
Looking for matches for protein position :150 in intogen database
150-154 is a match
149-165 is a match
142-151 is a match
150-153 is a match
149-153 is a match
144-152 is a match
150 is a match
148-150 is a match
List of matched sample numbers:[4, 2, 2, 1, 1, 1, 1, 1]
13 mutation(s) at this position
243
Looking for matches for protein position :243 in intogen database
241-246 is a match
243 is a match
237-249 is a match
242-246 is a match
234-244 is a match
238-243 is a match
243 is a match
240-243 is a match
239-243 is a match
236-243 is a match
List of matched sample numbers:[2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
12 mutation(s) at this position
Gene name:TP53,mutation_site_freq:{'123': 8, '282': 266, '150': 13, '243': 12},exact_mutation_frequency:226
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Number of mutated samples: 552
Known driver text: True
Distribution table for SMAD4 extracted
397
Looking for matches for protein position :397 in intogen database
395-397 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position

Looking for matches for protein position : in intogen database
List of matched sample numbers:[]
0 mutation(s) at this position
301
Looking for matches for protein position :301 in intogen database
301-302 is a match
List of matched sample numbers:[1]
1 mutation(s) at this position
Gene name:SMAD4,mutation_site_freq:{'397': 1, '301': 1},exact_mutation_frequency:
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Using cached data for gene: nan
<class 'list'>
Number of mutated samples: 16
Known driver text: False
Distribution table for KMT2B extracted
764
Looking for matches for protein position :764 in intogen database
List of matched sample numbers:[]

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,snp_pos1,Cancer Hotspot_Gene mutation_Sample frequency,Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition,Cancer Hotspot_Mutation site_Sample frequency,Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition,Cancer Hotspot_Exact Mutation_Sample frequency,Intogen_Gene Mutation_Sample frequency,Intogen_Mutation Site_Sample frequency,Intogen_Exact Mutation_Sample frequency,Intogen_Known Driver
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,chr1:9665241,,,,,,None,None,None,None
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,chr1:9665241,,,,,,,None,None,
2,1,243727332,T,G,PASS,156,0.0,AKT3,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/2,4.61,Benign,NaN,chr1:243727332,,,,,,,None,None,
3,1,243727332,T,G,PASS,156,0.0,AKT3,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/13,4.61,Benign,NaN,chr1:243727332,,,,,,,None,None,
4,1,241318460,CT,C,PASS,200,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241318460,,,,,,,None,None,
5,1,241234485,CT,C,PASS,195,2.1999999999999997,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241234485,,,,,,,None,None,
6,1,241232136,C,T,PASS,206,0.0,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/18,7.746,Benign,NaN,chr1:241232136,,,,,,,None,None,
7,1,241128709,A,G,PASS,207,1.4000000000000001,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/18,3.134,Benign,NaN,chr1:241128709,,,,,,,None,None,
8,1,241128709,A,G,PASS,207,1.4000000000000001,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.134,Benign,NaN,chr1:241128709,,,,,,,None,None,
9,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.597,Benign,NaN,chr1:241094238,,,,,,,None,None,
10,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.597,Benign,NaN,chr1:241094238,,,,,,,None,None,
11,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.736,Benign,NaN,chr1:241094238,,,,,,,None,None,
12,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.736,Benign,NaN,chr1:241094238,,,,,,,None,None,
13,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.568,Benign,NaN,chr1:241094238,,,,,,,None,None,
14,1,241094238,A,AAC,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.568,Benign,NaN,chr1:241094238,,,,,,,None,None,
15,1,241087972,CTCTCTATA,C,PASS,147,0.0,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241087972,,,,,,,None,None,
16,1,241083225,CA,C,PASS,156,5.3,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241083225,,,,,,,None,None,
17,1,241058004,C,A,PASS,155,0.0,RGS7,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/18,1.82,Benign,NaN,chr1:241058004,,,,,,,None,None,
18,1,240911986,CA,C,PASS,137,8.1,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:240911986,,,,,,,None,None,
19,1,193123292,A,G,PASS,211,0.0,CDC73,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,2.154,Benign,NaN,chr1:193123292,,,,,,,None,None,
20,1,193123292,A,G,PASS,211,0.0,CDC73,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.154,Benign,NaN,chr1:193123292,,,,,,,None,None,
21,1,179148318,G,A,PASS,176,0.0,ABL2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/11,1.465,Benign,NaN,chr1:179148318,,,,,,,None,None,
22,1,241126809,AT,A,PASS,207,7.000000000000001,RGS7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:241126809,,,,,,,None,None,
23,1,162763185,AT,A,PASS,156,3.2,DDR2,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:162763185,,,,,,,None,None,
24,1,162772543,G,T,PASS,207,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.321,Benign,NaN,chr1:162772543,,,,,,,None,None,
25,1,162772543,G,T,PASS,207,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,13/17,1.321,Benign,NaN,chr1:162772543,,,,,,,None,None,
26,1,11216105,T,A,PASS,155,0.0,MTOR,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/57,1.825,Benign,NaN,chr1:11216105,,,,,,,None,None,
27,1,64931096,A,T,PASS,206,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/24,7.148,Benign,NaN,chr1:64931096,,,,,,,None,None,
28,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.562,Benign,NaN,chr1:64969201,,,,,,,None,None,
29,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.562,Benign,NaN,chr1:64969201,,,,,,,None,None,
30,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.46,Benign,NaN,chr1:64969201,,,,,,,None,None,
31,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.46,Benign,NaN,chr1:64969201,,,,,,,None,None,
32,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,0.467,Benign,NaN,chr1:64969201,,,,,,,None,None,
33,1,64969201,G,GT,PASS,210,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,0.467,Benign,NaN,chr1:64969201,,,,,,,None,None,
34,1,97142697,T,G,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/22,11.29,Benign,NaN,chr1:97142697,,,,,,,None,None,
35,1,97142697,T,G,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/4,11.29,Benign,NaN,chr1:97142697,,,,,,,None,None,
36,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,13.84,Benign,NaN,chr1:65022230,,,,,,,None,None,
37,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DOWNSTREAM,NaN,NaN,13.84,Benign,NaN,chr1:65022230,,,,,,,None,None,
38,1,65022230,G,A,PASS,243,0.0,JAK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/25,13.84,Benign,NaN,chr1:65022230,,,,,,,None,None,
39,1,97371462,G,A,PASS,109,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,16/22,0.056,Benign,NaN,chr1:97371462,,,,,,,None,None,
40,1,97527794,GA,G,PASS,132,5.8999999999999995,DPYD,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:97527794,,,,,,,None,None,
41,1,156865995,A,G,PASS,238,0.0,NTRK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.992,Benign,NaN,chr1:156865995,,,,,,,None,None,
42,1,156865995,A,G,PASS,238,0.0,NTRK1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/16,1.992,Benign,NaN,chr1:156865995,,,,,,,None,None,
43,1,162657625,A,T,PASS,183,0.0,DDR2,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/17,0.036,Benign,NaN,chr1:162657625,,,,,,,None,None,
44,1,162696199,CT,C,PASS,190,5.4,DDR2,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr1:162696199,,,,,,,None,None,
45,1,97177779,T,A,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/4,1.742,Benign,NaN,chr1:97177779,,,,,,,None,None,
46,1,97177779,T,A,PASS,116,0.0,DPYD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/22,1.742,Benign,NaN,chr1:97177779,,,,,,,None,None,
47,2,233772291,G,T,PASS,124,0.0,UGT1A1,DELETERIOUS,novel,"446 445,446,444,177,442","UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1...",S446I,S446I S177I S445I S442I S444I,CDS,NONSYNONYMOUS,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON_SYNONYMOUS,5/5,NaN,24.0,Deleterious,142.0,chr2:233772291,,,,,,None,None,None,None
48,2,233772291,G,T,PASS,124,0.0,UGT1A1,DELETERIOUS,novel,"446 445,446,444,177,442","UGT1A3,UGT1A8,UGT1A7,UGT1A5,UGT1A9,UGT1A4,UGT1...",S446I,S446I S177I S445I S442I S444I,CDS,NONSYNONYMOUS,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,24.0,Deleterious,NaN,chr2:233772291,,,,,,,None,None,
49,2,208248389,G,A,PASS,116,6.0,IDH1,DELETERIOUS,rs121913499,132 132,IDH1,R132C,R132C,CDS,NONSYNONYMOUS,,IDH1,VCV000375891,R132C,0.00001,NaN,NaN,121913499.0,,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,REGULATORY,NaN,NaN,31.0,Deleterious,NaN,chr2:208248389,766,"{'brain': 612, 'biliary_tract': 57, 'skin': 25...",{'132': 766},"{'132': {'brain': 612, 'biliary_tract': 57, 's...",{'R132C': 139},665,{'132': 688},144,True
50,2,208248389,G,A,PASS,116,6.0,IDH1,DELETERIOUS,rs121913499,132 132,IDH1,R132C,R132C,CDS,NONSYNONYMOUS,,IDH1,VCV000375891,R132C,0.00001,NaN,NaN,121913499.0,,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,NON_SYNONYMOUS,4/10,NaN,31.0,Deleterious,180.0,chr2:208248389,766,"{'brain': 612, 'biliary_tract': 57, 'skin': 25...",{'132': 766},"{'132': {'brain': 612, 'biliary_tract': 57, 's...",{'R132C': 139},665,{'132': 688},144,True
51,2,212538253,A,T,PASS,127,0.0,ERBB4,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,6.162,Benign,NaN,chr2:212538253,,,,,,,None,None,
52,2,212538253,A,T,PASS,127,0.0,ERBB4,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/27,6.162,Benign,NaN,chr2:212538253,,,,,,,None,None,
53,2,212322431,TA,T,PASS,137,0.0,ERBB4,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:212322431,,,,,,,None,None,
54,2,211677577,TA,T,PASS,97,0.0,ERBB4,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:211677577,,,,,,,None,None,
55,2,39096885,CA,C,PASS,120,5.1,SOS1,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:39096885,,,,,,,None,None,
56,2,29249631,T,C,PASS,123,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,12/28,0.492,Benign,NaN,chr2:29249631,,,,,,,None,None,
57,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.603,Benign,NaN,chr2:29705282,,,,,,,None,None,
58,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.651,Benign,NaN,chr2:29705282,,,,,,,None,None,
59,2,29705282,A,ATATATATATATATATAT,PASS,81,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/28,0.573,Benign,NaN,chr2:29705282,,,,,,,None,None,
60,2,29394870,GT,G,PASS,135,0.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:29394870,,,,,,,None,None,
61,2,29266768,T,C,PASS,119,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,11/28,3.107,Benign,NaN,chr2:29266768,,,,,,,None,None,
62,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.713,Benign,NaN,chr2:29197299,,,,,,,None,None,
63,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,27/28,1.713,Benign,NaN,chr2:29197299,,,,,,,None,None,
64,2,29197299,C,G,PASS,127,0.0,ALK,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3PRIME_UTR,17/17,NaN,1.713,Benign,NaN,chr2:29197299,,,,,,,None,None,
65,2,29825713,GT,G,PASS,119,2.0,ALK,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr2:29825713,,,,,,,None,None,
66,3,179175710,AT,A,PASS,121,0.0,PIK3CA,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:179175710,,,,,,,None,None,
67,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,,None,None,
68,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,,None,None,
69,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3PRIME_UTR,1/1,NaN,9.667,Benign,NaN,chr3:181714163,,,,,,,None,None,
70,3,181714163,A,T,PASS,129,0.0,SOX2,,,NaN,nan,,,UTR_3,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,7/10,9.667,Benign,NaN,chr3:181714163,,,,,,,None,None,
71,3,179218304,A,G,PASS,116,7.000000000000001,PIK3CA,DELETERIOUS,rs121913274,545 545,PIK3CA,E545G,E545G,CDS,NONSYNONYMOUS,,PIK3CA,VCV000013656,E545G,NaN,NaN,NaN,121913274.0,171834.0004,Pathogenic/Likely pathogenic,NaN,https://www.ncbi.nlm.nih.gov/clinvar/variation...,NON_SYNONYMOUS,10/21,NaN,29.5,Deleterious,98.0,chr3:179218304,2627,"{'breast': 884, 'bowel': 347, 'uterus': 282, '...",{'545': 633},"{'545': {'breast': 174, 'bowel': 97, 'bladder'...",{'E545G': 21},"2,446",{'545': 619},15,True
72,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.49,Benign,NaN,chr3:169606408,,,,,,,None,None,
73,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.49,Benign,NaN,chr3:169606408,,,,,,,None,None,
74,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.374,Benign,NaN,chr3:169606408,,,,,,,None,None,
75,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.374,Benign,NaN,chr3:169606408,,,,,,,None,None,
76,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,1.599,Benign,NaN,chr3:169606408,,,,,,,None,None,
77,3,169606408,C,CA,PASS,116,7.5,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.599,Benign,NaN,chr3:169606408,,,,,,,None,None,
78,3,169451252,GA,G,PASS,154,8.3,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:169451252,,,,,,,None,None,
79,3,169238554,CA,C,PASS,153,0.0,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr3:169238554,,,,,,,None,None,
80,3,69848060,T,C,PASS,107,0.0,MITF,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/9,0.512,Benign,NaN,chr3:69848060,,,,,,,None,None,
81,3,53600934,C,G,PASS,136,0.0,CACNA1D,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/47,0.195,Benign,NaN,chr3:53600934,,,,,,,None,None,
82,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,Q261* Q243*,CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,198,{'261': 1},,True
83,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,Q261* Q243*,CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STOP_GAINED,9/17,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,198,{'261': 1},,True
84,3,52406255,G,A,PASS,120,0.0,BAP1,,rs772448753,"243 243,261",BAP1,Q243*,Q261* Q243*,CDS,STOP-GAIN,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,45.0,Deleterious,NaN,chr3:52406255,5,"{'eye': 1, 'kidney': 1, 'skin': 1, 'pleura': 1...",,,,198,{'261': 1},,True
85,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.022,Benign,NaN,chr3:169382849,,,,,,,None,None,
86,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,1.868,Benign,NaN,chr3:169382849,,,,,,,None,None,
87,3,169382849,C,CA,PASS,118,11.1,MECOM,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/16,2.193,Benign,NaN,chr3:169382849,,,,,,,None,None,
88,4,152369596,G,GA,PASS,148,0.0,FBXW7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,4/13,0.907,Benign,NaN,chr4:152369596,,,,,,,None,None,
89,4,152369596,G,GA,PASS,148,0.0,FBXW7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,4/13,0.382,Benign,NaN,chr4:152369596,,,,,,,None,None,
90,4,152369596,G,GA,PASS,148,0.0,FBXW7,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,4/13,0.369,Benign,NaN,chr4:152369596,,,,,,,None,None,
91,5,31463883,G,A,PASS,167,0.0,DROSHA,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,20/35,10.72,Benign,NaN,chr5:31463883,,,,,,,None,None,
92,5,80733107,A,G,PASS,138,0.0,MSH3,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,10/23,5.42,Benign,NaN,chr5:80733107,,,,,,,None,None,
93,5,132605268,C,T,PASS,117,0.0,RAD50,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,16/24,3.165,Benign,NaN,chr5:132605268,,,,,,,None,None,
94,6,157187897,G,A,PASS,132,0.0,ARID1B,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,13/19,3.339,Benign,NaN,chr6:157187897,,,,,,,None,None,
95,6,151891819,CA,C,PASS,117,0.0,ESR1,,,NaN,nan,,,INTRON,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chr6:151891819,,,,,,,None,None,
96,6,151891824,A,T,PASS,115,0.0,ESR1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,0.356,Benign,NaN,chr6:151891824,,,,,,,None,None,
97,6,151891824,A,T,PASS,115,0.0,ESR1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/7,0.356,Benign,NaN,chr6:151891824,,,,,,,None,None,
98,6,151913052,G,A,PASS,127,0.0,ESR1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,3/7,0.118,Benign,NaN,chr6:151913052,,,,,,,None,None,
99,7,148710746,C,G,PASS,167,0.0,CUL1,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/21,2.46,Benign,NaN,chr7:148710746,,,,,,,None,None,
100,7,55195555,C,T,PASS,212,0.0,EGFR,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,22/27,1.966,Benign,NaN,chr7:55195555,,,,,,,None,None,
101,7,151484856,C,T,PASS,138,0.0,RHEB,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REGULATORY,NaN,NaN,4.837,Benign,NaN,chr7:151484856,,,,,,,None,None,
102,7,151484856,C,T,PASS,138,0.0,RHEB,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,2/7,4.837,Benign,NaN,chr7:151484856,,,,,,,None,None,
103,7,55086578,C,G,PASS,195,1.7000000000000002,EGFR,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/27,11.38,Benign,NaN,chr7:55086578,,,,,,,None,None,

OncoKb Output

,chr_no,chr_pos,ref,alt,oncogenic,mutation_effect_known_effect,mutation_effect_description,gene_summary,variant_summary,tumor_type_summary,prognostic_summary,diagnostic_summary,diagnostic_implications,prognostic_implications,treatments,data_version,last_update
0,1,9665241,A,G,Unknown,Unknown,NaN,PIK3CD encodes a kinase involved in immune cel...,The PIK3CD *46* mutation has not specifically ...,NaN,NaN,NaN,[],[],[],v4.16,04/26/2017
1,1,11216105,T,A,Unknown,Unknown,NaN,"MTOR, an intracellular kinase that regulates c...",The MTOR *1039* mutation has not specifically ...,NaN,NaN,NaN,[],[],[],v4.16,01/16/2019

CKb output

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,NCBI Gene ID,CKB Core _Synonyms,CKB Core_GeneRole,CKB Core_Gene_Description
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2475,FRAP | FRAP1 | FRAP2 | RAFT1 | RAPT1 | SKS,Oncogene (PMID: 30606230),"MTOR, mechanistic target of rapamycin, is a se..."

merged_ckb

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,snp_pos1,Cancer Hotspot_Gene mutation_Sample frequency,Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition,Cancer Hotspot_Mutation site_Sample frequency,Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition,Cancer Hotspot_Exact Mutation_Sample frequency,Intogen_Gene Mutation_Sample frequency,Intogen_Mutation Site_Sample frequency,Intogen_Exact Mutation_Sample frequency,Intogen_Known Driver,OncoKB_link,OncoKB_oncogenic_status,OncoKB_mutation_effect,NCBI Gene ID,CKB Core _Synonyms,CKB Core_GeneRole,CKB Core_Gene_Description
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,chr1:9665241,,,,,,None,None,None,None,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,chr1:9665241,,,,,,,None,None,,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."

dbsnp output

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HCC1187BL,HCC1187C,Gene name_BED file,Depth,Allele Frequency (%),dbSNP_Id,gnomAD-Genomes,dbSNP_rs_id,gnomAD_value_dbSNP
0,1,9665241,.,A,G,.,PASS,DP=130;MQ=185.80;FractionInformativeReads=0.977,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:0.00:47,0:0.000:24,0:23,0:47:.:.","0/1:71.13:54,26:0.325:32,11:22,15:80:28,26,18,...",PIK3CD,130,0.0,NaN,NaN,NaN,NaN
1,1,11216105,.,T,A,.,PASS,DP=155;MQ=198.79;FractionInformativeReads=1.000,GT:SQ:AD:AF:F1R2:F2R1:DP:SB:MB,"0/0:-0.00:57,0:0.000:30,0:27,0:57:.:.","0/1:205.89:0,98:1.000:0,47:0,51:98:0,0,43,55:0...",MTOR,155,0.0,NaN,NaN,NaN,NaN

merged_dbsnp

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,dbSNP_rs_id,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,gnomAD_value_dbSNP,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,Cancer Hotspot_Gene mutation_Sample frequency,Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition,Cancer Hotspot_Mutation site_Sample frequency,Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition,Cancer Hotspot_Exact Mutation_Sample frequency,Intogen_Gene Mutation_Sample frequency,Intogen_Mutation Site_Sample frequency,Intogen_Exact Mutation_Sample frequency,Intogen_Known Driver,OncoKB_link,OncoKB_oncogenic_status,OncoKB_mutation_effect,NCBI Gene ID,CKB Core _Synonyms,CKB Core_GeneRole,CKB Core_Gene_Description
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,,,,,,None,None,None,None,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,,,,,,,None,None,,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."

DataFrame saved to /home/ubuntu/jupyter_notebooks/Internal/input_files/Somatic_SNV_with_pathogenic_var.vcf_cgp_snv_indel_Display_Table.xlsx

,#CHROM,POS,REF,ALT,FILTER,Depth,Allele Frequency (%),Gene name_BED file,SIFT4G_prediction,dbSNP,dbSNP_rs_id,Amino acid position,Gene Name,Amino acid change,dbNSFP Amino acid change,REGION,Mutation type,HGVS nomenclature,Gene,Clinvar_accession_no,Clinvar_Protein_change,gnomAD_value,gnomAD_value_dbSNP,1000_Genomes_value,ExAC_value,dbSNP_id,OMIM_id,Germline_classification,Somatic_clinical_impact,Clinvar_link,CADD_Consequence,Exon Number,Intron number,CADD_PHRED,CADD_Prediction,CADD_Grantham,Cancer Hotspot_Gene mutation_Sample frequency,Cancer Hotspot_Gene mutation_Sample frequency-Tumor_type_composition,Cancer Hotspot_Mutation site_Sample frequency,Cancer Hotspot_Mutation site_Sample frequency-Tumor_type_composition,Cancer Hotspot_Exact Mutation_Sample frequency,Intogen_Gene Mutation_Sample frequency,Intogen_Mutation Site_Sample frequency,Intogen_Exact Mutation_Sample frequency,Intogen_Known Driver,OncoKB_link,OncoKB_oncogenic_status,OncoKB_mutation_effect,NCBI Gene ID,CKB Core _Synonyms,CKB Core_GeneRole,CKB Core_Gene_Description
0,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INTRONIC,NaN,1/23,3.331,Benign,NaN,,,,,,None,None,None,None,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."
1,1,9665241,A,G,PASS,130,0.0,PIK3CD,,,NaN,NaN,nan,,,,nan,,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPSTREAM,NaN,NaN,3.331,Benign,NaN,,,,,,,None,None,,https://www.oncokb.org/hgvsg/1:g.9665241A>G?re...,,,5293,APDS | IMD14 | IMD14A | IMD14B | p110D | P110D...,Unknown,"PIK3CD, phosphatidylinositol 4,5-bisphosphate ..."